### ISSUE TITLE
nightly 3.8 build fails because of conflict

### ISSUE THREAD

**Issue by isidentical** [deadsnakes/issues#102]
(ported from a discord conversation)
https://github.com/thg-consulting/inspectortiger/runs/350876147#step:4:189

**Comment by asottile** [comment]
huh weird, I definitely got rid of those packages so I don't know what's installing them

I notice it's trying to install 3.8.0-... and the current nightly is 3.8.1~rc1 so something is up there

if you drop the `-distutils` package from your github actions does that fix it? (those packages don't exist for bionic for 3.7 / 3.8 any more)

**Comment by asottile** [comment]
the code is [already fixed](https://github.com/deadsnakes/python3.8-nightly/commit/f0b6878497af193e679c09876dcf9e4412301889) so there's nothing to do here from our side I'm afraid
