### ISSUE TITLE
Ubuntu repository not being in sync with github ??

### ISSUE THREAD

**Issue by flip111** [deadsnakes/issues#105]
I installed python3.8 on 23 december 2019 from ppa:deadsnakes and i get an old `site.py` file where [this fix](https://github.com/deadsnakes/issues/issues/76) was not included. The old version of the site.py is here

https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+files/libpython3.8-minimal_3.8.1-1+xenial3_amd64.deb

Notice that this is version `3.8.1-1+xenial3`

But when i look at the site.py of this repo https://github.com/deadsnakes/python3.8/blob/debian/3.8.1-1%2Bxenial3/Lib/site.py or download the `debian/3.8.1-1+xenial3` version from https://github.com/deadsnakes/python3.8/releases i get another site.py

This is causing problems in https://github.com/ipython/ipython/issues/12058

Maybe a new version without a new version tag was published and then it was skipped to upload to the repository and stayed on github only?

**Comment by asottile** [comment]
There was no action taken for #76 -- it is working exactly as intended (and as the upstream packages also work)

The `site.py` you linked is identical to the one in the cpython repository at that revision, we do apply debian/ubuntu's patches on top of it though so that's perhaps where things are a bit confusing for you? https://github.com/deadsnakes/python3.8/blob/debian/3.8.1-1%2Bxenial3/debian/patches/distutils-install-layout.diff

I'd suggest either:
- upgrade your version of `pexpect`
- utilize virtualenvs

**Comment by flip111** [comment]
Hi @asottile i wasn't aware of this diff that wasn't being applied. I thought this was a new issue, but i could have continued on #76 instead it seems.

When i type `python3.5 -m pip install pexpect` it says `Requirement already satisfied: pexpect in  /usr/lib/python3/dist-packages (4.0.1)`. I think this version pexpect is the latest version that still supports python3.5.

When i type `python3.8 -m pip install pexpect` it says `Requirement already satisfied: pexpect in ./.local/lib/python3.8/site-packages (4.7.0)`.

Why doesn't ppa:deadsnakes python3.8 use packages installed for python3.8 ??
> installing with sudo pip (or installing system wide python libraries without the system package manager) is asking for trouble

> in this case it's not our decision but debian's -- consider the upstream python3.7 package (which ships on ubuntu bionic (python3.6)):

In https://github.com/deadsnakes/issues/issues/76#issuecomment-447492503

I understand this reason. However consequence is that:

1. `pip install --user` packages are not included in path. (maybe also because of debian's decision) ?
2. `sudo pip` is not safe so can't change system packages for python3.8
3. `sudo pip` for 3.5 is not possible because dependency is on the latest version
4. it's not asked during installation whether to use (like debian) old system python3.5 packages so to "fix" this modifying system file site.py is needed. Or ...
5. python3.8 from deadsnakes can now only be used in virtualenvs when it so happens to be a dependency is no longer compatible with newer python3.8.

There seem to be a some options how it could "just work", but doesn't for various reasons. However please consider this stalemate situation, because mixing python3.8 stuff with python3.5 stuff is not working.

If it turns that there is "no way out" of this, perhaps on [the front page](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) it can be strongly suggested that the python's of deadsnakes are recommended to run in a virtualenv (or venv of course) because compatibility is not guaranteed.

**Comment by asottile** [comment]
for what it's worth, there's nothing special about deadsnakes's packaging here -- this is identical to the way debian packages non-release pythons:

- /usr/lib/python3/dist-packages -- shared packages
- /usr/lib/python3.5/dist-packages -- python3.5-specific packages
- /usr/lib/python3.8/dist-packages -- python3.8-specific packages
- /usr/local/lib/python3.8/dist-packages -- `sudo python3.8 -mpip install`d packages
- etc.

From my installation (granted this is bionic so slightly newer) -- I see the `sys.path` I expect:

```pycon
>>> import pprint
>>> import pprint, sys
>>> pprint.pprint(sys.path)
['',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/asottile/.local/lib/python3.8/site-packages',
 '/usr/local/lib/python3.8/dist-packages',
 '/usr/lib/python3/dist-packages']
```

that is, my `~/.local` site-packages come before the system installed packages:

```pycon
>>> import six
>>> six.__file__
'/home/asottile/.local/lib/python3.8/site-packages/six.py'
```

Can you provide a reproduction of what you're seeing? I suspect there's something you're not showing (ideally use `docker` so it is reproducible!)

**Comment by asottile** [comment]
> I think this version pexpect is the latest version that still supports python3.5.

**Comment by flip111** [comment]
Hi @asottile when i check my `sys.path` i get:
```
''
'/usr/lib/python38.zip'
'/usr/lib/python3.8'
'/usr/lib/python3.8/lib-dynload'
'/home/flip111/.local/lib/python3.8/site-packages'
'/usr/local/lib/python3.8/dist-packages'
```
This is AFTER i modified `/usr/lib/python3.8/site.py` by commenting https://github.com/deadsnakes/python3.8/blob/debian/3.8.1-1%2Bxenial3/debian/patches/distutils-install-layout.diff#L266-L268
I can uncomment those lines and look at sys.path again if you wish..

I have no idea why `python3.5 -m pip install` says pexpect is already satisfied with `4.0.1`

I'm going to wait with docker for the moment, because the OS has already been installed for some years now and i'm not confident that i will be able to reproduce exactly as it is on my laptop.

**Comment by asottile** [comment]
it says it is satisfied because `pexpect==4.0.1` satisfies the constraint you supplied `==*` -- in order for it to install something else you'd need to either `pexpect>...` or specify `--upgrade`

if you're using `python3-pip`, commenting out those lines probably breaks it for python3.8 by the way -- and modifying `site.py` kinda "voids the warranty" so to speak in that you're now in unsupported territory ;)

**Comment by flip111** [comment]
When i try `python3.5 -m pip install --upgrade pexpect` i get `ERROR: Cannot uninstall 'pexpect'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall`.

I can uncomment those lines again. That would mean venv is the only solution that works on my system (for the moment at least).

**Comment by asottile** [comment]
you also still haven't shown me what problem you're seeing -- when does the `python3/dist-packages` end up on your `sys.path` sooner than your `~/.local` -- and what happens when that happens?

**Comment by flip111** [comment]
This is with the `dist.py` file unmodified as it's in the ppa

```
» python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pprint
>>> import sys
>>> pprint.pprint(sys.path)
['',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/home/flip111/.local/lib/python3.5/site-packages',
 '/usr/lib/python3/dist-packages']
```

Then running `python3.8 -m jupyter notebook` works. So that's great (i had some confusion about this) because ...

`python3 notebook` (starting python3.5) was calling into python3.8 libraries which made me think it was starting python3.8

Unfortunately i can no longer reproduce the situation where python3.5 was loading python3.8 libraries because it can not find jupyter anymore.

Thanks for all the help @asottile , i think there is nothing left to talk about. But it's great to know that i didn't need to upgrade the pexpect version which was installed with the system python3.5 pip and i also don't need to use a venv!

**Comment by asottile** [comment]
magically fixd! 🎉
