### ISSUE TITLE
Building the packages for Debian

### ISSUE THREAD

**Issue by jhermann** [deadsnakes/issues#108]
### Deadsnakes PPA Builds for Debian in Docker

Not sure how I could add a page to the "docs" wiki. I wrote a Dockerfile that builds the 3.6 / 3.7 / 3.8 packages for Stretch and Buster, to get uniform builds on all 4 stable + old-stable Ubuntu + Debian releases.

See https://github.com/jhermann/ezpy/tree/master/deadsnakes#readme

**Comment by asottile** [comment]
awesome, looks great -- I wonder how closely they line up with the images in the [`runbooks`](https://github.com/deadsnakes/runbooks/tree/master/dockerfiles) repo

I also wonder if this is something we could incorporate "un"officially in our docs (very bare, maybe I should convert them to markdown files that can be more easily PRd) https://github.com/deadsnakes/docs

curious to hear your thoughts

**Comment by jhermann** [comment]
You can also open the wiki to public editing – vandalism is easily reverted, you have a full history, and abusers risk their github account. My experience with open wikis on GH is good so far.

But then, "inline edit" via the GH web UI on .md files in the main repo is also a good experience for contributors.

**Comment by jhermann** [comment]
Difference to runbooks is xvfb support (in my builds, tk-related tests are currently skipped), and actually building the packages as part of the container build.

**Comment by stefanor** [comment]
Not related to your docker containers, but there is a repo somewhat analogous to Deadsnakes, for Debian, here: https://people.debian.org/~paravoid/python-all/

**Comment by asottile** [comment]
feel free to submit a patch to https://github.com/deadsnakes/docs if you'd like to document this -- thanks!
