### ISSUE TITLE
python3.8-venv depends on python3-distutils

### ISSUE THREAD

**Issue by radix** [deadsnakes/issues#109]
### description

The pythonX.Y-venv packages (I've checked 3.7 and 3.8 so far) depend on "python3-distutils" instead of "pythonX.Y-distutils". "python3-distutils" seems wrong, since that's actually pointing at e.g. the python 3.6 version of distutils provided by Ubuntu Bionic.

#### cat /etc/lsb_release

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

#### uname -a

```
Linux Christopher-PC 4.19.81-microsoft-standard #1 SMP Fri Nov 1 14:28:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
"seems wrong" - is something actually broken? have you tried it? I promise you it's intentional :)

```console
$ dpkg -L python3-distutils | grep python3.7 | wc -l
54
$ dpkg -L python3-distutils | grep python3.8 | wc -l
54
```

**Comment by radix** [comment]
Ok, I'm confused. I don't have python3.6 on my system, but when I try to install python3.8-venv, it wants to install python3.6, via python3-distutils. That seems like a problem. I don't want Python 3.6 to be installed, I only want Python 3.8.

Here is what happens when I try to install python3.8-venv:

```
The following additional packages will be installed:
  libpython3-stdlib libpython3.6-minimal libpython3.6-stdlib python3 python3-distutils python3-lib2to3 python3-minimal python3.6 python3.6-minimal
Suggested packages:
  python3-doc python3-tk python3-venv python3.6-venv python3.6-doc binfmt-support
The following NEW packages will be installed:
  libpython3-stdlib libpython3.6-minimal libpython3.6-stdlib python3 python3-distutils python3-lib2to3 python3-minimal python3.6 python3.6-minimal python3.8-venv
```

It seems to be if python3.8-venv depended on python3.8-distutils instead of python3-distutils, I would be able to install it without having python3.6 installed too.

**Comment by asottile** [comment]
on bionic, python3-distutils provides the distutils packages for 3.6, 3.7, and 3.8 -- we cannot provide a python3.8-distutils package as it would conflict with python3-distutils -- see also #97 #98 #99 #100

**Comment by radix** [comment]
Hmm, still a little confused, since you say "we cannot provide a python3.8-distutils package", but I actually have a python3.8-distutils that I just installed from the deadsnakes PPA. am I using an out-of-date version or something?

I'm using `deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic main`, and `apt show -a python3.8-distutils` shows a single package with Version `3.8.0-1+bionic2` and `APT-Sources: http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic/main amd64 Packages`

Is that just there because there's no way to remove it from a PPA once it's been added?

Anyway, all that aside... is the conclusion that there is no way I can have python3.8 w/ a working distutils without having python3.6 installed, on Bionic, using the deadsnakes PPA?

**Comment by asottile** [comment]
hehe yeah so there's a weird quirk with ppas that makes it so you can't purge packages (or at least, I haven't figured out how to)

there is a way, but you won't like it -- it involves installing python3-distutils while ignoring its dependencies (there's something like `--nodeps`? I forget exactly)

**Comment by radix** [comment]
@asottile ok, thank you very much! I actually just tried doing a forced install without dependencies and it seems to be working... that works for my needs (building a docker image), so I'm happy.

Thanks very much for the explanation (and sorry that you had to go through it again for the... fourth time). Really appreciate your work!

**Comment by asottile** [comment]
no problem! glad to help :)

a real bummer the mess that upstream made :(

**Comment by cserpell** [comment]
Sorry for the revival of an old issue, but it seems the bionic `python3-distutils` does not provide 3.8 anymore: https://packages.ubuntu.com/bionic/all/python3-distutils/filelist . I am stuck with this problem.

**Comment by asottile** [comment]
@cserpell that's old python3-distutils (you want to look at `bionic-updates` -- https://packages.ubuntu.com/bionic-updates/all/python3-distutils/filelist):

```console
root@60fcf954fab3:/# cat /etc/lsb-release && dpkg -l | grep python3-distutils && dpkg -L python3-distutils | grep python3.8 | tail -1
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
ii  python3-distutils          3.6.9-1~18.04             all          distutils package for Python 3.x
/usr/lib/python3.8/distutils/versionpredicate.py
```
