### ISSUE TITLE
Support s390x, ppc64le, arm64v8

### ISSUE THREAD

**Issue by mattip** [deadsnakes/issues#110]
### description

I would like to use s390x, ppc64le, arm64v8 but it seems they are not built

### os information

xenial, bionic

This is for the [multibuild](https://github.com/matthew-brett/multibuild) system. It builds wheels with the manylinux images, and then would like to test them with different images. Right now the system tests with only x86_64 and i686 trusty images. I want to extend it matthew-brett/multibuild#314 these are being build by [multi-builder/docker-wheels](https://github.com/multi-builder/docker-wheels). I can build from source for the "alternative" architectures, but it seems it would be better if they existed in your ppa.

**Comment by asottile** [comment]
which of these boxes should I check

![Capture18](https://user-images.githubusercontent.com/1810591/75636960-0305d980-5bd8-11ea-85c2-e6002b5d094d.PNG)

**Comment by mattip** [comment]
The ones NumPy/Scipy are interested in are "PowerPC (powerpc)" and "IBM System z  (s390x)" - thanks

**Comment by asottile** [comment]
is powerpc == ppc64le -- or do you mean ppc64el 🤔 😕 

(legitimately asking -- I don't know 🤣)

**Comment by mattip** [comment]
I assume powerpc == ppc64le, which is what we need.

**Comment by asottile** [comment]
ah ok I've found a command which you can run to confirm which ones you need:

```bash
dpkg --print-architecture
```

debian's names are a little weird (like I'm used to calling it "Z" and not "s390x")

**Comment by mattip** [comment]
I did a [test travis run](https://travis-ci.org/multi-build/docker-images/builds/657133689) that only prints the name.

[s390x](https://travis-ci.org/multi-build/docker-images/jobs/657133694#L84) prints `s390x`

[ppc64le](https://travis-ci.org/multi-build/docker-images/jobs/657133693#L134) prints `ppc64el`, and the [apt-install commands](https://travis-ci.org/multi-build/docker-images/jobs/657056516#L169) in the real travis run also are getting the `ppc64el` variants. Travis label is `ppc64le` for [this architecture](https://docs.travis-ci.com/user/multi-cpu-architectures#testing-on-multiple-cpu-architectures). The [ubuntu wiki page](https://wiki.ubuntu.com/ppc64el) agrees this is the one I want: little endian. So in conclusion: `ppc64el`.

**Comment by asottile** [comment]
I've triggered builds of s390x and ppc64el for python3.5+ on xenial / bionic -- they should finish soon! https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+builds?build_text=&build_state=all

thanks again for the issue!
