### ISSUE TITLE
Python3.8 from this ppa won't use modules installed for python3 in Ubuntu 18.04

### ISSUE THREAD

**Issue by rs-fabrica** [deadsnakes/issues#112]
### description

I have a python module (python3-rados) installed for python3 in my Ubuntu 18.04.

In the Ubuntu original python 3.6.9 I have acess to this module but on deadsnaked 3.8.2 I don't even though I only installed python3-rados after installing python3.8 and making python3 point to python3.8

This python3-rados package is available with:

curl -L 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | apt-key add -
echo deb http://download.ceph.com/debian-nautilus/ bionic main | tee /etc/apt/sources.list.d/ceph.list

How can I make python3.8 access the modules installed at /usr/lib/python3 also (like python 3.6 does) and not only the ones installed at /usr/lib/python3.8?

#### lsb_release -a

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

#### uname -a

```
# uname -a
Linux 50d71ab13659 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
the default setup will do that by default assuming it is a pure python package:

```console
$ python3.8 -c 'import six; print(six)'
<module 'six' from '/usr/lib/python3/dist-packages/six.py'>
```

if it is a compiled binary you're out of luck, `cp36` `.so` files are not abi compatible by default -- I'd suggest using a virtualenv and installing packages there anyway

**Comment by rs-fabrica** [comment]
There might be an issue of compatibility but I can't tell because, despite the required package being installed in _/usr/lib/python3_, python3.8 doesn't see it:

```
# python3.8
Python 3.8.2 (default, Feb 26 2020, 02:56:10) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rados;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rados'
```

Python 3.6 has no problem accessing it:

```
# python3.6
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rados;
>>> 
```

Why can't python3.8 access a module installed in /usr/lib/python3?

**Comment by asottile** [comment]
what is `rados.__file__` in `python3`?

**Comment by asottile** [comment]
or just `print(rados)`
