### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by simondeziel** [deadsnakes/issues#114]
Ubuntu 20.04/Focal is about to be released (April 23rd, 2020) and it would be nice to have it supported by your PPA. Thanks!

**Comment by asottile** [comment]
yep, will be in due time -- the freeze hasn't happened yet so I've been holding off on building packages

note that for focal libssl1.0 is gone which means it'll be python3.5+ only (and maybe 2.7 if I get around to packaging that from scratch)

**Comment by asottile** [comment]
actually, looks like 2.7 will still be around in 20.04

**Comment by simondeziel** [comment]
Awesome, thanks!

**Comment by asottile** [comment]
these should all be present now!  (I just streamed making them on https://twitch.tv/anthonywritescode)
