### ISSUE TITLE
How can I install python3.9-pip?

### ISSUE THREAD

**Issue by sanderjo** [deadsnakes/issues#117]
### description

How can I install python3.9-pip?

```
root@320a0548dc96:~# python3.9
Python 3.9.0b1 (default, May 19 2020, 01:22:54) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@320a0548dc96:~# 
root@320a0548dc96:~# 
root@320a0548dc96:~# python3.9 -m pip
/usr/bin/python3.9: No module named pip
```

```
root@320a0548dc96:~# apt install python3.9-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3.9-pip
```

A `pt install python3-pip` will still python3.8, which I don't want; it gives interference with the python3.9 modules.

### os information

Ubuntu 20.04

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```

# paste the output of `uname -a` here
Linux 320a0548dc96 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
there is no such package, though you can ~usually use `python3.9 -m pip` and work with that

that said, installing packages to your system python is generally an anti pattern and I would suggest using a virtual environment instead

**Comment by sanderjo** [comment]
Thank you for replying.

> there is no such package, though you can ~usually use `python3.9 -m pip` and work with that

The thing is: `python3.9 -m pip` gives an error (see above). That is exactly my problem / this issue.

> that said, installing packages to your system python is generally an anti pattern and I would suggest using a virtual environment instead

I'm not sure what you mean with "anti pattern", but I'm doing this in a docker container. Does that count as OK?

**Comment by asottile** [comment]
did you install `python3-pip` before running `python3.9 -m pip`?

**Comment by sanderjo** [comment]
> did you install `python3-pip` before running `python3.9 -m pip`?

Yes, at first I did, and that install python3.8, and that gives interference between 3.8 and 3.9 (AFAIK)
So then I started a fresh docker, and I'm looking for a way to get the pure python3.9 pip...

**Comment by asottile** [comment]
I mean, you haven't really shown me what you've tried so I can only guess at where you're missing things but this works and is essentially what I suggested above (and you can find many duplicates in this issue tracker about the same thing and with the same suggestions):

```dockerfile
FROM ubuntu:focal

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        gnupg2 \
        python3-pip \
        software-properties-common \
    && add-apt-repository ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.9-dev \
        python3.9-distutils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["python3.9", "-m", "pip", "--help"]
```

```console
$ docker run --rm -ti py39-pip | head -10

Usage:   
  /usr/bin/python3.9 -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
write /dev/stdout: broken pipe
```

**Comment by asottile** [comment]
but also in general, even in docker, installing packages to the system outside of the system package manager can be problematic.  especially that it can change the versions of packages that are essential to functions of the distribution (of which many of the packages are written in python and only tested against the particular versions of packages which are "frozen" into the distribution).  upgrades and downgrades of those can cause system instability.  with a virtualenv, none of these problems exist because the application packages you are installing are entirely isolated from your system (kinda the point of a virtualenv!) -- plus your development environment will be much easier to match than a mishmash of system packages that may or may not interfere with your application code's python dependencies.

**Comment by sanderjo** [comment]
I was able to self-compile the module I needed, and now I can use it from python3.9:
```
python3.9 -m pip install mymodule --upgrade
```
 The module is now nicely in `/usr/local/lib/python3.9/dist-packages/`

@asottile Thank you for providing the PPA for Python3.9, and your answers!

**Comment by papb** [comment]
Just wanted to mention that in my case, this is what happened:

- I got a fresh Ubuntu 22.04.4
- It comes with Python 3.10 by default
- I started by installing the deadsnakes PPA and `apt install python3.9 python3.11`.
- I tried `pip` and `pip3` and `python3.9 -m pip` and `python3.11 -m pip` all failed.
- I ran `apt install python3-pip`
- Now everything works.
    - `pip` and `pip3` detect Python 3.10
    - `python3.9 -m pip` and `python3.9 -m pip3` detect Python 3.9
    - `python3.11 -m pip` and `python3.11 -m pip3` detect Python 3.11

All good. Thanks!
