### ISSUE TITLE
Restore system Python 3.8 on Ubuntu 20.04 after system upgrade

### ISSUE THREAD

**Issue by zgoda** [deadsnakes/issues#118]
### description

More of troubleshooting question than a real bug.

I had a Ubuntu 18.04 with Python 3.8.3 from deadsnakes then I blindly ran `do-release-upgrade` and now I have 20.04 with Python 3.8.3 from 18.04. Trying to force system 3.8.2 from Focal warns that half of the system will be uninstalled along the way and I am reluctant to try that to not end up with system that can be only reinstalled from scratch. Is there any other way to restore system provided Python 3.8?

Accidentally deadsnakes' 3.8.3 for 18.04 seems to work OK on 20.04 but I'd rather prefer to have clean system.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

#### uname -a

```
Linux PL006947 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
`apt reinstall python3` should maybe do it? -- but in general when running release upgrades you should delete your ppas and their packages first before upgrading

you could also look into apt pinning or do `apt install python3.8=...` where `...` is the `focal` version and that might fix it as well

this is kind of outside of the support of this repository and more of a general apt-get question, you might find better answers through something like stackoverflow or the ubuntu stackexchange

**Comment by zgoda** [comment]
`apt install python3.8 --reinstall` 1st tries to remove all packages that depend on Python 3.8 and this is huuuge. I just did not realize I have installed package in a version that is never than provided by system.

Anyway, thank you very much for your help, looks like I will need to wait in hope Ubuntu releases any newer Python 3.8.

**Comment by alexanderankin** [comment]
The output of this command is, for some odd reason, 0:

```bash
curl 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/dists/focal/main/binary-amd64/Packages.gz' | zcat | grep 'Package: python3.8' | wc -l
```

I am not sure if this is related to this issue or i should comment here... but anyways I was in the process of getting rid of other python packages and installing these ones, when i got hung up on this for a day.

**Comment by asottile** [comment]
@alexanderankin we don't provide python3.8 on 20.04 because that is the primary system python

**Comment by fox91** [comment]
Hi @zgoda,
I've solved with these commands:

```bash
sudo dpkg -P --force-depends libpython3.8 libpython3.8-minimal libpython3.8-stdlib python3.8 python3.8-minimal
sudo apt --fix-broken install
```
