### ISSUE TITLE
no valid OpenPGP data found.

### ISSUE THREAD

**Issue by DynamixYT** [deadsnakes/issues#120]
Hello, I am trying to add the deadsnakes/ppa repository to my ubuntu vps but it doesn't seem to be working because I get this everytime I try to add the repository:

```
gpg: keybox '/tmp/tmp6nmhdis9/pubring.gpg' created
gpg: /tmp/tmp6nmhdis9/trustdb.gpg: trustdb created
gpg: key BA6932366A755776: public key "Launchpad PPA for deadsnakes" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
```
I don't know how to fix either.
I am currently using Debian GNU/Linux 10 (buster)

**Comment by asottile** [comment]
can you share all of the commands you ran?

**Comment by DynamixYT** [comment]
I did
```
sudo add-apt-repository --remove ppa:deadsnakes/ppa

sudo apt update

sudo apt-key del BA6932366A755776

gpg --keyserver keyserver.ubuntu.com --recv-keys BA6932366A755776

gpg --export --armor BA6932366A755776 | sudo apt-key add -

sudo add-apt-repository ppa:deadsnakes/ppa

sudo apt update
```
and at that last sudo apt update, it shows same no valid openpgp thing.

**Comment by DynamixYT** [comment]
I did the things all in order btw

**Comment by asottile** [comment]
what does `lsb_release -a` say? could you fill out the issue template please

**Comment by asottile** [comment]
maybe #86 and #192 are of help?

**Comment by asottile** [comment]
I'm not sure where you got BA6932366A755776 as well, I don't see that on our ppa page

**Comment by DynamixYT** [comment]
1. the lsb_release -a says:
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
2. I can check those out

3. BA6932366A755776 is from this: 
```
gpg: keybox '/tmp/tmp6nmhdis9/pubring.gpg' created
gpg: /tmp/tmp6nmhdis9/trustdb.gpg: trustdb created
gpg: key BA6932366A755776: public key "Launchpad PPA for deadsnakes" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
``` 
in the 3rd gpg

**Comment by asottile** [comment]
technically we don't provide packages for debian, only ubuntu LTS distributions -- above you said you were installing on an ubuntu vps, are those commands from that vps or from your local machine?

**Comment by DynamixYT** [comment]
From that vps

**Comment by asottile** [comment]
so it's not ubuntu then?

**Comment by DynamixYT** [comment]
Wdym? (Sorry if I'm sounding stupid, this is my first time using this)

**Comment by asottile** [comment]
ubuntu (supported by this ppa) and debian (what ubuntu is based on, but not supported by the ppa) are quite a bit different.  ~sometimes you can get lucky and some of the ubuntu packages will work on debian without modification, but most of the times not.

it's unclear whether the differences between debian and ubuntu are what's causing your issues here or if it's some other networking / etc. issue (the linked issue mentions switching protocol when receiving a key for example)

~usually to use the packages we provide on another linux distribution you'll need to rebuild them from source.

**Comment by DynamixYT** [comment]
Hmm

**Comment by DynamixYT** [comment]
This vps is being hosted from Google Cloud Platform btw (if you need to know that info)

**Comment by asottile** [comment]
I can reproduce your same error message on `debian:buster` (via docker) -- which makes sense as it's not supported by the ppa (debian is not ubuntu)

so if you want to use the ppa, you'll need to use some flavor of ubuntu LTS (20.04 / 18.04 / 16.04)

**Comment by PortLordz** [comment]
I can verify installed ubuntu18.04 on fresh VPS, but it also refers to debian in multiple places. also have the same error, thats stops the update command from working after
