### ISSUE TITLE
Documentation line mildly incorrect

### ISSUE THREAD

**Issue by adamchainz** [deadsnakes/issues#125]
### description

This line in the PPA description:

```
- `python#.#-gdbm`: provides the standard library `gnu.dbm` module
```

Should read:

```
- `python#.#-gdbm`: provides the standard library `dbm.gnu` module
```

As the module is [`dbm.gnu`](https://docs.python.org/3.8/library/dbm.html#module-dbm.gnu) not 'gnu.dbm'.

### os information

n/a

**Comment by asottile** [comment]
thanks -- fixed!
