### ISSUE TITLE
Unable to locate package python3-distutils

### ISSUE THREAD

**Issue by gowthamcr** [deadsnakes/issues#126]
### description

Unable to locate package python3-distutils

### os information
Ubuntu 16.04
#### lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```
# paste the output of `uname -a` here
```

**Comment by asottile** [comment]
could you share what command you ran and what you tried to install?

**Comment by streamhsa** [comment]
add-apt-repository ppa:deadsnakes/ppa
apt-get update
apt-get install -y python3-distutils

**Comment by gowthamcr** [comment]
add-apt-repository ppa:deadsnakes/ppa
apt-get update
apt-get install -y python3-distutils

**Comment by asottile** [comment]
our repository does not provide python3-distutils -- that's upstream ubuntu's package.  ours will always be prefixed with `python#.#-...` or `libpython#.#-...`
