### ISSUE TITLE
deadsnake action missing apt-get update after add-apt-repository

### ISSUE THREAD

**Issue by sfdye** [deadsnakes/issues#128]
### description

The build failed for 2.6, 3.3, 3.4 where deadsnake action is used as suggested in this [comment](https://github.com/actions/setup-python/issues/102#issuecomment-660050654)

https://github.com/PythonCharmers/python-future/runs/881731480?check_suite_focus=true

```
 Reading state information...
  E: Unable to locate package python2.6-dev
  E: Couldn't find any package by glob 'python2.6-dev'
  E: Couldn't find any package by regex 'python2.6-dev'
  E: Unable to locate package python2.6-venv
  E: Couldn't find any package by glob 'python2.6-venv'
  E: Couldn't find any package by regex 'python2.6-venv'
  E: Unable to locate package python3-distutils
```

From build log:
```
Current runner version: '2.267.1'
Operating System
  Ubuntu
  16.04.6
  LTS
```

It seems `apt-get update` is missing in https://github.com/deadsnakes/action/blob/380daf10273e1474809a93e9281104e9f86632d6/index.js

**Comment by sfdye** [comment]
cc @asottile

**Comment by asottile** [comment]
use 18.04+, there's other problems with github actions on xenial

**Comment by sfdye** [comment]
```
Supported Ubuntu and Python Versions
  ====================================
  
  - Ubuntu 16.04 (xenial) Python 2.3 - Python 2.6, Python 3.1 - Python3.4, Python 3.6 - Python3.9
  - Ubuntu 18.04 (bionic) Python2.3 - Python 2.6, Python 3.1 - Python 3.5, Python3.7 - Python3.9
  - Ubuntu 20.04 (focal) Python3.5 - Python3.7, Python3.9
  - Note: Python2.7 (all), Python 3.5 (xenial), Python 3.6 (bionic), Python 3.8 (focal) are not provided by deadsnakes as upstream ubuntu provides those packages.
  - Note: for focal, older python versions require libssl1.0.x so they are not currently built
```

But python 2.6, 3.3, 3.4 are not supported in 20.04 (focal)

Full context:
https://github.com/actions/setup-python/issues/102

**Comment by asottile** [comment]
that's the support for deadsnakes itself, but github actions is a different story

**Comment by asottile** [comment]
see [the note in the README](https://github.com/deadsnakes/action#available-versions)

**Comment by sfdye** [comment]
```
note: this action is incompatible with ubuntu-16.04 due to a limitation in add-apt-repository

```
Ok I see. Is there an issue for this with github action?

**Comment by asottile** [comment]
not that I know of, xenial is very old so I didn't bother

**Comment by tueda** [comment]
I got similar errors for 2.6, 3.2 and 3.3 (3.4 was OK) on **bionic**:

https://github.com/tueda/formset/runs/2212050313?check_suite_focus=true

```
Current runner version: '2.277.1'
Operating System
  Ubuntu
  18.04.5
  LTS
```
```
install python2.6
   sudo apt-get install -y --no-install-recommends python2.6-dev python2.6-venv python3-distutils
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package python2.6-venv
  E: Couldn't find any package by glob 'python2.6-venv'
  E: Couldn't find any package by regex 'python2.6-venv'
Error: Process completed with exit code 1.
```

**Comment by asottile** [comment]
@tueda `venv` didn't exist before python3.4 so it's difficult to bootstrap an isolated environment -- realistically 3.4+ is all that's "supported" (you could craft your own setup script which installs 2.6 from deadsnakes and finesses the right pip / virtualenv / etc. versions to bootstrap it (but I have no interest in maintaining that))

**Comment by asottile** [comment]
there's really no reason in 2021 to still support such ancient and dead versions

**Comment by tueda** [comment]
@asottile Thank you for your comment and clarification.

My Python script in this case uses only the standard library in 2.6 + `argparse`, which seems to be installed by default in many distributions (CentOS 6, Scientific Linux 6, etc.). The test is aiming to check if the script runs with the default `python`. Installing `venv` is not mandatory.

But it is true that such ancient distributions reached EOL eventually in the last autumn. Probably I should stop supporting 2.6.

Anyway, I think it is worth explicitly mentioning in the action's README that it does not work with < 3.4.
