### ISSUE TITLE
How can I fix the repository to be "secure" ? 

### ISSUE THREAD

**Issue by cyberchucktx** [deadsnakes/issues#129]
### description

How can I fix the repository to be "secure" ? 

When I followed the instructions within the article 
"How to Install Python 3 on Ubuntu 18.04 or 20.04" (at https://phoenixnap.com/kb/how-to-install-python-3-ubuntu )

It says to use 

add-apt-repository ppa:deadsnakes/ppa

Which yields: 

E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### os information
Ubuntu 19.10 

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

#### uname -a

```
# paste the output of `uname -a` here
Linux ubuntu-virtual 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by asottile** [comment]
the ppa does not provide packages for `eoan` -- only for LTS releases -- you can try building them yourself from source if you'd like to use them on eoan (or sometimes a similar LTS will work, though it is unsupported)
