### ISSUE TITLE
3.9-dev install fails to complete via GitHub Action (distutils/lib2to3 conflicts?)

### ISSUE THREAD

**Issue by webknjaz** [deadsnakes/issues#139]
### description

Not sure what exactly is happening here. But it looks like some of the subpackages for stdlib modules like `distutils`/`lib2to3` have conflicting files and when apt/dpkg attempts to unpack them, it fails to overwrite what's on disk.

Ref: https://github.com/pypa/setuptools/runs/1269036965#step:4:179
```console
  Unpacking python3.9-dev (3.9.0-78-g0fbddb14dc-1+focal1) ...
  Selecting previously unselected package python3.9-lib2to3.
  Preparing to unpack .../7-python3.9-lib2to3_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb ...
  Unpacking python3.9-lib2to3 (3.9.0-48-g5b1fdcacfc-1+focal1) ...
  dpkg: error processing archive /tmp/apt-dpkg-install-I34wpn/7-python3.9-lib2to3_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb (--unpack):
   trying to overwrite '/usr/lib/python3.9/lib2to3/Grammar.txt', which is also in package python3-lib2to3 3.8.5-1~20.04.1
  dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
  Selecting previously unselected package python3.9-distutils.
  Preparing to unpack .../8-python3.9-distutils_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb ...
  Unpacking python3.9-distutils (3.9.0-48-g5b1fdcacfc-1+focal1) ...
  dpkg: error processing archive /tmp/apt-dpkg-install-I34wpn/8-python3.9-distutils_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb (--unpack):
   trying to overwrite '/usr/lib/python3.9/distutils/README', which is also in package python3-distutils 3.8.5-1~20.04.1
  dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
  Selecting previously unselected package python3.9-venv.
  Preparing to unpack .../9-python3.9-venv_3.9.0-78-g0fbddb14dc-1+focal1_amd64.deb ...
  Unpacking python3.9-venv (3.9.0-78-g0fbddb14dc-1+focal1) ...
  Errors were encountered while processing:
   /tmp/apt-dpkg-install-I34wpn/7-python3.9-lib2to3_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb
   /tmp/apt-dpkg-install-I34wpn/8-python3.9-distutils_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb
  E: Sub-process /usr/bin/dpkg returned an error code (1)
```

https://github.com/deadsnakes/issues/issues/136#issuecomment-705793174 implies that it's been fixed but I'm not sure if the fix gets pulled into the GHA setup.

FWIW this is triggered by
```yaml
- uses: deadsnakes/action@v1.0.0
  with:
    python-version: 3.9-dev
```
_(https://github.com/pypa/setuptools/runs/1269036965#step:4:3)_

#### lsb_release -a

GHA/Ubuntu focal

#### uname -a

N/A

**Comment by asottile** [comment]
iiiinteresting, it's trying to install two different package versions, including one that no longer exists:

```
   Get:7 http://ppa.launchpad.net/deadsnakes/nightly/ubuntu focal/main amd64 python3.9-dev amd64 3.9.0-78-g0fbddb14dc-1+focal1 [501 kB]
  Get:8 http://ppa.launchpad.net/deadsnakes/nightly/ubuntu focal/main amd64 python3.9-lib2to3 all 3.9.0-48-g5b1fdcacfc-1+focal1 [131 kB]
```

(notice how one is 78 and the other is 48)

**Comment by webknjaz** [comment]
🤯

**Comment by asottile** [comment]
![image](https://user-images.githubusercontent.com/1810591/96351271-21d5b500-106f-11eb-8bed-41aeaebf6f76.png)

**Comment by asottile** [comment]
shrugs, I'm deleting the old packages -- hopefully that fixes it? not sure why they're sticking around

**Comment by webknjaz** [comment]
@asottile by the way, have you considered adding a scheduled run to https://github.com/deadsnakes/action so that dogfooding would alert about such things before they are reported?

**Comment by asottile** [comment]
I haven't, the nightlies are noisy enough as is

**Comment by webknjaz** [comment]
I would've reported earlier but setuptools had a bunch of other unresolved problems that shadowed this one :(

**Comment by webknjaz** [comment]
@asottile just retriggered one of the PRs and nothing changed: https://github.com/pypa/setuptools/pull/2431/checks?check_run_id=1269204557#step:4:178

**Comment by webknjaz** [comment]
On your screenshot, you show Python 3.8. Did you do this for 3.9-dev too?

**Comment by asottile** [comment]
there's three boxes checked, it takes up to 60 minutes for deletion according to the next screen which I did not take a screenshot of

**Comment by webknjaz** [comment]
The log still has these two entries:
```console
  Get:8 http://ppa.launchpad.net/deadsnakes/nightly/ubuntu focal/main amd64 python3.9-lib2to3 all 3.9.0-48-g5b1fdcacfc-1+focal1 [131 kB]
  Get:9 http://ppa.launchpad.net/deadsnakes/nightly/ubuntu focal/main amd64 python3.9-distutils all 3.9.0-48-g5b1fdcacfc-1+focal1 [196 kB]
```

**Comment by webknjaz** [comment]
@asottile I looked into https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly/+packages and noticed that 3.9 for xenial and bionic list `python3.9-lib2to3` and `python3.9-distutils` but focal does not. Is this expected?

**Comment by webknjaz** [comment]
If there's no deb packages, it'd explain why apt falls back to older versions.

**Comment by asottile** [comment]
yes

**Comment by asottile** [comment]
it doesn't really explain the fallback, the old packages shouldn't exist (launchpad replaces source packages with newer versions, you can't publish multiple versions of a package in a ppa)

**Comment by webknjaz** [comment]
So I've done a bit more digging.

I've downloaded http://ppa.launchpad.net/deadsnakes/nightly/ubuntu/dists/focal/main/binary-amd64/Packages.gz and here's the only entry for `python3.9-distutils` it contains:
```console
Package: python3.9-distutils
Source: python3.9
Priority: optional
Section: python
Installed-Size: 771
Maintainer: Matthias Klose <doko@debian.org>
Architecture: all
Version: 3.9.0-48-g5b1fdcacfc-1+focal1
Depends: python3.9-lib2to3 (>= 3.6.4)
Filename: pool/main/p/python3.9/python3.9-distutils_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb
Size: 196276
MD5sum: f0d4399275b99a8bdc0fc22773afc086
SHA1: 276fbf724da062e221e17d50fdd79cb5c180858d
SHA256: e3a0a1a9689e3c603f43d109577ad42c7cb12bbd4b0a3c2f2fb6cceecab832f6
Description: distutils package for Python (version 3.9)
Description-md5: 496d7b49faf0bf4ffd0a35c07b9f752c
Multi-Arch: foreign
```

Also, looking at http://ppa.launchpad.net/deadsnakes/nightly/ubuntu/pool/main/p/python3.9/ there's a number of packages that are in fact with different versions:
```console
...
￼	python3.9-distutils_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb	2020-10-08 09:32	192K	 
￼	python3.9-distutils_3.9.0-76-gb30934e9af-1+bionic1_all.deb	2020-10-16 09:40	192K	 
￼	python3.9-distutils_3.9.0-76-gb30934e9af-1+xenial1_all.deb	2020-10-16 09:40	192K	 
￼	python3.9-distutils_3.9.0-78-g0fbddb14dc-1+bionic1_all.deb	2020-10-17 10:40	192K	 
￼	python3.9-distutils_3.9.0-78-g0fbddb14dc-1+xenial1_all.deb	2020-10-17 10:40	192K	 
...
￼	python3.9-distutils_3.9.0-48-g5b1fdcacfc-1+focal1_all.deb	2020-10-08 09:32	192K	 
￼	python3.9-distutils_3.9.0-76-gb30934e9af-1+bionic1_all.deb	2020-10-16 09:40	192K	 
￼	python3.9-distutils_3.9.0-76-gb30934e9af-1+xenial1_all.deb	2020-10-16 09:40	192K	 
￼	python3.9-distutils_3.9.0-78-g0fbddb14dc-1+bionic1_all.deb	2020-10-17 10:40	192K	 
￼	python3.9-distutils_3.9.0-78-g0fbddb14dc-1+xenial1_all.deb	2020-10-17 10:40	192K	 
...
```

Look at 48/76/78. If I understand your earlier explanation correctly, those shouldn't co-exist, right?

Also, if you remove `*-48-*`, I suppose it's `*-78-*` alternative won't appear there magically, correct?

**Comment by asottile** [comment]
read https://github.com/deadsnakes/issues/issues/136#issuecomment-705658565 you seem confused still

**Comment by webknjaz** [comment]
Yep, I'm confused and so I'm trying to get a full picture.

At least, I've confirmed that it's reproducible outside of GHA. The following triggers the same errors:
```console
$ docker run -it --rm ubuntu bash -c 'apt-get update && apt-get install software-properties-common && add-apt-repository ppa:deadsnakes/nightly && apt-get install -y --no-install-recommends python3.9-dev python3.9-venv python3.9-distutils'
```

**Comment by asottile** [comment]
please please just wait an hour thanks
