### ISSUE TITLE
gpg timeout in dockerfile

### ISSUE THREAD

**Issue by hoosierEE** [deadsnakes/issues#140]
I tried to build this exact Dockerfile (using Docker Desktop on MacOS) and it fails with `Error: retrieving gpg key timed out.`

Interestingly, building this Dockerfile works on Linux.

Any suggestions?

```dockerfile
FROM ubuntu:xenial
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository ppa:deadsnakes \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.6-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
```

_Originally posted by @asottile in https://github.com/deadsnakes/issues/issues/53#issuecomment-372433273_

**Comment by asottile** [comment]
sounds like a problem with docker desktop and not an issue with deadsnakes

unfortunately I can't really spend my freetime to help diagnose things outside my control

**Comment by hoosierEE** [comment]
That's fair, I'll take it up with the Docker people.

**Comment by tekknolagi** [comment]
@hoosierEE did you ever take it up with them? Have a link?

**Comment by hoosierEE** [comment]
Sorry, it's been so long I forgot how this was resolved.
