### ISSUE TITLE
ERROR: '~deadsnakes' user or team does not exist 

### ISSUE THREAD

**Issue by silviatgl** [deadsnakes/issues#141]
### Hi all! when I try to install python3.8 it tells me that the user does not exist. It is a virtual Oracle machine running ubuntu. I tried many things, any idea what can be causing the issue? thank you in advance

```
sudo add-apt-repository ppa:deadsnakes/ppa
Cannot add PPA: 'ppa:~deadsnales/ubuntu/ppa'
ERROR: '~deadsnakes' user or team does not exist 
```

**Comment by asottile** [comment]
that says deadsnales, you've got a typo

**Comment by silviatgl** [comment]
thanks
