### ISSUE TITLE
fails to update apt-get using PPA and cannot install pythhon3.6

### ISSUE THREAD

**Issue by yasir047** [deadsnakes/issues#142]
### description
the ppa is not working and it is throwing error.
I did the following steps and got error in the last one

> sudo apt-get install software-properties-common
> sudo add-apt-repository ppa:deadsnakes/ppa 
> sudo apt-get update

```
W: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu hirsute Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

#### uname -a

```
Linux ip-10-8-17-121 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux
```

**Comment by hmcclungiii** [comment]
I'm having the exact same issue.

**Comment by yasir047** [comment]
I have fixed the issue by the following steps:
---

```
wget https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz
tar xvf Python-3.6.9.tgz
cd Python-3.6.9
./configure --enable-optimizations --enable-shared --with-ensurepip=install
make -j8
sudo make altinstall
python3.6


virtualenv -p python3.6 venv
```

**Comment by asottile** [comment]
deadsnakes is only for ubuntu LTS releases, not debian 9.4

**Comment by georvoug** [comment]
@asottile I have the same problem. I have Ubuntu 20.10  and I want to do : 
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
However the following problem occurs:
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu groovy Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
What would you recommend me to do

**Comment by asottile** [comment]
deadsnakes is only for ubuntu LTS releases, not ubuntu 20.10

**Comment by fatbringer** [comment]
> ## I have fixed the issue by the following steps:
> ```
> wget https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz
> tar xvf Python-3.6.9.tgz
> cd Python-3.6.9
> ./configure --enable-optimizations --enable-shared --with-ensurepip=install
> make -j8
> sudo make altinstall
> python3.6
> 
> 
> virtualenv -p python3.6 venv
> ```

i am not sure what i did wrong but i can only seem to launch python from that folder insttead of everywhere else.
Also the comment works for other versions of python, such as python 3.8.

The only thing that still confuses me is
 how do you make it such that you can run python3.6 or python3.8 from a terminal from any folder ?
