### ISSUE TITLE
Support for Ubuntu 20.10 - Groovy Gorilla

### ISSUE THREAD

**Issue by bertonha** [deadsnakes/issues#143]
Hello guys any plan to support the new version of ubuntu ?
Ubuntu 20.10 - Groovy Gorilla

**Comment by asottile** [comment]
we only support LTS as it's a lot of work to put up these packages, sometimes you can reuse packages from previous versions on later versions of you can build them yourself

**Comment by Bengt** [comment]
I gave this a shot, but unfortunately it does not work at first try. Some libraries Python uses have changed versions between Ubuntu 20.04 LTS (Focal Fossa) in Ubuntu 20.10 (Groovy Gorilla). Therefore, you cannot reuse the packages from the PPA directly in this case. Instead you have to at least recompile them against 20.10 libraries or possibly make changes to the Python source code first.
