### ISSUE TITLE
Add dependency on ca-certificates

### ISSUE THREAD

**Issue by tiran** [deadsnakes/issues#144]
### description

The Python packages in the deadsnakes PPA don't have a dependency on ``ca-certificates``. The lack of ca-certificates in a Debian or Ubuntu minimal container image breaks Python's ssl module and standard library modules. For example the ``urlib`` module requires a system system trust store with root CA certificates to validate HTTPS connections.

I opened https://bugs.launchpad.net/ubuntu/+source/python3.9/+bug/1879310 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960869 in May 2020. So far the problem has not been addressed.

Could you please address the issue in deadsnakes directly until Ubuntu and Debian catch up? The fix is a simple one-line change to ``debian/control``. Just add a *requires* or *recommends* dependency on ``ca-certificates``.

**Note**: The package that provides the ``add-apt-repository`` command, pulls in ``ca-certificates`` already. But it's possible to install packages from the PPA ``http://ppa.launchpad.net/deadsnakes/ppa/ubuntu`` directly. Direct installations are missing ``ca-certificates`` package by default.

You can find a reproducer for the issue in my repository https://github.com/tiran/distro-truststore .

### os information

All Debian/Ubuntu versions, Python versions, and platforms are affected.

**Comment by asottile** [comment]
I usually try to stick to debian's setup but I think this makes sense

I'm going to tentatively set this to `Recommends:` as it's not _required_ to run all python code -- the one problem with `Depends: ca-certificates` is that `ca-certificates` `Depends: openssl` which brings in a suite of software that's unnecessary for python

**Comment by asottile** [comment]
if you're in the mood of yelling at debian -- you might want to get them to do this too :) https://github.com/deadsnakes/python3.9/commit/d8216a1f585dac9db805d4e3c57f29535cf84cf8

**Comment by tiran** [comment]
Good catch! @pganssle will be happy that at least deadsnakes is fixed.

**Comment by tiran** [comment]
@asottile Is https://gist.github.com/tiran/2dec9e03c6f901814f6d1e8dad09528e enough yelling for you?

**Comment by asottile** [comment]
ah yeah I read that already :)

**Comment by tiran** [comment]
https://bugs.launchpad.net/ubuntu/+source/python3.9/+bug/1904271

**Comment by tiran** [comment]
> [bugs.launchpad.net/ubuntu/+source/python3.9/+bug/1904271](https://bugs.launchpad.net/ubuntu/+source/python3.9/+bug/1904271)

Aaaand closed as *invalid*

**Comment by asottile** [comment]
😭

**Comment by stefanor** [comment]
FWIW: https://salsa.debian.org/cpython-team/python3/-/commit/b8cdbed9dd8bfdca4dc54a4559e0bfdaf46347f4

**Comment by asottile** [comment]
sweeet  -- I've applied a similar patch to python3.3+ -- I actually had trouble with everything older than that because the pristine-tar data seems incompatible with the gbp version I'm using.  but that's ok, those packages are basically dead-dead anyway.

in 3.9+ I added tzdata as a dependency, and in all versions I added ca-certificates as a recommends for the `-stdlib` package (in 3.3 I added it to the libpython package since there isn't a separate `-stdlib` package there)
