### ISSUE TITLE
pip not installed when installing python 3.9

### ISSUE THREAD

**Issue by msoultan** [deadsnakes/issues#145]
### description
I'm not totally sure where the problem lies as this is the first time I've encountered this, but according to this ticket I submitted on the pip github, pip is supposed to be included when python 3.9 is installed via apt:

https://github.com/pypa/pip/issues/9130

but apparently it isn't:

```
$ python3.9 -m pip --version
/usr/bin/python3.9: No module named pip
```

Here's how I've installed python 3.9:

```
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.9
```

Here's exactly what I'm running into when trying to install pip via the instructions on the pip site:

```
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1842k  100 1842k    0     0  4168k      0 --:--:-- --:--:-- --:--:-- 4159k
$ python3.9 get-pip.py --user
Traceback (most recent call last):
  File "/tmp/get-pip.py", line 23704, in <module>
    main()
  File "/tmp/get-pip.py", line 198, in main
    bootstrap(tmpdir=tmpdir)
  File "/tmp/get-pip.py", line 120, in bootstrap
    import setuptools  # noqa
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 14, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 24, in <module>
    from setuptools.depends import Require
  File "/usr/lib/python3/dist-packages/setuptools/depends.py", line 7, in <module>
    from .py33compat import Bytecode
  File "/usr/lib/python3/dist-packages/setuptools/py33compat.py", line 54, in <module>
    unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

So how do I get pip installed?

Thanks!
Mike

#### lsb_release -a

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

#### uname -a

```
$ uname -a
Linux u7c3fa8eaaf1b59.ant.amazon.com 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
correct, you need to separately install `python3-pip` and then use `python3.9 -m pip` to install packages

though I'd strongly suggest against installing packages globally and instead use a virtualenv

see also these duplicate issues: https://github.com/deadsnakes/issues/issues?q=is%3Aissue+pip+is%3Aclosed

**Comment by asottile** [comment]
the error you're seeing is a bug in get-pip.py by the way -- I'd suggest reporting that to pypa/pip -- though I suspect they already know about this issue

**Comment by msoultan** [comment]
I provided the ticket in my initial post that lists this particular error and they said I'm installing pip incorrectly and sent me this way :p

So if I'm understanding correctly, pip (outside of a virtual environment) is essentially going by the wayside and all pip installs performed outside of a virtual environment should be performed using `python3.9 -m pip install ...`?  It seems like getting a pip3.9 executable is no longer possible due to the issue raised in the linked ticket.

**Comment by msoultan** [comment]
Oh, and one other thing, if I'm doing this right, this would be the installation process?

```
# install python3.9
sudo apt-get update
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa --yes
sudo apt-get update
sudo apt-get install python3.9 --yes

# install pip
sudo apt-get install python3-pip --yes
python3.9 -m pip install pip --upgrade
curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
python3 /tmp/get-pip.py --user # install base python3 version after 3.9 so pip3 stays associated with python3 and not python3.9
python /tmp/get-pip.py --user # install the python2 version last so the pip binary is not overwritten with the python3 version
rm /tmp/get-pip.py
```

The reason I'm doing the get-pip.py stuff is because upgrading python3.9 pip overwrites `pip` and `pip3` which historically link to python2.7 and python3.6 (in the case of Ubuntu 16) and I thought that changing those, especially `pip3` can break system-level stuff.  It kinda boggles me that they overwrite pip and pip3, but it is what it is...

**Comment by asottile** [comment]
sounds like you missed what they said in the linked ticket -- your setuptools is too old so you need to upgrade that

**Comment by asottile** [comment]
but yeah, my official suggestion is don't ever use global pip, and instead use virtualenvs.  you'll have a much nicer time

**Comment by msoultan** [comment]
Ok, so per your suggestion I reinstalled setuptools and finally things are working - for some reason I thought installing pip took care of that?  I've never had to install setuptools before... this is all really confusing.

Anyways, now it seems like this is the process to get pip installed:

```
# install pip
sudo apt-get install python3-pip --yes
python3.9 -m pip install pip --upgrade
python3.9 -m pip install setuptools --force-reinstall
```

Does installing pip really require this many steps?  Further, it seems like this isn't documented anywhere, and the only thing that I've ever seen documented for installing pip with apt is just to install python3-pip and that's it, even though it's a really old version.  Am I missing something?

**Comment by asottile** [comment]
18.04 is kind of old a little bit so that's probably why you ran into a bit of a rocky start.  python3.9 made a breaking change in the `html.parser` module which has confused older versions of `setuptools`

**Comment by msoultan** [comment]
Interesting - so you're thinking as we shift to 20.04 that just doing ```apt install python3.9 python3-pip``` will prove sufficient?  I'm installing python3.9 on 600+ machines (which are mostly 16.04) so I want to make sure I'm doing it the right way.

Thanks!

**Comment by asottile** [comment]
yeah probably, setuptools is much newer on 20.04:

```console
$ apt-cache show python3-setuptools | grep Version
Version: 45.2.0-1
```

**Comment by msoultan** [comment]
Ok - thanks for your help on this!

**Comment by msoultan** [comment]
That being said, should I be installing setuptools via apt or is it ok to use `python3.9 -m pip install setuptools`?

**Comment by asottile** [comment]
again, I wouldn't recommend global installation of python packages, use a virtualenv -- but whichever approach works for you

**Comment by msoultan** [comment]
Besides `sudo apt-get install python3-pip`, are any of the commands installing it globally?

```
# install pip
sudo apt-get install python3-pip --yes
python3.9 -m pip install pip --upgrade
python3.9 -m pip install setuptools --force-reinstall
```
Oh whoops... I should be putting --user after the upgrade and setuptools commands, huh?

**Comment by asottile** [comment]
yes, all three are installing global python packages
