### ISSUE TITLE
Instability of service

### ISSUE THREAD

**Issue by nedrebo** [deadsnakes/issues#147]
# Description

We use this PPA for our CI. It could be that this use case is covered by:

> If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk.

But I'll report the issue anyway and you can do with it what you feel is best.

When we run `add-apt-repository ppa:deadsnakes/ppa -y` we quite often (maybe 0.2% of times) get the following error:

```
Cannot add PPA: 'ppa:~deadsnakes/ubuntu/ppa'.
The team named '~deadsnakes' has no PPA named 'ubuntu/ppa'
Please choose from the following available PPAs:
 * 'nightly':  nightly python builds
 * 'ppa':  New Python Versions
```

# OS information

## Guest OS

`docker run ubuntu:16.04`

## Host OS

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

```
$ docker info
...
 Server Version: 19.03.8
...
```

## Host `uname -a`

```
$ uname -a
Linux ci-agent-9 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
I'm not sure where you got the command `add-apt-repository ppa:deadsnakes/ubuntu/ppa` -- I believe the command is supposed to be `add-apt-repository ppa:deadsnakes/ppa`

my guess is the way that launchpad deploys ppas has some sort of symlink race with `ubuntu/ppa` -> `ppa` that you're running into?

could you try without the `ubuntu/` bit and see if that improves things?

**Comment by nedrebo** [comment]
I will do that and report back in some weeks. Thx.

**Comment by nedrebo** [comment]
Oh no, I think you misread the issue. Our command is unfortunately already `add-apt-repository ppa:deadsnakes/ppa -y`. It is the error message that contains the additional `ubuntu/`.

**Comment by asottile** [comment]
hmmm weird

another alternative might be to just add the repository directly using the sources file

for example:

```console
$ cat /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-focal.list 
deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main
# deb-src http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main
```

**Comment by cjwatson** [comment]
There may be an api.launchpad.net reliability issue of some kind here, but with the extremely minimal diagnostics provided by add-apt-repository it's not really possible to be sure.  I'd start by filing a bug report on add-apt-repository (using `ubuntu-bug /usr/bin/add-apt-repository`) asking for it to actually show what errors it ran into rather than just silently falling back to something confusing in the way that it currently does.

By the way, `ppa:deadsnakes/ppa` and `ppa:deadsnakes/ubuntu/ppa` are synonymous.

**Comment by knatten** [comment]
This, from `man add-apt-repository` might be a good idea:

```
-m, --massive-debug Print a lot of debug information to the command line
```

**Comment by cjwatson** [comment]
I mean, maybe, but you generally don't want to run with massive debugging on all the time in the hope of catching a 1-in-500 failure.  `add-apt-repository` still needs to be clearer when things fail.

**Comment by knatten** [comment]
> I mean, maybe, but you generally don't want to run with massive debugging on all the time in the hope of catching a 1-in-500 failure. `add-apt-repository` still needs to be clearer when things fail.

Sure, but for now I think that's a way to get some debug output in the mean time. I checked, and in the success case, `--massive-debug` isn't really massive at all, it seems to just dump the resulting `sources.list` to stdout.

**Comment by asottile** [comment]
since I don't think there's anything actionable from my side and I haven't heard back in a while -- closing this out
