### ISSUE TITLE
[Legal Issue] Wrong Maintainer in control files

### ISSUE THREAD

**Issue by carstencodes** [deadsnakes/issues#149]
### description

We're currently checking, if deadsnakes python distribution packages can be used to deploy python applications using python 3.9 on older revisions of Ubuntu.

I noticed, that the maintainer in the control files seems not to be set appropriately. Since the source seems to be a mirror of the debian repository, the original maintainer (Matthias Klose) is set to be the maintainer. Taking a look at deadsnakes member list, he is not part of this project.

> Every package must have a maintainer, except for orphaned packages as described below. The maintainer may be one person or a group of people reachable from a common email address, such as a mailing list. The maintainer is responsible for maintaining the Debian packaging files, evaluating and responding appropriately to reported bugs, uploading new versions of the package (either directly or through a sponsor), ensuring that the package is placed in the appropriate archive area and included in Debian releases as appropriate for the stability and utility of the package, and requesting removal of the package from the Debian distribution if it is no longer useful or maintainable. [1]

According to this definition from the debian rules, the maintainer should be changed for the packages.

### os information

OS Independent

### finals

Can you confirm it's an issue, that happened by mistake? Or is it intentional?

--------
cc  @sschukat
--------
[1] https://www.debian.org/doc/debian-policy/ch-binary.html#s-maintainer

**Comment by asottile** [comment]
we mirror the upstream packages as closely as possible -- we don't publish to debian itself so their guidelines don't really apply

a metadata field in a package is not a legal issue
