### ISSUE TITLE
ubuntu 20.04 / python 3.9 doesn't have distutils / venv packages

### ISSUE THREAD

**Issue by huguesb** [deadsnakes/issues#150]
Attempting to install them default to the python3.8 version offered by the distro, which results in an unnecessary extra version of python being installed, and all kinds of headaches docker image builds that assume a single version of python is installed. I have tried a number of workarounds, including forced installs without deps and nothing works, forcing me to stick to 18.04

**Comment by asottile** [comment]
You need to install `python#.#-venv` to get the venv packages.  The `distutils` packages are provided by `python3-distutils` -- we can't ship our own `python#.#-distutils` on 20.04 because it would conflict with the upstream packaging

This is covered in the ppa description:

```
Packages
========

The packages provided here are loosely based on the debian upstream packages with some modifications to make them more usable as non-default pythons and on ubuntu. As such, the packages follow debian's patterns and often do not include a full python distribution with just `apt install python#.#`. Here is a list of packages that may be useful along with the default install:

- `python#.#-dev`: includes development headers for building C extensions
- `python#.#-venv`: provides the standard library `venv` module
- `python#.#-distutils`: provides the standard library `distutils` module
- `python#.#-lib2to3`: provides the `2to3-#.#` utility as well as the standard library `lib2to3` module
- `python#.#-gdbm`: provides the standard library `dbm.gnu` module
- `python#.#-tk`: provides the standard library `tkinter` module
```

**Comment by huguesb** [comment]
I'm sorry I really don't understand this answer.

If I install python3.9-venv, it brings python3.8-distutils, which brings python3.8, which is unacceptable
If I don't install python3.9-venv and manually install pip, pip crashes due to missing distutils, which is unacceptable

What sort of conflict would providing python3.9-distutils cause? Would it prevent installing 3.8 and 3.9 side by side?

**Comment by asottile** [comment]
So you're missing a bit here.  python3.9-venv depends on `python3-distuils` (there's no such package `python3.8-distuils`) -- python3-distutils includes source for 3.8 and 3.9 due to upstream ubuntu's strange packaging

If I were to publish a separate python3.9-distutils, it could not be installed on a system where python3-distutils is installed, which would make this PPA not usable in the general case

**Comment by huguesb** [comment]
This might be naive because I don't fully understand how apt dependency resolution works but, could you possibly provide a python3.9-distutils and make python3.9-venv depend on either python3-distutils or python3.9-distutils ?

**Comment by asottile** [comment]
no I can't, two packages cannot provide the same files

**Comment by huguesb** [comment]
After looking into it I am increasingly convinced that your previous statement is incorrect. The deb packages have provisions `Provides`, `Conflicts`, and `Replaces` fields that I'm pretty sure can be used for this purpose.

It seems like you could provide a `python3.9-distutils` that replaces the default `python3-distutils`. You could either make it so that it only provides files for 3.9, or you could mirror the 3.8 version to provide sources for both versions. Either approaches would unblock me, although the latter seems preferable as it would maintain compatibility with running 3.8 and 3.9 side by side.

**Comment by asottile** [comment]
I can't because then you can't install python3.8 which is the system python

**Comment by huguesb** [comment]
Just to clarify:

You don't want to offer a `python3.9-distutils` because `python3.8-distutils` on ubuntu 20.04 already provides these files (in addition to the ones for 3.8). To account for that bizarre upstream choice you have your other packages for 3.9 on 20.04 depend on `python3.8-distutils`

My proposal is to create a python3.9-distutils package that is *identical* to the upstream `python3.8-distutils` (with sources for both 3.8 and 3.9), except with dependencies on python3.9, and relevant `Provides` / `Conflicts` / `Replaces` fields for the 3.8 version.

That way 3.8 and 3.9 can still coexist and it becomes possible to install 3.9 without 3.8

Am I missing something?

**Comment by asottile** [comment]
yes, `sudo apt install python3.8 python3.8-distutils python3.9-distutils=your-broken-suggestion python3.9-distutils=your-broken-suggestion` **will not work because they conflict**

**Comment by oberluz** [comment]
The solution for me was to remove python3.8 after installing all of the python3.9 modules:

`
RUN apt-get remove -y python3.9-distutils python3.8
RUN apt autoremove -y
`

**Comment by metallerok** [comment]
Try this:
```
wget https://bootstrap.pypa.io/get-pip.py
```
```
python3.8 get-pip.py
```
```
python3.8 -m pip install --upgrade pip
```

**Comment by maciej-lech** [comment]
@asottile focal version of distutils doesn't have distutils files for python3.9 - https://packages.ubuntu.com/focal/all/python3-distutils/filelist

**Comment by asottile** [comment]
@maciej-lech that's an old version
