### ISSUE TITLE
Support Latest Ubuntu release as well as LTS's

### ISSUE THREAD

**Issue by cooperlees** [deadsnakes/issues#153]
### description

Can we enable aarch64 for Pi users and other aarch64 boxes?

I saw https://github.com/deadsnakes/issues/issues/64 and it said it was enabled, but my aarch64 Pis on Focal can't find the packages. Happy to do some work if I can help.

**Comment by asottile** [comment]
we're building all the ones we can except for `powerpc`, `armel`, and `riscv64` which afaik are all obsolete -- can you show your apt sources for that particular build and some output?

![image](https://user-images.githubusercontent.com/1810591/109692323-3c4f8d00-7b3d-11eb-88ee-af265e31ce5c.png)

your architecture can be shown via:

```bash
dpkg --print-architecture
```

**Comment by cooperlees** [comment]
O my bad, I am blind.

```
fatal: [bad_host]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://ppa.launchpad.net/deadsnakes/nightly/ubuntu groovy Release' does not have a Release file."}
```

It's me running groovy and not focal on some Pis. Is there possibility of always support latest Ubuntu too?

**Comment by asottile** [comment]
you can rebuild the packages for others, but I don't have the freetime (read: funding) to invest in directly supporting non-LTS releases since there are so many and they are usually relatively unstable

some of the packages "just work" on their adjacent releases -- iirc a lot of the focal packages will install and work on groovy -- but this is also unsupported

**Comment by cooperlees** [comment]
> you can rebuild the packages for others, but I don't have the freetime (read: funding) to invest in directly supporting non-LTS releases since there are so many and they are usually relatively unstable
> 
> some of the packages "just work" on their adjacent releases -- iirc a lot of the focal packages will install and work on groovy -- but this is also unsupported

Yup, totally understand. This is mainly why I said only the latest. Happy to donate time and money (if feasible) and setup the pipeline for latest Ubuntu.

I was going to just try adding the focal sources too, as yes, they should unless a linked library breaks an API etc.

Thanks for responding.

**Comment by asottile** [comment]
> 
> 
> > you can rebuild the packages for others, but I don't have the freetime (read: funding) to invest in directly supporting non-LTS releases since there are so many and they are usually relatively unstable
> > some of the packages "just work" on their adjacent releases -- iirc a lot of the focal packages will install and work on groovy -- but this is also unsupported
> 
> Yup, totally understand. This is mainly why I said only the latest. Happy to donate time and money (if feasible) and setup the pipeline for latest Ubuntu.
> 
> I was going to just try adding the focal sources too, as yes, they should unless a linked library breaks an API etc.
> 
> Thanks for responding.

yeah committing to `latest` would end up being "commit to all non-LTS" as once you publish as soon as you unpublish or stop publishing people get MAD
