### ISSUE TITLE
http://ppa.launchpad.net/deadsnakes/ppa/ubuntu groovy Release' does not have a Release file

### ISSUE THREAD

**Issue by steveross1975** [deadsnakes/issues#157]
### description
I have added the ppa repository to my repo list, but I get this error that prevents me from doing any update
### os information
Ubuntu 20.10 64bit
#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

#### uname -a

```
# paste the output of `uname -a` here
```
Linux raspi-master 5.8.0-1015-raspi #18-Ubuntu SMP PREEMPT Fri Feb 5 06:09:58 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by asottile** [comment]
please search "groovy" in the issue tracker
