### ISSUE TITLE
error installing python3.9-dev on  Linux Mint 20.1

### ISSUE THREAD

**Issue by tytuseczek** [deadsnakes/issues#160]
### description

Installing python3.9 was easy:
`sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update 
sudo apt install python3.9 `

however, after running 
`sudo apt install python3.9`
I get

`$ sudo apt install python3.9 python3.9-venv python3.9-dev
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
python3.9 is already the newest version (3.9.2-1+focal2).
Należy uruchomić "apt --fix-broken install", aby je naprawić.
Następujące pakiety mają niespełnione zależności:
 libpython3.9 : Wymaga: libpython3.9-stdlib (= 3.9.2-1+focal2) ale 3.9.0-5~20.04 ma zostać zainstalowany
 libpython3.9-dev : Wymaga: libpython3.9-stdlib (= 3.9.2-1+focal2) ale 3.9.0-5~20.04 ma zostać zainstalowany
 libpython3.9-stdlib : Wymaga: libpython3.9-minimal (= 3.9.0-5~20.04) ale 3.9.2-1+focal2 ma zostać zainstalowany
 python3.9 : Wymaga: libpython3.9-stdlib (= 3.9.2-1+focal2) ale 3.9.0-5~20.04 ma zostać zainstalowany
E: Niespełnione zależności. Proszę spróbować wykonać "apt --fix-broken install" bez pakietów (lub podać rozwiązanie).`

$ sudo apt install python3.9 python3.9-venv python3.9-dev
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności       
Odczyt informacji o stanie... Gotowe
python3.9 is already the newest version (3.9.2-1+focal2).
Należy uruchomić "apt --fix-broken install", aby je naprawić.
Następujące pakiety mają niespełnione zależności:
 libpython3.9 : Wymaga: libpython3.9-stdlib (= 3.9.2-1+focal2) ale 3.9.0-5~20.04 ma zostać zainstalowany
 libpython3.9-dev : Wymaga: libpython3.9-stdlib (= 3.9.2-1+focal2) ale 3.9.0-5~20.04 ma zostać zainstalowany
 libpython3.9-stdlib : Wymaga: libpython3.9-minimal (= 3.9.0-5~20.04) ale 3.9.2-1+focal2 ma zostać zainstalowany
 python3.9 : Wymaga: libpython3.9-stdlib (= 3.9.2-1+focal2) ale 3.9.0-5~20.04 ma zostać zainstalowany
E: Niespełnione zależności. Proszę spróbować wykonać "apt --fix-broken install" bez pakietów (lub podać rozwiązanie).

#### lsb_release -a

`No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa
`

#### uname -a
`Linux jerzy-Inspiron-3542 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by asottile** [comment]
try the command it suggests?

**Comment by tytuseczek** [comment]
`$ sudo apt --fix-broken install
apt
Usage: apt command [options]
       apt help command [options]

Commands:
  add-repository   - Add entries to apt sources.list
`

**Comment by asottile** [comment]
[on github use triple backticks to make code blocks](https://youtu.be/1UodxuXj5Ao?list=PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY)

**Comment by asottile** [comment]
try `sudo apt-get install --fix-broken` -- seems mint patches the `apt` command strangely ?

**Comment by tytuseczek** [comment]
```
apt install --fix-broken
```
fixed the packages, thanks
