### ISSUE TITLE
Python 3.9.3 is broken, as described in Python 3.9.4 Hotfix

### ISSUE THREAD

**Issue by Tom-Brouwer** [deadsnakes/issues#161]
### description

Python 3.9.3 has compatibility issues, as described in the [Python 3.9.4 Hotfix Release notes](https://www.python.org/downloads/release/python-394/). Concretely for me, this update caused the 'debugging' functionality in VScode to stop working, as described [here](https://github.com/microsoft/debugpy/issues/580).

Currently the only work-around for me was to remove Python3.9 and built Python 3.9.4 from source (Ubuntu 20.04).

Since 3.9.3 is clearly broken, as described in the hot-fix above, I suggest to stop distributing this, and either revert to 3.9.2 or update to 3.9.4.

**Comment by asottile** [comment]
from the main page:

> Disclaimer: there's no guarantee of timely updates 

A remind that this service is provided for free and you can [sponsor](https://github.com/sponsors/asottile) if you're deriving benefit from it

I'll get to these when I have freetime

**Comment by Tom-Brouwer** [comment]
No problem, thanks for the great work! Just wanted to give a heads-up since it was not yet under closed issues.
