### ISSUE TITLE
To create a release in deadsnakes for ubuntu 21.04 codename - hirstute hippo

### ISSUE THREAD

**Issue by ALENTL** [deadsnakes/issues#166]
### description
Err:10 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu hirsute Release          
  404  Not Found [IP: 91.189.95.85 80]
Get:11 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease [109 kB]  
Hit:12 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu hirsute Release' does not have a Release file.

### os information
Pop os 21.04 beta release 
#### lsb_release -a
Done

```
# paste the output of `lsb_release -a` here
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute

```

#### uname -a
Done
```
# paste the output of `uname -a` here
Linux pop-os 5.11.0-7614-generic #15~1618626693~21.04~ecb25cd-Ubuntu SMP Thu Apr 22 15:59:53 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
as the ppa description says, we only provide packages for LTS releases -- it's already a lot of work that I do here for free and receive basically no compensation for it -- adding non-LTS releases would be way more work for not too much benefit

**Comment by pablodz** [comment]
> as the ppa description says, we only provide packages for LTS releases -- it's already a lot of work that I do here for free and receive basically no compensation for it -- adding non-LTS releases would be way more work for not too much benefit

Thanks for all @asottile , your work is really appreciate
