### ISSUE TITLE
Support for Ubuntu 20.10 Groovy

### ISSUE THREAD

**Issue by morfien101** [deadsnakes/issues#169]
### description

Is there any plan to allow Ubuntu 20.10 for the PPA?

I tried to lie to the OS and use Focal but it seems the packages are marked with the name of the release.

**Comment by asottile** [comment]
dupes: https://github.com/deadsnakes/issues/issues?q=is%3Aissue+is%3Aclosed+groovy

as the ppa description says, we only provide packages for LTS releases -- it's already a lot of work that I do here for free and receive basically no compensation for it -- adding non-LTS releases would be way more work for not too much benefit

if you or your company would like to pay for this work, please reach out to me directly (you can find my email in my commits)
