### ISSUE TITLE
404  Not Found: http://ppa.launchpad.net/deadsnakes/ppa/ubuntu hirsute Release   

### ISSUE THREAD

**Issue by GMSL1706** [deadsnakes/issues#173]
### description
Hi, I am new in Ubuntu and I wanted to install the last version of Python3. I accidentally download the ppa deadsnakes and I do not know how to remove that because [I read](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) that it is not available for my version (I can make a mistake). When I use command  `sudo apt-get update`, I have this error:
```
Err:7 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu hirsute Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```

#### uname -a

```
Linux OR19728 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Can someone help me please ?

**Comment by asottile** [comment]
the issue template answers this question

**Comment by asottile** [comment]
you can remove the ppa from `/etc/apt/sources.list.d`

**Comment by GMSL1706** [comment]
Thank you very much
