### ISSUE TITLE
deadsnakes should have a multi-python container image

### ISSUE THREAD

**Issue by bristea** [deadsnakes/issues#174]
### description

There are some particular use-cases where there is a need to have all supported versions of python installed on the same host, for example when running commands that performing packaging tasks and validating constraints.

It becomes harder and harder to run full ranges like 3.6-3.9 on newer platforms (Ubuntu 20.10 does not have deadnakes).

If we would have a single container published with *all* currently supported pythons it would make it very easy for any developer to use it for running these jobs that require cross-python testing. The need for this is not really new and https://hub.docker.com/r/fkrull/multi-python is a good example of doing exactly that. Still, this is not published from deadsnakes and it would be much more convenient to avoid depending on a single person for that. Using the established deadsnakes would likely also motivate others to help with maintenance.

**Comment by asottile** [comment]
I don't think you would actually want _all_ of the pythons we provide, that'd be a many-GB image

it's not difficult to install the versions you need yourself so I don't think this would provide value, only more maintenance for something very few would use
