### ISSUE TITLE
pip not installed?

### ISSUE THREAD

**Issue by leonhma** [deadsnakes/issues#175]
### description

vsc complains that pip is not installed and i can't seem to find a way to access it. have you guys got any suggestions or is that some bug?

### os information

zorin 15 (based on ubuntu)

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Zorin
Description:	Zorin OS 15.3
Release:	15
Codename:	bionic

```

#### uname -a

```
Linux leonhards-desktop 5.4.0-77-generic #86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
correct, we can't provide pip without conflicting with the debian packages -- here's ways you can acquire pip: https://youtu.be/2Hg5-Hrsa6w

**Comment by johnthagen** [comment]
@asottile If possible, I would suggest trying to put information about how to install `pip` in the docs somewhere: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

It took me a while as a new user to realize why `python3.X-pip` wasn't working, and leading me to this issue + YouTube link.
