### ISSUE TITLE
Unable to add PPA for Python 3.7 / Ubuntu 18.04 / arm64

### ISSUE THREAD

**Issue by jobi** [deadsnakes/issues#179]
### description

We had been using the PPA as a way to install the latest Python 3.7 on our Ubuntu Bionic Docker images for our application. Recently with some of our developers switching to M1 Macs, we've looked at building multi-arch versions of these Docker images.

We're running into an issue where Ubuntu will fail to add the PPA when running on `arm64`:

```
root@95ea002ef625:/# add-apt-repository ppa:deadsnakes/ppa
Cannot add PPA: 'ppa:~deadsnakes/ubuntu/ppa'.
ERROR: '~deadsnakes' user or team does not exist.
```

Looking at the pool of packages, it does seem like `arm64` packages for that combination do exist.

#### lsb_release -a

```
root@95ea002ef625:/#  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

#### uname -a

```
root@95ea002ef625:/# uname -a
Linux 95ea002ef625 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by asottile** [comment]
that particular error message happens long before it gets to the ppa part -- it's failing on some network lookup to launchpad (perhaps an internal proxy or similar is blocking it?)

the packages are present and I've verified they work so this is something on your end
