### ISSUE TITLE
description shown after adding ppa is not up to date

### ISSUE THREAD

**Issue by jugmac00** [deadsnakes/issues#180]
### description

I added the ppa on a new Ubuntu 20.04 installation via

```
sudo add-apt-repository ppa:deadsnakes/ppa
```

and got the following information:

>Supported Ubuntu and Python Versions
>====================================
>- Ubuntu 16.04 (xenial) Python 2.3 - Python 2.6, Python 3.1 - Python3.4, Python 3.6 - Python3.9
>- Ubuntu 18.04 (bionic) Python2.3 - Python 2.6, Python 3.1 - Python 3.5, Python3.7 - Python3.9
>- Ubuntu 20.04 (focal) Python3.5 - Python3.7, Python3.9
>- Note: Python2.7 (all), Python 3.5 (xenial), Python 3.6 (bionic), Python 3.8 (focal) are not provided by deadsnakes as upstream ubuntu provides those packages.
>- Note: for focal, older python versions require libssl1.0.x so they are not currently built

Python 3.10 is not yet listed, but already available.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS (fossa-bulbasaur X55.1)
Release:        20.04
Codename:       focal
```

#### uname -a

```
Linux XPS-13-9310 5.10.0-1049-oem #51-Ubuntu SMP Mon Sep 27 11:01:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Looks like the description is the same as on https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa - coincidence or not :-)

**Comment by asottile** [comment]
updated -- thanks!

also removed xenial
