### ISSUE TITLE
compatibility with ubuntu 21.10

### ISSUE THREAD

**Issue by matiasAS** [deadsnakes/issues#181]
### description

hi, how can i add the repository to ubuntu 21.10 ?. regards
Matias

#### lsb_release -a

```
Ubuntu 21.10
Codename impish
```

#### uname -a

```
Linux ubuntu 5.13.0-19-generic #19-Ubuntu SMP Thu Oct 7 21:58:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by matiasAS** [comment]
I am clear that it must be an lts version and this one is not, I have only opened this issue in case someone can help me install through a python3.7 ppa repository in ubuntu 21.10

**Comment by asottile** [comment]
hi, please read the first chunk in the issue template -- thanks
