### ISSUE TITLE
Python 3.11.0a2

### ISSUE THREAD

**Issue by jwilk** [deadsnakes/issues#183]
[Python 3.11.0a2](https://www.python.org/downloads/release/python-3110a2/) was released last week.
Could you update the `python3.11` package?

**Comment by asottile** [comment]
yep I'll get to it when I'm not on vacation

you can always use the nightly packages as well

**Comment by jwilk** [comment]
> you can always use the nightly packages

Not really: I need it for arm64, whereas the nightly packages are amd64-only.

**Comment by asottile** [comment]
well then you'll just have to wait -- consider sponsoring
