### ISSUE TITLE
No python3.8-distutils for bionic/focal?

### ISSUE THREAD

**Issue by carlosgalvezp** [deadsnakes/issues#185]
Hi!

I notice there's only python3.8-distutils for xenial, and with a different version (3.8.9) than Python (3.8.12). Why is that? All other Python versions have the correct packages. Would it be possible to build it with a matching version, also for bionic and focal?

http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/pool/main/p/python3.8/

Thanks!

**Comment by asottile** [comment]
on those it's python3-distutils

**Comment by asottile** [comment]
we can't provide packages which conflict with the upstream packages or neither are installable
