### ISSUE TITLE
[GHA] Allow skipping a venv setup

### ISSUE THREAD

**Issue by webknjaz** [deadsnakes/issues#187]
I'm working on a tox GHA that calls this one or the official "setup-python" conditionally and then install tox with pip and `--user`.
I noticed that when the deadsnakes action is invoked, any command with `--user` starts failing. It is pretty obvious that it's because of the unconditional venv creation/activation.
I don't want to debate whether using `--user` is even a good idea (I know about its shortcomings) but I think that the most problematic part is that this action has a different UX from the GitHub's one and it is unexpected/undocumented. Especially, for newbies (personally, I can find a million ways to work around this limitation).

What can we do about it? I see only two obvious solutions:
1) add an input to allow the end-users to opt-in (or out?) to have the venv setup
2) not care and declare it as `wontfix` (but in this case, it'd probably still be useful to add a note in the readme or so)

P.S. Composite Actions now support invoking other actions directly. I seem to recall that you wanted to make deadsnakes call the official one under the hood. If it's still desired, it's finally possible.

**Comment by asottile** [comment]
without the venv creation and activation the action doesn't provide any value (and in many cases doesn't work at all (!)) so this won't be implemented

as for the P.S. I abandoned that idea, even with composite actions it is not a simple task https://github.com/deadsnakes/issues/issues/123#issuecomment-881069547

**Comment by webknjaz** [comment]
> as for the P.S. I abandoned that idea, even with composite actions it is not a simple task [#123 (comment)](https://github.com/deadsnakes/issues/issues/123#issuecomment-881069547)

FYI Composite Actions started supporting the `if:` syntax a few months ago if you're referring to the problem of formerly limited syntax. I can send a demo PR unless there's another reason you dropped the idea (it's not obvious from the comments in the PR as they refer to JS and not Composite Actions as they are implemented today).

**Comment by webknjaz** [comment]
> without the venv creation and activation the action doesn't provide any value (and in many cases doesn't work at all (!)) so this won't be implemented

Sounds like you're referring to the `$PATH` injection you have there. I'd argue that it's still possible to make it useful without a virtualenv but with a similar approach (with just a normal non-venv "bin" directory and shim symlinks there).

**Comment by asottile** [comment]
nah I'm referring to pip being unusable
