### ISSUE TITLE
No more support for Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by freethejazz** [deadsnakes/issues#195]
Adding this issue to _hopefully_ reduce the number of issues that may come in about the recent change that **the deadsnakes ppa is no longer supporting Ubuntu 16.04 Xenial for any python version**. I believe this is as of approximately January 15th, 2022. This means your mileage may vary when trying to install python from the deadsnakes ppa on Ubuntu 16.04, but 3.7 (#194) and 3.6 (below) appear not to work.

## Steps to reproduce
1. Attempt to install any python version from Ubuntu 16.04 Xenial (and cross your fingers)

You may see errors like the ones I got trying to install `python3.6-dev` (same errors with `python3.6`):
```
#6 40.01 E: Unable to locate package python3.6-dev
#6 40.01 E: Couldn't find any package by glob 'python3.6-dev'
#6 40.01 E: Couldn't find any package by regex 'python3.6-dev'
```

## Fix
1. If you can, upgrade to a newer version of Ubuntu. Standard support for 16.04 from Canonical ended in April 2021.
2. If not, reach out to @asottile to set up a support plan.
3. Either way, consider sponsoring @asottile.

Thanks for all your work supporting some of our core application infrastructure, @asottile!

**Comment by mkadin** [comment]
Thanks for creating this issue -- we are in this boat and our CI has stalled.  We are using 3.9, so I can confirm that version is also not working anymore.  Our bad for waiting on a Xenial upgrade, certainly.

@asottile -- i sent you a DM on twitter, but let me know what the best way is to get in touch.  Happy to work on a short term financial arrangement to get us (+ any other folks in the same boat) unblocked while we work on the larger issue of upgrading.

**Comment by ivopetiz** [comment]
Is there any chance of having the old Python packages in some kind of historical repository?
It would be a great help.

**Comment by asottile** [comment]
hi @freethejazz -- thanks for the issue and appreciate the sponsorship

the end-of-lifed packages have indeed been removed -- launchpad doesn't let us update or upload them after the distribution reaches EOL and we ran out of allotted space for the ppa

please reach out to me privately using my email address in my git commits (the edu address) with the following information so I provide a payment plan / estimate:
- approximately how many machines will be running `apt update` / `apt install`
- what python versions and ubuntu distribution you would need available
- do you need the latest security patches applied

**Comment by mmomtchev** [comment]
An old ppa still carries them:
`add-apt-repository ppa:jblgf0/python`

**Comment by asottile** [comment]
that ppa has a snapshot from 2019 without security patches, I would not recommend using it

**Comment by mmomtchev** [comment]
Me (and many others on this issue) do not care about security - we need it to run a Github Actions build chain with `node-gyp` which requires `python3.6` - in my case it is the only way to support Amazon Linux which hasn't been updated in ages

This allows me to release my package

**Comment by asottile** [comment]
to each their own, but I suspect your downstream users would not be too happy to hear that you do not care about security
