### ISSUE TITLE
E: Couldn't find any package by glob

### ISSUE THREAD

**Issue by YoniSneOr** [deadsnakes/issues#197]
### description
Trying to install python3.7/3.8
as follow
 sudo add-apt-repository -y 'ppa:deadsnakes/ppa'
 apt-get update
   apt-get -y install  python3.8  python3.8-dev python3.8-distutils python3-pip
   and I am getting the following errors:
   
   E: Unable to locate package python3.8
E: Couldn't find any package by glob 'python3.8'
E: Couldn't find any package by regex 'python3.8'
E: Unable to locate package python3.8-dev
E: Couldn't find any package by glob 'python3.8-dev'
E: Couldn't find any package by regex 'python3.8-dev'
E: Unable to locate package python3.8-distutils
E: Couldn't find any package by glob 'python3.8-distutils'
E: Couldn't find any package by regex 'python3.8-distutils'

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial

#### uname -a

```
# paste the output of `uname -a` here
```
Linux bbd517a7c53f 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by asottile** [comment]
please see the pinned issue: #195
