### ISSUE TITLE
Unable to create a virtual environment with Python 3.10

### ISSUE THREAD

**Issue by Patol75** [deadsnakes/issues#198]
### Description

I am encountering an issue while executing `python3.10 -m build` in a module folder. The terminal shows:
```
* Creating venv isolated environment...

Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.10/site-packages/build/__main__.py", line 372, in main
    built = build_call(
  File "/home/thomas/.local/lib/python3.10/site-packages/build/__main__.py", line 229, in build_package_via_sdist
    sdist = _build(isolation, builder, outdir, 'sdist', config_settings, skip_dependency_check)
  File "/home/thomas/.local/lib/python3.10/site-packages/build/__main__.py", line 140, in _build
    return _build_in_isolated_env(builder, outdir, distribution, config_settings)
  File "/home/thomas/.local/lib/python3.10/site-packages/build/__main__.py", line 104, in _build_in_isolated_env
    with _IsolatedEnvBuilder() as env:
  File "/home/thomas/.local/lib/python3.10/site-packages/build/env.py", line 104, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/home/thomas/.local/lib/python3.10/site-packages/build/env.py", line 258, in _create_isolated_env_venv
    executable, script_dir, purelib = _find_executable_and_scripts(path)
  File "/home/thomas/.local/lib/python3.10/site-packages/build/env.py", line 303, in _find_executable_and_scripts
    raise RuntimeError(f'Virtual environment creation failed, executable {executable} missing')
RuntimeError: Virtual environment creation failed, executable /tmp/build-env-lcuno53i/local/bin/python missing

ERROR Virtual environment creation failed, executable /tmp/build-env-lcuno53i/local/bin/python missing
```
The issue does not arise with Python 3.9. Both Python distributions have been installed through deadsnakes.

A developer from pypa [recommended](https://github.com/pypa/build/issues/215#issuecomment-1016312379) I open an issue here.

#### lsb_release -a

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

#### uname -a

```
Linux thomas-GL502VM 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
the venv module works fine so it's something nonstandard they're doing:

```console
$ python3.10 -m venv venv
$ ls venv/
bin  include  lib  lib64  pyvenv.cfg
$ ls venv/bin/python
venv/bin/python
```

**Comment by Patol75** [comment]
@asottile Thank you for your input on this issue. The conversation has progressed further with the `build` developer. Would you mind checking his/her latest replies and let me/us know if they change anything to the way the issue is being approached? Thank you for your time.

**Comment by asottile** [comment]
oddly I can't see anything but your messages there but presumably build can do whatever venv or virtualenv did to handle this (since I believe they encounter the same problems)

**Comment by Patol75** [comment]
I am pasting below the last four replies from the `build` developer.

> Yes, venvs are created "correctly". The issue is that we cannot extract the venv paths if a different scheme is used for the venv because we operate on the assumption that the system default and the venv schemes are the same. That is how venvs have historically worked and it's how they are supposed to work. If Debian or deadnakes or Fedora or whoever wish to deviate from the spec, they need to put in the effort to make sure their changes are compatible with the wider ecosystem.

> Can you actually pip install anything in this venv with the latest version of pip? If you can, i.e. if pip falls back on distutils, then it should also emit a warning.

> I assume pip calls get_preferred_scheme in 3.10; deadsnakes is varying the prefix depending on whether it's being called from inside a venv, meaning that it might or might not work for build depending on whether build itself was installed inside a venv. get_preferred_scheme wasn't introduced so people could fudge the paths at runtime.

> We create venvs programmatically. We do not know where the venv Python is located, or where any of the other paths are located inside the venv, which is why we are calling sysconfig.get_paths in the first place. So no, whatever works for virtualenv and venv (or even pip) won't work for us. We could hardcode the Python path as venv-dir/Scripts/python on Windows and venv-dir/bin/python everywhere else, attempt to call get_paths in a subprocess and hope for the best. Personally, I'd rather Debian roll back their patches and work with the core Python team to find a workable solution.

**Comment by henryiii** [comment]
I believe you have blocked `@layday`, that has been mentioned before. Maybe that's why you can only see half the convo? Maybe you could try loading the page in private browsing.

From what I quickly gather Debian is using their newfound power in 3.10 with `get_preferred_scheme` to vary the location at runtime which makes it impossible for tools like build to compute the correct paths inside the venv (without hard coding, at least), and goes against the [spec](https://www.python.org/dev/peps/pep-0405/#sysconfig-install-schemes-and-user-site). Looks like an issue with upstream Debian rather than deadsnakes, though. https://github.com/deadsnakes/python3.10/blob/ubuntu/focal/debian/patches/deb-locations.diff

(I could be misreading this, though, I'm not currently actively involved in solving it)

Final message quote:

> We create venvs programmatically. We do not know where the venv Python is located, or where any of the other paths are located inside the venv, which is why we are calling `sysconfig.get_paths` in the first place. So no, whatever works for virtualenv and venv (or even pip) won't work for us. We could hardcode the Python path as venv-dir/Scripts/python on Windows and venv-dir/bin/python everywhere else, attempt to call get_paths in a subprocess and hope for the best. Personally, I'd rather Debian roll back their patches and work with the core Python team to find a workable solution.

**Comment by asottile** [comment]
hmm, I mean `venv` and `virtualenv` have the same problems and seem to work -- perhaps `build` could adopt whatever `virtualenv` is doing?  presumably this: https://github.com/pypa/virtualenv/blob/bb82a73b6dbf577874f6d4bfaf72d2a7f59dfffe/src/virtualenv/discovery/py_info.py#L76-L86

**Comment by Patol75** [comment]
Latest update from the `build` side:

> I mentioned that as a possibility earlier. I do think it's the wrong way to approach altering the venv scheme. If a different scheme is sought for venvs, a new entry should be added to the preferred scheme dict, for venvs. get_preferred_scheme is supposed to be the single source of truth for schemes by install type. And because it bears repeating: they should absolutely not be varying the schemes depending on the active prefix. I'm lukewarm to the idea of relying on an extension to the venv spec that has scarcely being discussed and has not been merged into CPython. But if it's gonna get us out of this bind, I suppose we could look for venv in the scheme names, like we do with the framework prefix for Apple's Python. Or we could recommend that people use virtualenv, like Bernat has suggested.

**Comment by nschloe** [comment]
I just bumped into the same thing on Ubuntu 22.04. Is there a Debian bug open for this yet?

**Comment by asottile** [comment]
i don't maintain the debian side, you'll have to open an issue there
