### ISSUE TITLE
Support Ubuntu 22.04 (Jammy)

### ISSUE THREAD

**Issue by candrews** [deadsnakes/issues#199]
### description

The release of Ubuntu 22.04 (Jammy) is approaching and it would be great if this PPA supported it when it's released or perhaps even beforehand :smile: 

### os information

Ubuntu 22.04 (Jammy Jellyfish)

#### lsb_release -a

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy
```

#### uname -a

```
Linux dd70daca0deb 5.16.8-200.fc35.x86_64 #1 SMP PREEMPT Tue Feb 8 20:58:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
it will of course once jammy is finalized -- there's still some big updates that will happen before that and I don't want to waste effort when I'd need to do a full rebuild (for instance there's a libc and python upgrade scheduled still before freeze)
