### ISSUE TITLE
PPA: Add version for 22.04

### ISSUE THREAD

**Issue by nschloe** [deadsnakes/issues#206]
The PPAs seem to support released Ubuntu LTS versions only. Because of Debian's/Ubuntu's failfest with Python 3.10 (see, e.g., [here](https://github.com/pre-commit/pre-commit/issues/2299#issuecomment-1074697903), I'd like to suggest to already add jammy (22.04) to the PPAs now.

**Comment by asottile** [comment]
I'll be doing this once jammy is released -- I've already started a bit of prepwork to flip the switch but want to make sure it's at least at release candidacy state first
