### ISSUE TITLE
Linux Mint: 20 LTS - dependency problems in today's update

### ISSUE THREAD

**Issue by ngmisl** [deadsnakes/issues#208]
python3.10 : Depends: libpython3.10-stdlib (= 3.10.4-1+focal2) but 3.10.4-1+focal1 is installed
 python3.10-minimal : Depends: libpython3.10-minimal (= 3.10.4-1+focal2) but 3.10.4-1+focal1 is installed

**Comment by jugmac00** [comment]
Afaik Linux Mint is not supported, and there was already a similar issue reported:
https://github.com/deadsnakes/issues/issues/207

P.S.: It is always a good idea to search the issue tracker before opening a new issue.

**Comment by ngmisl** [comment]
Weird because I use this ppa for a week without any problems

**Comment by ngmisl** [comment]
https://github.com/deadsnakes/issues/issues/207#issuecomment-1098684655

fixed it, thanks for the hint @jugmac00
