### ISSUE TITLE
Latest update got file conflict between libpython3.10-stdlib_3.10.4-1+bionic2_amd64.deb and libpython3.10-minimal_3.10.4-1+bionic2_amd64.deb

### ISSUE THREAD

**Issue by helioloureiro** [deadsnakes/issues#209]
### description

After a `apt update && apt dist-upgrade` python-3.10 related packages displayed unsolvable conflict.

root@dell ~# apt -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  fonts-mathjax libjs-mathjax
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libpython3.10-minimal libpython3.10-stdlib
The following packages will be upgraded:
  libpython3.10-minimal libpython3.10-stdlib
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 0 B/2,582 kB of archives.
After this operation, 72.7 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 612396 files and directories currently installed.)
Preparing to unpack .../libpython3.10-stdlib_3.10.4-1+bionic2_amd64.deb ...
Unpacking libpython3.10-stdlib:amd64 (3.10.4-1+bionic2) over (3.10.4-1+bionic1) ...
dpkg: error processing archive /var/cache/apt/archives/libpython3.10-stdlib_3.10.4-1+bionic2_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/python3.10/_sysconfigdata__linux_x86_64-linux-gnu.py', which is also in package libpython3.10-minimal:amd64 3.10.4-1+bionic1
Preparing to unpack .../libpython3.10-minimal_3.10.4-1+bionic2_amd64.deb ...
Unpacking libpython3.10-minimal:amd64 (3.10.4-1+bionic2) over (3.10.4-1+bionic1) ...
dpkg: error processing archive /var/cache/apt/archives/libpython3.10-minimal_3.10.4-1+bionic2_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/python3.10/typing.py', which is also in package libpython3.10-stdlib:amd64 3.10.4-1+bionic1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libpython3.10-stdlib_3.10.4-1+bionic2_amd64.deb
 /var/cache/apt/archives/libpython3.10-minimal_3.10.4-1+bionic2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

### os information
Ubuntu 18.04 running python 3.10 from repo:

deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic main

#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
****
```

#### uname -a

```
Linux dell 5.17.2-helio #34 SMP PREEMPT Mon Apr 11 17:49:09 CEST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bennuttall** [comment]
Same here on focal:

```
dpkg: error processing archive /var/cache/apt/archives/libpython3.10-stdlib_3.10.4-1+focal2_amd64.deb
 (--unpack):
 trying to overwrite '/usr/lib/python3.10/_sysconfigdata__linux_x86_64-linux-gnu.py', which is also i
n package libpython3.10-minimal:amd64 3.10.4-1+focal1
Preparing to unpack .../libpython3.10-minimal_3.10.4-1+focal2_amd64.deb ...
Unpacking libpython3.10-minimal:amd64 (3.10.4-1+focal2) over (3.10.4-1+focal1) ...
dpkg: error processing archive /var/cache/apt/archives/libpython3.10-minimal_3.10.4-1+focal2_amd64.de
b (--unpack):
 trying to overwrite '/usr/lib/python3.10/typing.py', which is also in package libpython3.10-stdlib:a
md64 3.10.4-1+focal1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libpython3.10-stdlib_3.10.4-1+focal2_amd64.deb
 /var/cache/apt/archives/libpython3.10-minimal_3.10.4-1+focal2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by jugmac00** [comment]
duplicate - see #207
