### ISSUE TITLE
Python 3.7 missing for Jammy 22.04

### ISSUE THREAD

**Issue by candrews** [deadsnakes/issues#213]
### description

There is no python 3.7 package for Ubuntu 22.04 (Jammy): https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa?field.series_filter=jammy

### os information

Ubuntu 22.04 (Jammy)

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

#### uname -a

```
Linux 6a5eb4fac40d 5.17.3-300.fc36.x86_64 #1 SMP PREEMPT Wed Apr 13 23:08:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
yeah it will be there eventually, had a death in the family so I've been unable to attend to this

**Comment by candrews** [comment]
> had a death in the family

I offer my condolences - I'm very sorry for your loss.



> yeah it will be there eventually

Could you please keep this issue open until then? That way, I and others can know this issue exists and we can subscribe to find out when it's closed, rather than having to manually check the ppa all the time.

Thank you for all that you do!
