### ISSUE TITLE
Trademark violation of the deadsnakes logo

### ISSUE THREAD

**Issue by iqbalabd** [deadsnakes/issues#220]
The Python "2-snakes" logo is a registered trademark of the Python Software Foundation.

As communicated also via Twitter to @asottile the current deadsnakes logo violates the trademark policy for using the Python logo as written [here](https://www.python.org/psf/trademarks/) and [here](https://www.python.org/psf/trademarks-faq/)

Please remove the logo as soon as possible, and use a variation of the logo which has explicitly approved. You can request for permission by emailing the PSF Trademark WG at psf-trademarks@python.org.

**Comment by asottile** [comment]
apologies had muted the twitter thread long before that!  thanks for the heads up

I believe the use falls under acceptable use given the policy listed [here](https://www.python.org/psf/trademarks/) -- notably that the use is non-commercial (deadsnakes provides a ppa containing python packages for ubuntu)

> Use of derived logos for freely distributed 3rd-party modules or tools -- Allowed if for the Python programming language. Use of derived logos for commercial modules and tools requires permission from the PSF.

> Contacting us is not a requirement for the specific non-commercial uses listed above

**Comment by iqbalabd** [comment]
The purpose of the use of the logo can be considered as nominative and fine, but the way the logo is presented violates the guidelines as it doesn't preserve the shape of the logo. 
Please refer to "Q: What does it mean to "leave the shape unaltered"? [here](https://www.python.org/psf/trademarks-faq/)
Just to be clear, nominative use cases still does not permit unauthorized changes in the shape of the logo.

It's best to send a draft of a proposed logo before use to the Trademark WG to get an explicit permission before use.

**Comment by asottile** [comment]
the shape and outline is retained according to those guidelines -- unless I'm missing something

**Comment by iqbalabd** [comment]
No, the shape and outline is not retained in your current usage of the logo. 

- The eyes of the snakes is x (it should be round)
- The tongue jutting out breaks the outline
- The cracks in the bodies of the snake breaks the outline.

**Comment by asottile** [comment]
if flood filled according to the guidelines they're retained -- and adjacent visuals are permitted as demonstrated by the examples

**Comment by DavidMertz** [comment]
Just to be completely clear. This is not remotely a close call.. it is a clear and unambiguous violation of a protected PSF Trademarks. We've dealt with hundreds of examples that have a plausible argument, and worked with the creators to arrive at a suitable form.

I wrote the trademarks FAQ, in the main, and large portions of the trademarks policy. FWIW, while not a lawyer, I did do a Harvard Law class in Intellectual Property (through the wonderful edX). I've co-chair Ed the trademarks committee for about 15 years.q

We'll give you a couple days to take this down. After that, we'll send a takedown notice to GiHub. I don't know if they'll only take down this one repository or close your account altogether. But it won't be good for you.

To arrive at a suitable derived logo, please correspond with the PSF Trademarks Working Group at the address Iqbal gives. But remove all published versions of the violation FIRST.

**Comment by asottile** [comment]
as a psf voting member myself I'll comment that this is a really bad look for the python community -- **threatening** a non commercial free open source project which is used by millions of python users over a fair use
