### ISSUE TITLE
Creating virtual environments on ubuntu:18.04 using python3.10 fails

### ISSUE THREAD

**Issue by adfernandes** [deadsnakes/issues#221]
Creating virtual environments on `ubuntu:18.04` using `python3.10` from `deadsnakes' fails

Trying to use `python3.10-venv`, using `virtualenv -p python3.10 venv` gives exactly the error [detailed here](https://github.com/pypa/pip/issues/10253).

The **fix** is [given here](https://github.com/pypa/pip/pull/10252), and for some reason this patch appears not to be in the `deadsnakes` repo (currently `python-3.10.5`).

As an intermediate workaround, the user can issue
```
python3.10 -m ensurepip --upgrade
```
but this does _not_ work when creating virtual environments.

Here is a `Dockerfile` to reproduce:
```docker
FROM ubuntu:18.04

WORKDIR /root

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update -y \
    && apt-get dist-upgrade -y \
    && apt-get install -y \
    apt-utils \
    build-essential \
    curl \
    gnupg2 \
    software-properties-common \
    && apt-get clean -yq

RUN add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update -y \
    && apt-get install -y \
    python3.10 \
    python3.10-dev \
    python3.10-venv \
    virtualenv \
    && apt-get clean -yq

RUN virtualenv -p python3.10 venv
```

**Comment by asottile** [comment]
you're using `virtualenv` from 18.04 which is version 15.1 which was released in 2016 -- 5 full years before python 3.10 was relased

if you use `python3.10 -m venv venv` it'll work fine or if you use a modern version of `virtualenv` (>=20.10) it will also work fine -- for example [using the zipapp](https://virtualenv.pypa.io/en/latest/installation.html#via-zipapp)

**Comment by adfernandes** [comment]
_Ah-ha._ That makes sense, **thanks**.

It wasn't obvious to me that the `virtualenv` command was more than just syntactic sugar for `python3.10 -m venv venv`, especially since it seems to work with the system pythons `2.7` and `3.6` that way.

Very confusing!

**Comment by asottile** [comment]
[virtualenv vs. venv](https://youtu.be/MGTX5qI2Jts)

**Comment by adfernandes** [comment]
For anyone else who finds this thread, here's a great explanation of the _super confusing_ state of Python virtual environments: [What is the difference between venv, pyvenv, pyenv, virtualenv, virtualenvwrapper, pipenv, etc?](https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe)

**Unless** you know what you're doing, the [default answer](https://stackoverflow.com/a/47559925) should be `python3 -m venv "${directory}"`
