### ISSUE TITLE
python3.11 ubuntu jammy missing ensurepip or pip

### ISSUE THREAD

**Issue by ssbarnea** [deadsnakes/issues#223]
### description

I discovered that I do not have neither pip or ensure pip on the py311 version coming from deadsnakes repo, so I am not really sure how we can make use of it.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

#### uname -a

```
Linux u1 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:57:22 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux```

Any hints on how to make it work would be really appreciated, especially as debian/ubuntu does not seem to be very keen on including the entire stdlib, [ensurepip](https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1955729) in particular.

As a side note, I was able to use python3.11 from Fedora 36 main repositories without any problems, it did include ensurepip and pip. Sadly, for GHA, we need to use Ubuntu.

And thanks for maintaining deadsnakes!

**Comment by asottile** [comment]
ensurepip is available if you pull in the `-venv` package and pip is available through `python3-pip`

 that said, using global pip is a bad idea -- make a virtualenv

in the future please search the issue tracker, there's 10s of duplicates for either "pip" or "ensurepip"

**Comment by asottile** [comment]
that is in the docs, but it appears you didn't read them
