### ISSUE TITLE
No valid OpenPGP data found

### ISSUE THREAD

**Issue by KarsonTheFoxx** [deadsnakes/issues#224]
### description
i cannot add the ppa as it fails to find a valid GPG key and OpenPGP data

### os information
Linux bullseye 11

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

#### uname -a

Linux penguin 5.10.114-16024-gbdf1547bd4f4 #1 SMP PREEMPT Thu Jun 30 18:19:44 PDT 2022 x86_64 GNU/Linux

**Comment by asottile** [comment]
read the issue template please
