### ISSUE TITLE
Postinstall scripts make reproducible bytecode difficult 

### ISSUE THREAD

**Issue by josnyder-rh** [deadsnakes/issues#225]
This issue is largely copied from an [Ubuntu issue](https://bugs.launchpad.net/ubuntu/+source/python3.8/+bug/1983124) I filed:

> The python interpreter writes reproducible bytecode when two environment variables (SOURCE_DATE_EPOCH and PYTHONHASHSEED) are set. Without PYHONHASHSEED set, various internal data structures get serialized to a .pyc file in arbitrary order. With PYTHONHASHSEED, that order is deterministic.
>
> The postinstall script in the python3.8-minimal package builds bytecode with `python3.8 -E -S -O /usr/lib/python3.8/py_compile.py`. The -E option in particular causes PYTHONHASHSEED to be ignored. Users who want to reproducibly install Python into a container image must either delete or rewrite the bytecode after the installation concludes.
>
> Observed behavior: when the installer process runs with these two environment variables, bytecode differs between installations.
>
> Expected behavior: the same bytecode under every installation

The bug report has not received much attention from the Ubuntu project. I don't know this project's policy on adding patches not already present in the Ubuntu upstream, but if such a thing is possible, it would be much appreciated!

**Comment by asottile** [comment]
yeah we tend not to differ from upstream unless it's really really broken -- this sounds like we'd be carrying the patch a while. you're probably better to report to debian than ubuntu as that's the source of everything

**Comment by josnyder-rh** [comment]
Thanks for the pointer! In case anyone else is interested in following along, I filed [a bug upstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=101756).
