### ISSUE TITLE
Python 3.11.0~rc1-1+jammy1 conflicts with python3-distutils_3.10.6-1~22.04_all

### ISSUE THREAD

**Issue by mosquito** [deadsnakes/issues#226]
### Python `3.11.0~rc1-1+jammy1` conflicts with `python3-distutils_3.10.6-1~22.04_all`

```
dpkg: error processing archive /tmp/apt-dpkg-install-oRr1iS/25-python3-distutils_3.10.6-1~22.04_all.deb (--unpack):
[1706](https://github.com/snakepacker/python/runs/8051269172?check_suite_focus=true#step:7:1708)
#25 32.39  trying to overwrite '/usr/lib/python3.11/distutils/README', which is also in package python3.11-distutils 3.11.0~rc1-1+jammy1
```

Extra logs can be found [here](https://github.com/snakepacker/python/runs/8051269172?check_suite_focus=true#step:7:1707)

#### lsb_release -a

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

#### uname -a

```
Linux 937278c1a3c0 5.10.109-0-virt #1-Alpine SMP Mon, 28 Mar 2022 11:20:52 +0000 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
you're using `jammy-proposed` which contains unreleased packages -- I'd recommend you report to ubuntu instead

**Comment by piexil** [comment]
This error now happens on non-proposed repos. All my docker containers using this repo and jammy broke. 
Has anyone opened a bug at ubuntu?

**Comment by asottile** [comment]
my guess is no

**Comment by stefanor** [comment]
> Has anyone opened a bug at ubuntu?

Yes: https://bugs.launchpad.net/ubuntu/+source/python3-stdlib-extensions/+bug/1990593

**Comment by piexil** [comment]
> > Has anyone opened a bug at ubuntu?
> 
> Yes: https://bugs.launchpad.net/ubuntu/+source/python3-stdlib-extensions/+bug/1990593

Thank you, I was filling my own but didn't want to double file. Added my +1 to that thread. 

For those who need a workaround, you can tell apt it's okay to overwrite the file. 
`sudo apt-get -o Dpkg::Options::="--force-overwrite" install <package>`

Be very careful and only use this to install the python package. This is just a readme file so it should be okay to overwrite, but I'm not guaranteeing anything.
