### ISSUE TITLE
Don't have python 3.10.8 for jammy

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [deadsnakes/issues#231]
### description

_fill in a description of your issue -- be specific!_

### os information
ubuntu 22.04
#### lsb_release -a

```
# paste the output of `lsb_release -a` here
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

#### uname -a

```
# paste the output of `uname -a` here
Linux deus-pc 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Don't have python 3.10.8 in ppa for jammy.

**Comment by asottile** [comment]
we don't provide python versions for ones provided by ubuntu as the primary python for the distribution

**Comment by Bogdan-Torkhov** [comment]
It's not the latest version.I want latest.Please add it.

**Comment by Bogdan-Torkhov** [comment]
In the description you writed that you provide latest python versions for all ubuntu version

**Comment by asottile** [comment]
I don't know what to tell you, read my last comment
