### ISSUE TITLE
Bionic 3.10 `armhf` build failing

### ISSUE THREAD

**Issue by johnthagen** [deadsnakes/issues#232]
### description

As shown here:

- https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic
- https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+build/24544153

The `armhf` build of Python 3.10 is failing to build. This appears to be affecting Tensorflow builds downstream:

- https://github.com/tensorflow/tensorflow/issues/56137#issuecomment-1289275446

Could this build be fixed, or is this a known issue/limitation with Bionic builds moving forward?

**Comment by asottile** [comment]
I reported this to cpython a while back -- there's nothing I can really do about this -- it seems to be a hardware fault

**Comment by johnthagen** [comment]
Thanks for the history. It looks like your bug report was here:

- https://github.com/python/cpython/issues/88209

Interestingly, it was marked as fixed in:

- https://github.com/python/cpython/issues/88209#issuecomment-1093914336
- https://github.com/python/cpython/commit/3b2a45ff95a68acc8276b37678c98740a232f6d4

**Comment by johnthagen** [comment]
Hey @asottile, so some good news. We think we've isolated the upstream issue to a missing bugfix backport to 3.10:

- https://github.com/python/cpython/pull/98677

Do you have the capability to do a test DeadSnakes build targeting a PR on CPython? It would be helpful to know if this truly fixes the DeadSnakes build issue. Thanks!

**Comment by asottile** [comment]
it is certainly possible, though I usually only backport specific patches for paid customers :S

**Comment by johnthagen** [comment]
We're hoping this gets up streamed into 3.10.9, so you wouldn't need to backport yourself permanently. Was thinking of doing a single CI job against the PR as a test to see if this fixes the issue.

**Comment by johnthagen** [comment]
The backport was merged into the `3.10` branch:

- https://github.com/python/cpython/pull/98677

**Comment by asottile** [comment]
cool, then it will land with the next patch version. unless someone wants to sponsor the work to get it sooner

**Comment by asottile** [comment]
I have no idea, they're not my machines

**Comment by jugmac00** [comment]
@johnthagen This is the publicly available information about the builder spec:
https://help.launchpad.net/Packaging/BuilderSpecs

If you need more details, you could write an email to feedback@launchpad.net 

Afaik we use some special images, ran via lxd, with restricted internet access.
