### ISSUE TITLE
deadsnake/action should only install from deadsnakes

### ISSUE THREAD

**Issue by nedbat** [deadsnakes/issues#234]
### description

deadsnake/action will install versions from Ubuntu instead of from deadsnakes.  3.9-dev was removed from deadsnakes in May.  The action continued to install 3.9-dev, but got it from focal-updates.

Here's an action that installed 3.9 successfully, but from focal-updates: https://github.com/nedbat/coveragepy/actions/runs/3590447527/jobs/6043849821#step:3:68

I guess focal removed 3.9-dev finally, because then my workflow started to fail: https://github.com/nedbat/coveragepy/actions/runs/3599755482/jobs/6067024908#step:3:88

The deadsnakes action should only install from deadsnakes.

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```
# paste the output of `uname -a` here
```

**Comment by asottile** [comment]
I think what happened is you got upgraded from 20.04 to 22.04 maybe?  I'll see what I can do but I'd like to avoid hardcoding the versions it installs :S  -- the `nightly` will only support versions until they exit bugfix support (which is why 3.9 got deleted) because I only have limited space in launchpad

**Comment by nedbat** [comment]
Is there some way to only install from the deadsnakes PPA, rather than from any configured PPA?

**Comment by asottile** [comment]
so `apt` has a `-t` but it doesn't seem to produce an error for packages that don't exist :( -- I tried `-t o=LP-PPA-deadsnakes-ppa`

**Comment by asottile** [comment]
deadsnakes/action@v3.0.0 now errors if the python does not come from deadsnakes

**Comment by nedbat** [comment]
Thanks!

**Comment by nedbat** [comment]
Hmm, something isn't right: it failed on 3.10: https://github.com/nedbat/coveragepy/actions/runs/3627427884/jobs/6117309116#step:3:96, perhaps because 3.10 is already installed in the ubuntu image?

**Comment by asottile** [comment]
3.10 is not provided for ubuntu-22.04 because the base OS provides it (and presents high risk of bricking the OS if I mess up)

**Comment by nedbat** [comment]
I changed my action to use ubuntu-20.04 so that I could install 3.10, 3.11, and 3.12 from deadsnakes nightly.  I would rather have a way to say, "don't worry about the OS, I'm just sure I want the nightlies," but at least I have a workaround.

**Comment by asottile** [comment]
could maybe do a matrix of `[{os: ubuntu-20.04, python: 3.10-dev}, {os: ubuntu-22.04, python: 3.11-dev}, {os: ubuntu-22.04, python: 3.12-dev}]`
