### ISSUE TITLE
Feature request: provide `python-is-pythonX.Y` packages

### ISSUE THREAD

**Issue by bersbersbers** [deadsnakes/issues#236]
Ubuntu has a [`python-is-python3` package](https://packages.ubuntu.com/focal/python-is-python3) which I find quite handy. Unfortunately, it depends on their `python3` package, which currently means `python3.8`.

I wonder if there is interest in (and it is possible) adding `python-is-pythonX.Y` packages to this repository, specific to each release. This way, users interested in using a single Python version could simply do `sudo apt install python-is-python3.11` to install the latest Python version and the continue to use their script using a simple `python` call.

**Comment by asottile** [comment]
this breaks the system
