### ISSUE TITLE
3.12 perf: -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer

### ISSUE THREAD

**Issue by nschloe** [deadsnakes/issues#239]
I'm trying to play around with [Python 3.12's perf profiler support](https://docs.python.org/3.12/howto/perf_profiling.html). As noted [here](https://docs.python.org/3.12/howto/perf_profiling.html#how-to-obtain-the-best-results),

> For the best results, Python should be compiled with `CFLAGS="-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"` [...]

Since this this is a pretty significant feature of 3.12, perhaps it'd be an idea to compile the PPA's Python version with said flags.

**Comment by asottile** [comment]
I don't enable any of the optimizations until it reaches rc because they cause compile times to take way longer and I spend way more time debugging weird build stuff during alpha / beta breakages

**Comment by nschloe** [comment]
Sure! Should I open a new bug when the first RC is released?

**Comment by asottile** [comment]
no -- I do not need to be told to do what I always do
