### ISSUE TITLE
Python 3.11.1-jammy was removed from upstream. 

### ISSUE THREAD

**Issue by imulmat4** [deadsnakes/issues#241]
### description

Python3.11.1 was removed from upstream. The only versions avilable are 3.11.2 and 3.11.0-rc. If yall could add 3.11.1 back to the upsteam so I dont need to build from source that would be awesome.

#### lsb_release -a

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

```

#### uname -a

```
5.19.0-76051900-generic #202207312230~1663791054~22.04~28340d4~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
launchpad only allows us to host a single version -- if you would like paid hosting for more versions you can reach out to me privately to arrange that
