### ISSUE TITLE
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu lunar Release' does not have a Release file.

### ISSUE THREAD

**Issue by bc500DT** [deadsnakes/issues#242]
### description

_fill in a description of your issue -- be specific!_

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```
# paste the output of `uname -a` here
```

**Comment by jugmac00** [comment]
The ppa is only available for LTS releases. Lunar is not a release, so you can't use this ppa.

**Comment by asottile** [comment]
as the first part of the issue template states:

> NOTE: deadsnakes only provides packages for ubuntu LTS releases (even number + .04)
> - it's a lot of  **free** work already to build packages for LTS releases
> - if you or your company would like to pay for this, please reach out directly
>  (you can find my email address in my commits)

**Comment by bc500DT** [comment]
can you post an alternative ppa link?

**Comment by asottile** [comment]
please take some time and actually read what I wrote
