### ISSUE TITLE
InRelease not signed

### ISSUE THREAD

**Issue by ashu032** [deadsnakes/issues#244]
There seems to be something wrong as every time I do a sudo update it gets interrupted with this error message. 

W: GPG error: https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BA6932366A755776
E: The repository 'https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease' is not signed.

I'm unable to remove the repository and reinstall it either.

**Comment by asottile** [comment]
you should be able to remove it in `/etc/apt/sources.list.d`

but it sounds like you're being man in the middled which is why the cert is invalid

**Comment by ashu032** [comment]
Hi. Thanks for your reply. I tried doing that but it didn't work. Is there
any other way to resolve the issue?

**Comment by asottile** [comment]
"didn't work" isn't a bug report -- you need to describe what you ran what you tried and what you saw
