### ISSUE TITLE
Rather than let what works as-is for ESM release, you deleted perfectly working packages and asked for payment instead

### ISSUE THREAD

**Issue by hans2520** [deadsnakes/issues#255]
This doesn't even follow the ESM convention, which allows updating packages up to the EOL date.
https://github.com/deadsnakes/issues/issues/251

It is understood that PPA hosting is limited space, however it doesn't appear to be the case that U18 releases were needing to be deleted just yet due to this limitation.

**Comment by asottile** [comment]
I understand you're frustrated -- but please read the duplicate issue you linked.  you're not paying me for ESM so you have no room to complain.
