### ISSUE TITLE
Missing release file for Luna

### ISSUE THREAD

**Issue by Jacamexx** [deadsnakes/issues#256]
### description

while trying to add the ppa to ubuntu 23.04 I found that there is no release fiule:

Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Adding deb entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Found existing deb-src entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-lunar.list
Adding key to /etc/apt/trusted.gpg.d/deadsnakes-ubuntu-ppa.gpg with fingerprint F23C5A6CF475977595C89F51BA6932366A755776
Hit:1 http://archive.ubuntu.com/ubuntu lunar InRelease                                                                           
Get:2 http://archive.ubuntu.com/ubuntu lunar-updates InRelease [109 kB]                                                          
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease                                                                             
Hit:4 https://ppa.launchpadcontent.net/cappelikan/ppa/ubuntu lunar InRelease                                                              
Get:5 http://archive.ubuntu.com/ubuntu lunar-backports InRelease [99,8 kB]                   
Ign:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu lunar InRelease                  
Get:7 http://archive.ubuntu.com/ubuntu lunar-security InRelease [109 kB]
Err:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu lunar Release                   
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar```

#### uname -a

```
Linux jacamoro-Zbook 5.19.0-42-generic #43-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 18:21:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by asottile** [comment]
read the issue template, right at the top

**Comment by th0ger** [comment]
@asottile But the issue is real. We cant install python3.10 on Ubuntu 23.04 lunar.
https://askubuntu.com/questions/1475895/install-python3-10-on-ubuntu-23-04
