### ISSUE TITLE
Could not install python 3.10 on ubuntu 18.04

### ISSUE THREAD

**Issue by liudonghua123** [deadsnakes/issues#257]
### description

Hi, I have a server which runs ubuntu 18.04. and I installed python 3.10.8 last year, maybe using your ppa (`sudo add-apt-repository ppa:deadsnakes/ppa && apt install python3.10`). See also https://ubuntuhandbook.org/index.php/2021/01/install-python-3-10-alpha-ubuntu-20-04-ubuntu-18-04/.

But when I tried to reinstall the python 3.10 due to missing `Python.h and pyconfig.h` (I removed python 3.10.8 accidently), then I could not install python3.10 anymore. 

I tried to download debs from http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/pool/main/p/python3.10/ and use `dpkg -i *` to install them, but it failed with libc6 version conflicts. 

I also noticed this [commit](https://github.com/deadsnakes/python3.10/commit/0aab4f7d19ae663449339066501de9d80d1da044), maybe the ubuntu 18.04 support is removed just a few days ago.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

#### uname -a

```
Linux xxs 4.15.0-210-generic #221-Ubuntu SMP Tue Apr 18 08:32:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by liudonghua123** [comment]
Is there anyway I can install the old python 3.10.8 on my ubuntu 18.04?

**Comment by jugmac00** [comment]
See the pinned issue: https://github.com/deadsnakes/issues/issues/251

In the issue template, which you deleted, there was a note to read the pinned issues first.

**Comment by liudonghua123** [comment]
@jugmac00 Thanks, I see. I build python 3.10 on ubuntu 18.04 from source. And I also forked https://github.com/deadsnakes/python3.10 and modified the [.github/workflows/main.yml](https://github.com/liudonghua123/python3.10/blob/main/.github/workflows/main.yml), build and push the debs and [all-in-one.tar](https://github.com/liudonghua123/python3.10/releases/download/3.10.12/python-3.10.12-bionic-amd64-all-in-one.tar) to the [release](https://github.com/liudonghua123/python3.10/releases/tag/3.10.12), just for personal usage if I need to install python 3.10 on old ubuntu 18.04.
