### ISSUE TITLE
No secret key

### ISSUE THREAD

**Issue by masterkiga** [deadsnakes/issues#259]
### description

```
bash ./build_python3.sh --version 3.10
```
After a couple of hours of building then aborts with...
```
Now signing changes and any dsc files...
 signfile dsc python3.10_3.10.11-1+bionic1.dsc Anthony Sottile (deadsnakes) <asottile+deadsnakes@umich.edu>
gpg: skipped "Anthony Sottile (deadsnakes) <asottile+deadsnakes@umich.edu>": No secret key
gpg: /tmp/debsign.JidEbCXv/python3.10_3.10.11-1+bionic1.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1081:
running debsign failed
gbp:error: 'debuild -i -I' failed: it exited with 29
```
#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

```

#### uname -a

```
Linux jetson01 4.9.337-tegra #1 SMP PREEMPT Thu Jun 8 21:19:14 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by asottile** [comment]
please read the pinned issues and issue template next time

**Comment by masterkiga** [comment]
As Ubuntu 18.04/Python3.10 doesn't seem to be a supported combination I spent some time upgrading the Nvidia Jetson Nano to Ubuntu 20.04, re-adding the ppa and tried building Python3.10 - again the gpg error occurred after a couple of hours of building to say No secret key. Is there any other pinned issue I should be reviewing?

**Comment by asottile** [comment]
ubuntu 18.04 is not supported -- nor is whatever your `build_python3.sh` is -- if you want enterprise support please reach out privately.
