### ISSUE TITLE
Python 3.11.6 update missing in the repository

### ISSUE THREAD

**Issue by niturk** [deadsnakes/issues#263]
Hey Deadsnakes Team,

I've noticed that the repository currently has Python 3.11.5, but I think there's a newer version available, Python 3.11.6. It looks like the update for 3.11.6 might have been missed or overlooked.

Can you please give me an update on this or maybe add the 3.11.6 version to the repository?

I really appreciate all your hard work in keeping the community up to date with the latest Python versions.

Thanks

**Comment by asottile** [comment]
as the ppa description indicates there is no guarantees of timely updates.  I do this work for free and if you want an SLA for your used that can be set up with a contract
