### ISSUE TITLE
Install a specific version of Python 3.11

### ISSUE THREAD

**Issue by jcus0006** [deadsnakes/issues#264]
This is not an issue, it is actually a question. Apologies if this is not the right place where to ask this but I don't know of anywhere else I could ask.

Is there a way to use deadsnakes to install a specific version of Python? for e.g. at an earlier time I had used deadsnakes to install Python 3.11.2. I am now using the same instructions and getting a later version 3.11.5. 

I would like to install the same version 3.11.2 on a different machine. Is there a way to achieve this?

**Comment by asottile** [comment]
launchpad only allows us to publish a single version for a particular release

if you'd like support for a previous version you can build it yourself (at no support -- I do not have the time to help you do this for free) or set up a support contract -- you can contact me through my commit email address

**Comment by jcus0006** [comment]
when you say build it yourself do you mean via the source code? or extend launchpad to support a previous version? and if it is the latter, are there any instructions or so?

**Comment by jugmac00** [comment]
I assume @asottile referred to the former, i.e. compiling Python from source, see https://devguide.python.org/getting-started/setup-building/.

You could also create a PPA yourself with a different Python version, but I assume except from the part on how to create a PPA, this is highly undocumented, and significantly more effort.
https://help.launchpad.net/Packaging/PPA
