### ISSUE TITLE
Issue Installing Python 3.10 on Ubuntu 18.04 - Always Installs postgresql-plpython3-10 Instead

### ISSUE THREAD

**Issue by muhamedoufi** [deadsnakes/issues#269]
Issue Description:
When attempting to install Python 3.10 on Ubuntu 18.04 (Bionic), the installation process unexpectedly installs the postgresql-plpython3-10 package instead.

Environment:

Distributor ID: Ubuntu
Description: Ubuntu 18.04.6 LTS
Release: 18.04
Codename: Bionic
Steps to Reproduce:

Run the command sudo apt install python3.10.
Observe that the installation process selects and installs postgresql-plpython3-10 instead of Python 3.10.
Expected Behavior:
The expected behavior is that running sudo apt install python3.10 installs Python 3.10 without automatically installing the ```postgresql-plpython3-10``` package.

Observed Behavior:
The observed behavior is that the installation process selects and installs ```postgresql-plpython3-10``` alongside ```Python 3.10.```

Additional Information:

Running apt list -a python3.10 shows the available versions of Python 3.10.
The issue persists even after attempting to use specific version numbers and other workaround commands.
Purging the ```postgresql-plpython3-10``` package using ```sudo apt-get purge postgresql-plpython3-10``` did not resolve the issue.
Screenshots/Logs:
Include any relevant terminal output or logs during the installation process.

```root@server:/var/www/tracking# sudo apt install python3.10                  
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Note : sélection de postgresql-plpython3-10 pour l'expression rationnelle « python3.10 »
Les NOUVEAUX paquets suivants seront installés :
  postgresql-plpython3-10
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/50,7 ko dans les archives.
Après cette opération, 184 ko d'espace disque supplémentaires seront utilisés.
Sélection du paquet postgresql-plpython3-10 précédemment désélectionné.
(Lecture de la base de données... 114271 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../postgresql-plpython3-10_10.23-0ubuntu0.18.04.2_amd64.deb ...
Dépaquetage de postgresql-plpython3-10 (10.23-0ubuntu0.18.04.2) ...
Paramétrage de postgresql-plpython3-10 (10.23-0ubuntu0.18.04.2) ...
Traitement des actions différées (« triggers ») pour postgresql-common (190ubuntu0.1) ...
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:```

**Comment by asottile** [comment]
please read the issue template and the pinned issues
