### ISSUE TITLE
PEP 703: deadsnakes builds with `--disable-gil`

### ISSUE THREAD

**Issue by hugovk** [deadsnakes/issues#270]
### description

First off, thank you for maintaining deadsnakes, it's really helpful for testing nightly builds!

[PEP 703](https://peps.python.org/pep-0703/) has been [accepted](https://discuss.python.org/t/pep-703-making-the-global-interpreter-lock-optional-in-cpython-acceptance/37075) to remove the GIL. The rollout is planned in three phases, and for success, it's extremely important to get community feedback and support to be able to move to the next phase.

Therefore it's also extremely important for the community to be able to test the "free-threaded" aka "nogil" builds of Python. This requires a separate build of Python 3.13 with the `--disable-gil` flag enabled for the configure script (see the [PEP](https://peps.python.org/pep-0703/#build-configuration-changes) and [CPython CI](https://github.com/search?q=repo%3Apython%2Fcpython+--disable-gil+language%3AYAML&type=code)).

To achive this, it would be very helpful if deadsnakes PPA and https://github.com/deadsnakes/action were also available as free-threaded builds for 3.13 (and later) to enable the community to try them out and give feedback (perhaps the deadsnakes/action via `with: disable-gil: true`).

It's still a bit early for extension authors to start testing, but it would be great to have the testing infra ready for when the time comes.

Would this be possible?

**Comment by asottile** [comment]
the build already exists if you've checked

**Comment by hugovk** [comment]
So it does, I should have known you're already on it and checked first, thanks!

Do we still need something to enable it for deadsnakes/action?

For example: https://github.com/deadsnakes/action/pull/123
