### ISSUE TITLE
libpython3.12-testsuite installation error

### ISSUE THREAD

**Issue by TechnoDexx** [deadsnakes/issues#273]
### description

The libpython3.12-testsuite (3.12.1-1+jammy2) package is being configured...
   File "/usr/lib/python3.12/test/test_lib2to3/data/bom.py", line 2
     print "BOM BOOM!"
     ^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
dpkg: error processing package libpython3.12-testsuite (--configure):
  subprocess from libpython3.12-testsuite package installed post-installation script returned error code 1
dpkg: package dependencies do not allow python3.12-full package to be configured:
  python3.12-full depends on libpython3.12-testsuite, however:
   The libpython3.12-testsuite package is not configured yet.

dpkg: error processing package python3.12-full (--configure):
  dependency problems - leave unconfigured
Errors occurred while processing the following packages:
  libpython3.12-testsuite
  python3.12-full

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

```

#### uname -a

```
Linux HomeShark 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by bmos** [comment]
Throwback to issue #235 

I have this occurring as well.

**$ lsb_release -a**

```
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

**$ uname -a**

```shell
Linux wil-desktop 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by albcunha** [comment]
I got the same error too

**Comment by asottile** [comment]
@albcunha that's what the thumbs up button is for.  adding "same" just generates spam

**Comment by asottile** [comment]
looks like lib2to3 tests also moved so I've got those too -- should be fixed in jammy3 and focal2

**Comment by dilnix** [comment]
Thanks, it's fixed now, and updated successfully.
But still, there is a syntax warning:

![Screenshot_20231210_225212](https://github.com/deadsnakes/issues/assets/33361500/e8821e23-0522-4766-aaf7-fea3cece11b3)

**Comment by asottile** [comment]
that's a bug in python itself
