### ISSUE TITLE
Nightly build of 3.13 failing

### ISSUE THREAD

**Issue by a-reich** [deadsnakes/issues#274]
### description
Not sure if this is the right place to put this, but it seems like the nightly build for 3.13 has been failing for the past week?

They seem to have a consistent message at the end of the logs:

> dh_movefiles: warning: debian/tmp/usr/lib/python3.13/pathlib.py not found (supposed to put it in libpython3.13-minimal)

So could be related to https://github.com/python/cpython/pull/112881 recently changing pathlib from a file to directory.

**Comment by asottile** [comment]
yep no need to notify I get emailed about these when they fail

it'll get fixed eventually
