### ISSUE TITLE
`add-apt-repository ppa:deadsnakes/ppa` timing out?

### ISSUE THREAD

**Issue by ReubenFrankel** [deadsnakes/issues#277]
### description

Not sure this is the right place for this, but when I run

```
add-apt-repository ppa:deadsnakes/ppa
```

the command hangs with no output (with or without `-d`) for over 15 mins - I gave up after that.

https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa is also down for me currently.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

#### uname -a

```
Linux 50e099e3f73c 6.5.11-linuxkit #1 SMP PREEMPT_DYNAMIC Wed Dec  6 17:14:50 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ReubenFrankel** [comment]
Think it just came back up, never mind.

**Comment by mahotd** [comment]
fyi https://launchpad.net is down

see https://status.canonical.com/
