### ISSUE TITLE
Python 3.12.2 and 3.11.8

### ISSUE THREAD

**Issue by jorenham** [deadsnakes/issues#278]
Hi hi,

I was wondering when I can expect the python 3.12.2 and 3.11.8 packages. Is there an ETA, or are there perhaps some issues because of the new SBOM?

**Comment by asottile** [comment]
unless you are paying there's no SLA

**Comment by jorenham** [comment]
I am aware of that, and I wasn't asking for one. 

Correct me if I'm wrong here; but are you saying that there there are no plans to publish new packages? Because if so, that's absolutely fine by me; I just like to know whether I have to switch to another repo, that's all :)

**Comment by asottile** [comment]
read the ppa description

**Comment by jorenham** [comment]
@asottile I have; it doesn't answer my question. 
Hence my question on whether there is an ETA or plans for releasing the Python 3.12.2 and Python 3.11.8 packages.

**Comment by asottile** [comment]
right at the top, please read:

> Disclaimer: there's no guarantee of timely updates in case of security problems or other issues. If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk
