### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by nedbat** [deadsnakes/issues#281]
### description

I was running against the nightlies of 3.11, 3.12 and 3.13.  [Last night, 3.11 failed to install](https://github.com/nedbat/coveragepy/actions/runs/8771014777/job/24070368677).  Looking at the [nightly packages](https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly/+packages), I see only 3.12 and 3.13, so I guess 3.11 isn't being provided anymore because of its maturity.

Is there something like a changelog or news page that would state this shift explicitly?  Perhaps there's something well-known in the PPA world that I'm not familiar with.

Thanks!

**Comment by asottile** [comment]
https://github.com/deadsnakes/nightly

essentially I remove them when they enter security only
