### ISSUE TITLE
Support for new Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by lucasfijen** [deadsnakes/issues#282]
### description

I might be really quick on the boat, but yesterday the new LTS dropped for Ubuntu; 24.04. 
Are you planning on adding support for this version?

Also, just wanted to express how much I appreciate deadsnakes, it makes installing different python versions for developing really hassle free, thank you so much!

### os information

Ubuntu 24.04 LTS

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```
# paste the output of `uname -a` here
```

**Comment by MikeMcC399** [comment]
This would be much appreciated. Hopefully it is already being planned! I'm especially looking for Python `3.11` as Ubuntu 22.04 ships with Python `3.12`, which is too high.

https://releases.ubuntu.com/noble/

```text
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```

```text
$ uname -a
Linux ubuntu-24-04 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
we usually follow up within a week or so.  if you want this expedited consider sponsoring or supporting the project as it's only worked on in my freetime

**Comment by wydnas** [comment]
Echoing the grateful sentiments above but Python 3.10 needed here.  Keep up the good work.

**Comment by fuog** [comment]
Wow, that was quick! Thank you so much for the work. Iust found `python3.10` @ 24.04 :heart: 
Unfortunately I found an error in the package. I'm opening a separate issue for it.. #283

**Comment by asottile** [comment]
this isn't closed yet so please don't

**Comment by asottile** [comment]
these should be available now -- minus 3.13 which is in process of building

**Comment by MikeMcC399** [comment]
@asottile 

Thank you very much! `python3.11` is working fine for me on Ubuntu `24.04` 🎉

**Comment by jaraco** [comment]
> these should be available now -- minus 3.13 which is in process of building

Where's the best place to follow progress on this concern?

**Comment by asottile** [comment]
ironically @jaraco you broke the build with the configparser changes

**Comment by jaraco** [comment]
> ironically @jaraco you broke the build with the configparser changes

Oh, that's the first I'm hearing about it. Strange I don't see anything in my email pertaining to it. I check the bug tracker.

**Comment by jaraco** [comment]
I got around to checking this issue again and it seems to have been solved now.

**Comment by bachphi** [comment]
I am running Ubuntu 24.04  & Python3.12.3.  Installing MSSQL got some errors related to Python. I want to install Python3.11.
But when I tried to add 'add-apt-repository ppa:deadsnakes/ppa'  , I got TimeoutError [Errno 110] Connection timed out and a long list of errors above it.

How do I install Python3.11?

**Comment by asottile** [comment]
that's a problem with your Internet connection and not deadsnakes
