### ISSUE TITLE
python `3.13.0b1` has been released

### ISSUE THREAD

**Issue by Venkat2811** [deadsnakes/issues#285]
### description

Hey Team, thank you for the great work !  I have been using your `python 3.13.a06` for experimenting.   `3.13.0b1` has been released with several fixes https://github.com/python/cpython/releases/tag/v3.13.0b1

Thanks,
Venkat

**Comment by asottile** [comment]
please read the ppa description and don't do this

**Comment by Venkat2811** [comment]
Hey @asottile ,

Yes I read description of [main](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) and [nightly ppa](https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly).  3.13 nightly is not updated while 3.12 nightly is.

I also see 3.13 nightly builds failing here: https://github.com/deadsnakes/python3.13-nightly/actions/workflows/main.yml

Sorry, am I missing something here ?
