### ISSUE TITLE
python `3.13.0b1` nightly build failing

### ISSUE THREAD

**Issue by Venkat2811** [deadsnakes/issues#286]
Sorry, I was not clear when creating [issue](https://github.com/deadsnakes/issues/issues/285#issuecomment-2102961248).

I read description of [main](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) and [nightly ppa](https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly).  3.13 nightly is not updated while 3.12 nightly is.

I also see 3.13 nightly builds failing here: https://github.com/deadsnakes/python3.13-nightly/actions/workflows/main.yml

**Comment by asottile** [comment]
I thought I told you "don't do this"
