### ISSUE TITLE
GitHub Action workflow cannot find the signing GPG key

### ISSUE THREAD

**Issue by andfoy** [deadsnakes/issues#288]
Thanks for providing support for the latest Python 3.13 beta packages, they have been very useful in several projects in the Scientific Python ecosystem, which are using 3.13 to test against the novel free-threaded features. 

During the past week, we have experienced a major error when the deadsnakes action is trying to set up the PPA in the GitHub actions runner, this error states that the GPG key is not temporarily available. According to several Ubuntu forums, this is due to the signing key not being available in the local key repository. e.g., https://askubuntu.com/questions/127326/how-to-fix-missing-gpg-keys

Here is an example CI run that failed due to the aforementioned error: https://github.com/scipy/scipy/actions/runs/9602812965/job/26484508195?pr=21007 

I would like to know if this is something that can be fixed on your end, or if it is a setting that is missing from the project's end

cc @rgommers

**Comment by asottile** [comment]
if you read the output you'll notice a very obvious failure:

```
  lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
```

this isn't a deadsnakes issue and everything works just fine when launchpad isn't serving 500s
