### ISSUE TITLE
deadsnakes/action: `3.13` is 3.13.0b2 not 3.13.0b3

### ISSUE THREAD

**Issue by hugovk** [deadsnakes/issues#289]
### description

Use `deadsnakes/action` to install `3.13` on GitHub Actions.

https://github.com/hugovk/test/actions/runs/9819140702/job/27112413646

It's 3.13.0b2 from 8th June, rather than the latest 3.13.0b3 from 27th June:

https://peps.python.org/pep-0719/

```
Run python --version --version && which python
  python --version --version && which python
  shell: /usr/bin/bash -e {0}
Python 3.13.0b2 (main, Jun  8 2024, 19:40:00) [GCC 11.4.0]
/home/runner/venv-3.13/bin/python
```

Perhaps caused by https://github.com/deadsnakes/python3.13/actions/runs/9430734473/job/25978611794 ?

```
Using index info to reconstruct a base tree...
M    Lib/_pyrepl/pager.py
Falling back to patching base and 3-way merge...
Auto-merging Lib/_pyrepl/pager.py
CONFLICT (content): Merge conflict in Lib/_pyrepl/pager.py
```

### os information

```
Operating System
  Ubuntu
  22.04.4
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20240630.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240630.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240630.1
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

#### uname -a

```
Linux fv-az1542-307 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May  9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
please read the ppa description

**Comment by hugovk** [comment]
I read https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa but I'm not sure which bit you mean, maybe this? 

> Disclaimer: there's no guarantee of timely updates in case of security problems or other issues.

**Comment by asottile** [comment]
that one indeed! I'm well aware when things are out of date because I get a saying reminder, I'm just very very busy and doing it for free
