### ISSUE TITLE
Cannot add repository to docker container - ssl error

### ISSUE THREAD

**Issue by randall-mcbride** [deadsnakes/issues#291]
### description

I am trying to install Python 3.12 on a docker container running Ubuntu 22.04. When running "add-apt-repository ppa:deadsnakes/ppa" I get the following error;

File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

#### lsb_release -a

```
# paste the output of `lsb_release -a` here

root@6c05a12dd21f:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

#### uname -a
```
# paste the output of `uname -a` here

Linux 6c05a12dd21f 4.18.0-513.9.1.el8_9.x86_64 #1 SMP Thu Nov 16 10:29:04 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by asottile** [comment]
works fine for me.  you probably have a mitm proxy, clock skew, etc  -- we don't maintain that as well so I can't help you and you'd need to bring that up with launchpad
