### ISSUE TITLE
3.13t has today's date; 3.14t is July 11th

### ISSUE THREAD

**Issue by nedbat** [deadsnakes/issues#292]
I'm using deadsnakes to get nightly builds of 3.13 free-threading and 3.14 free-threading.  3.13t looks great.  But 3.14 is weeks out of date:

Links to the coverage.py Python nightly actions, showing `python -m site`:

[python -m site](https://github.com/nedbat/coveragepy/actions/runs/10193932876/job/28199492932#step:5:14) on 3.13t:
```
+ python -VV
Python 3.13.0b4+ experimental free-threading build (main, Jul 31 2024, 08:49:16) [GCC 11.4.0]
+ python -m site
sys.path = [
    '/home/runner/work/coveragepy/coveragepy',
    '/usr/lib/python313t.zip',
    '/usr/lib/python3.13',
    '/usr/lib/python3.13/lib-dynload',
    '/home/runner/venv-3.13/lib/python3.13t/site-packages',
]
```

[python -m site](https://github.com/nedbat/coveragepy/actions/runs/10193932876/job/28199493431#step:5:14) on 3.14t:
```
+ python -VV
Python 3.14.0a0 experimental free-threading build (main, Jul 11 2024, 08:47:28) [GCC 11.4.0]
+ python -m site
sys.path = [
    '/home/runner/work/coveragepy/coveragepy',
    '/usr/lib/python314.zip',
    '/usr/lib/python3.14',
    '/usr/lib/python3.14/lib-dynload',
    '/home/runner/venv-3.14/lib/python3.14/site-packages',
]
```

**Comment by asottile** [comment]
yep the build for 3.14 has been broken for a while.  it will get fixed when I get some free time

**Comment by nedbat** [comment]
Maybe we should leave the issue open until it is?

**Comment by nedbat** [comment]
Is there some kind of help we can rally for you? I've been depending on deadsnakes for a while.  It's disappointing to realize that my Python Nightly tests are weeks behind.

**Comment by asottile** [comment]
I actually tried to prevent exactly this type of issue with the template but failed I guess heh: https://github.com/deadsnakes/issues/blame/main/.github/ISSUE_TEMPLATE.md#L4

haven't looked at the actual breakage yet but the falling build in https://github.com/deadsnakes/python3.14-nightly might have enough of a hint to fix it but it's a fairly shallow learning curve

**Comment by nedbat** [comment]
@asottile Since we agree that something is broken, where is the right place to keep an issue open while it's being worked on?

**Comment by asottile** [comment]
you can follow the status here: https://github.com/deadsnakes/nightly?tab=readme-ov-file#available-packages or for a specific version here: https://github.com/deadsnakes/python3.14-nightly

**Comment by nedbat** [comment]
Thanks, but one of the advantages of an open issue for something that needs to be fixed is that I can subscribe to the issue and be notified when it is closed.  Others can see there is work that needs to be done, and help out.  Why close an issue before it is fixed?

**Comment by asottile** [comment]
because I already spend way too much time on this for free and micromanaging issues in the experimental nightly builds (when there is explicitly no guarantees of timely updates) is not something I'm willing to do

**Comment by asottile** [comment]
I tried to make that clear here: https://github.com/deadsnakes/issues/commit/68b4f3d7a0952423986548dad551dba0a07d441b

I know that's slightly inconvenient for you, but it helps keep the maintenance here as minimal as possible

**Comment by nedbat** [comment]
I don't mean to be oppositional about this. The deadsnakes builds are a great resource and I appreciate everything you're doing.  I'd like to try to rally others to help you and get this fixed. But it's hard when the needed work isn't visible.

**Comment by asottile** [comment]
it's plenty visible, you just want a notification :) subscribe to the builds then!

**Comment by hugovk** [comment]
The error is:

```
Missing modules in python-minimal:
{'annotationlib'}
('annotationlib', 'used in: ', ['functools', 'inspect'])
```

https://github.com/deadsnakes/python3.14-nightly/actions/runs/10195066418/job/28203021859#step:7:2316

Which sounds reasonable because annotionlib is a new module in 3.14, merged two weeks ago in https://github.com/python/cpython/pull/119891.

So does annotionlib need adding to python-minimal? Where would that be?

**Comment by nedbat** [comment]
There are two kinds of visibility I'm talking about: 
- People who want to help make deadsnakes better: they need to see what work needs to be done, and the progress.
- People who want to use deadsnakes: they want to know what is broken and what works

You mentioned "subscribe to the builds": I'm not sure what that means, where do I do that?

**Comment by asottile** [comment]
> There are two kinds of visibility I'm talking about:
> 
>  * People who want to help make deadsnakes better: they need to see what work needs to be done, and the progress.
> 
>  * People who want to use deadsnakes: they want to know what is broken and what works
> 

both of those things are visible on https://github.com/deadsnakes/nightly

>  You mentioned "subscribe to the builds": I'm not sure what that means, where do I do that?

watch the repositories you care about

**Comment by nedbat** [comment]
> watch the repositories you care about

Can you be more specific? What repository, and what kind of watching?  Normally I watch issues.  If you mean get notifications about all commits, that would be noisy.

Thanks for fixing 3.14, what notification could I have gotten to know that you had?

**Comment by asottile** [comment]
please [respect my boundaries](https://github.com/deadsnakes/issues/issues/292#issuecomment-2267591531)
