### ISSUE TITLE
Local binary build

### ISSUE THREAD

**Issue by jhgorse** [deadsnakes/issues#294]
Hi,

Thank you for this project. It is a real life saver.

Hopefully quick question, how do I use this to build/reproduce the `deadsnakes` build for a specific ubuntu python release locally? Say for example, ubuntu/jammy python3.11.3.

I can see some hints in `updating.md` and the build logs, but can't quite get Docker to kick off. Thoughts?

Cheers,
Joe

**Comment by asottile** [comment]
it's just standard gbp (or you can skip gbp and use the dpkg building tools) 

unfortunately I don't have the time to teach you for free but there are plenty of resources out there

**Comment by jhgorse** [comment]
Thank you for writing.

For anyone who comes along and tries to reproduce, here are my breadcrumbs for ubuntu 22.04.4:
```
sudo apt-get install git dpkg-dev devscripts git-buildpackage
git config --global user.name 'Anthony Sottile (deadsnakes)'
git config --global user.email 'asottile+deadsnakes@umich.edu'
export DEBFULLNAME='Anthony Sottile (deadsnakes)'
export DEBEMAIL='asottile+deadsnakes@umich.edu'
gpg --generate-key

git clone https://github.com/deadsnakes/python3.11 -b debian/3.11.3-1+jammy2
git clone https://github.com/deadsnakes/runbooks
# patch ./runbooks/build to include `--git-ignore-branch` where you see `--git-pristine-tar`
cd python3.11 && ../runbooks/build --git-build
```

It was not and is still not obvious what branch was supposed to be used for the `deadsnakes/python3.11` repository. I suspect that is why I needed to add `--git-ignore-branch`. None of the update or import scripts appeared to run successfully or give useful error messages regarding the assumed initial state.

This did build and pass the `runbooks/quick-test`.

Cheers,
Joe

**Comment by asottile** [comment]
that's definitely not correct and please don't impersonate me

**Comment by jhgorse** [comment]
Ok.

Where did the `debian` folder come from? Is this a copy from their package management team?

**Comment by asottile** [comment]
> unfortunately I don't have the time to teach you for free but there are plenty of resources out there
