### ISSUE TITLE
Ubuntu 24.04.1 and deadsnakes version issues

### ISSUE THREAD

**Issue by rlippmann** [deadsnakes/issues#297]
### description

Trying to upgrade/reinstall various packages I keep running into the following errors:

```
The following packages have unmet dependencies:
 libpython3.12t64 : Depends: libpython3.12-stdlib (= 3.12.3-1ubuntu0.1) but 3.12.5-1+jammy1 is to be installed
```

Apparently a lot of things depend on python in Noble, so I can't do things like upgrade/reinstall samba, vim, etc.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

#### uname -a

```
Linux pkitty 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rlippmann** [comment]
So, I think I managed to fix this:

sudo aptitude remove python3
sudo ppa-purge ppa:deadsnakes/ppa
sudo apt reinstall python3

**Comment by asottile** [comment]
we don't provide python 3.12 on noble, that's ununtu's package

**Comment by rlippmann** [comment]
I'm aware.  The problem is that if you have 3.12 installed on jammy via deadsnakes, it conflicts with the one noble wants to install.

**Comment by rlippmann** [comment]
So, since the version in deadsnakes jammy is higher (3.12.5) than what ubuntu provides (3.12.3), apt can't find 3.12.5+ in the ubuntu repos.  Nor in deadsnakes because 3.12 isn't there either.

**Comment by asottile** [comment]
you're in severely unsupported territory -- trying to install a python on the wrong ubuntu release is asking for trouble (especially if you're trying to overwrite the system python)

**Comment by rlippmann** [comment]
That's not what I did, though.

I had jammy with the system versions of python.  I installed 3.12 via deadsnakes on jammy to do development.  Not as the system python, just installed the binaries.

When I went and tried to upgrade from jammy to noble, apt saw a version of 3.12 there.  So, it tried to use it.  Unfortunately, deadsnakes was at 3.12.5, noble is at 3.12.3, so apt gave up.

If you want to reproduce:
1) install jammy on a machine
2) add deadsnakes ppa
3) install 3.12 from deadsnakes onto the jammy machine
4) try to upgrade to noble from there.

**Comment by anto-acube** [comment]
I had the very same issue @rlippmann. How did you managed to continue the Ubuntu release upgrade? My sourcelists are completely messed up.

**Comment by asottile** [comment]
ah rookie mistake.  you'll want to purge all ppas when upgrading

**Comment by sandblasted** [comment]
For future reference you can manually downgrade to the distro version.

$ sudo apt-get install python3.12=3.12.3-1ubuntu0.2 python3.12-minimal=3.12.3-1ubuntu0.2 libpython3.12-stdlib=3.12.3-1ubuntu0.2 libpython3.12-minimal=3.12.3-1ubuntu0.2

To check the available version numbers use
$ apt-cache policy python3.12-minimal
