### ISSUE TITLE
python3.13-nogil has no pip? Also there is no python3.13-nogil-venv?

### ISSUE THREAD

**Issue by mw66** [deadsnakes/issues#299]
### description

python3.13-nogil has no pip?

```
$ python3.13-nogil -m pip install joblib
/usr/bin/python3.13-nogil: No module named pip
```

Also there is no python3.13-nogil-venv? 

```
$ sudo apt-get install python3.13-nogil-venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.13-nogil-venv
E: Couldn't find any package by glob 'python3.13-nogil-venv'
E: Couldn't find any package by regex 'python3.13-nogil-venv'
```

### os information

Linux  6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

#### lsb_release -a

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

#### uname -a

```
Linux  6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
search the issue tracker or read the description: no packages include pip, make a virtualenv.

you're looking for python3.13-venv

**Comment by mw66** [comment]
So, does `python3.13-nogil` work with `python3.13-venv`?

Are they compatible?

**Comment by asottile** [comment]
it takes you about as much time to try it than to ask.  please don't waste my time and just try it -- it's literally what I told you the answer was already
