### ISSUE TITLE
Enable pgo?

### ISSUE THREAD

**Issue by asottile** [deadsnakes/issues#3]
Upstream debian turns this off: investigate why and see if we can turn it on for our builds (since we don't support as many platforms).

This will likely add a lot of time to our builds if we choose to do this.

Perhaps @fkrull knows why this is off -- I couldn't find anything definitive :(

**Comment by fkrull** [comment]
I don't know, unfortunately. I faintly remember trying to turn it on and having a bunch of problems, but I may be confusing it with another feature. You could always try it and see what happens; that's what test suites are for, right? He said, overly optimistic. :D

**Comment by fkrull** [comment]
See https://github.com/deadsnakes/python3.6/pull/1
