### ISSUE TITLE
Python 3.14 for Focal?

### ISSUE THREAD

**Issue by pekkaklarck** [deadsnakes/issues#300]
Great work getting Python 3.14 available so fast! What's the status with the Focal support? It doesn't seem to be supported at least yet, but it hasn't yet reached it EOL (#251) either. I totally understand if there are problems with it that you don't want to tackle, though. I should upgrade anyway...

**Comment by asottile** [comment]
when is the release date of 3.14?

when is the end of life of focal?

**Comment by pekkaklarck** [comment]
Good point. I was hoping to delay upgrading until I buy a new laptop sometime early next year, but I really need to test annotation changes before that. Well, it's my problem and not yours. Thanks for the great service!
