### ISSUE TITLE
Add JIT builds

### ISSUE THREAD

**Issue by mdboom** [deadsnakes/issues#302]
### description

Add experimental JIT builds for 3.14-dev.

Just as the experimental free-threading (nogil) builds are available, we should also make it easy to access the experimental JIT builds.

Building requires:

- clang-18 / llvm-18 installed at build time
- Pass `--enable-experimental-jit=yes` to `./configure`

**Comment by asottile** [comment]
I am waiting to see what Debian decides to do here and then will follow what they do

**Comment by mdboom** [comment]
Do you have a pointer to where that discussion is happening?  (Google is failing me...)

**Comment by asottile** [comment]
I don't think there is one
