### ISSUE TITLE
Upgrading to 3.12.8 and 3.13.1 on Ubuntu 22.04 - Broken install

### ISSUE THREAD

**Issue by andesouz** [deadsnakes/issues#305]
### description

Here's tha outcome of running apt upgrade on Ubuntu 22.04 (December 4, 2024)

ubuntu-> sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libpython3.12 : Depends: libpython3.12-stdlib (= 3.12.8-1+jammy1) but 3.12.7-1+jammy1 is installed
 libpython3.12-dev : Depends: libpython3.12-stdlib (= 3.12.8-1+jammy1) but 3.12.7-1+jammy1 is installed
 libpython3.12-testsuite : Depends: python3.12 (>= 3.12.8-1+jammy1) but 3.12.7-1+jammy1 is installed
 libpython3.13 : Depends: libpython3.13-stdlib (= 3.13.1-1+jammy1) but 3.13.0-1+jammy1 is installed
 libpython3.13-dev : Depends: libpython3.13-stdlib (= 3.13.1-1+jammy1) but 3.13.0-1+jammy1 is installed
 python3.12-dev : Depends: python3.12 (= 3.12.8-1+jammy1) but 3.12.7-1+jammy1 is installed
 python3.12-examples : Depends: python3.12 (>= 3.12.8-1+jammy1) but 3.12.7-1+jammy1 is installed
 python3.12-full : Depends: python3.12 (= 3.12.8-1+jammy1) but 3.12.7-1+jammy1 is installed
 python3.12-venv : Depends: python3.12 (= 3.12.8-1+jammy1) but 3.12.7-1+jammy1 is installed
 python3.13-dev : Depends: python3.13 (= 3.13.1-1+jammy1) but 3.13.0-1+jammy1 is installed
 python3.13-venv : Depends: python3.13 (= 3.13.1-1+jammy1) but 3.13.0-1+jammy1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

When runnung apt --fix-broken-install, here's the outcome:

ubuntu-> sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libpython3.12-minimal libpython3.13-minimal python3.12-minimal python3.13-minimal
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libpython3.12-stdlib libpython3.13-stdlib python3.12 python3.13
The following packages will be upgraded:
  libpython3.12-stdlib libpython3.13-stdlib python3.12 python3.13
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
11 not fully installed or removed.
Need to get 0 B/10.9 MB of archives.
After this operation, 25.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 419808 files and directories currently installed.)
Preparing to unpack .../python3.12_3.12.8-1+jammy1_amd64.deb ...
Unpacking python3.12 (3.12.8-1+jammy1) over (3.12.7-1+jammy1) ...
dpkg: error processing archive /var/cache/apt/archives/python3.12_3.12.8-1+jammy1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/python3.12', which is also in package python3.12-minimal 3.12.7-1+jammy1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../libpython3.12-stdlib_3.12.8-1+jammy1_amd64.deb ...
Unpacking libpython3.12-stdlib:amd64 (3.12.8-1+jammy1) over (3.12.7-1+jammy1) ...
dpkg: error processing archive /var/cache/apt/archives/libpython3.12-stdlib_3.12.8-1+jammy1_amd64.deb (--unpack):
 trying to overwrite '/etc/python3.12/sitecustomize.py', which is also in package libpython3.12-minimal:amd64 3.12.7-1+jammy1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../python3.13_3.13.1-1+jammy1_amd64.deb ...
Unpacking python3.13 (3.13.1-1+jammy1) over (3.13.0-1+jammy1) ...
dpkg: error processing archive /var/cache/apt/archives/python3.13_3.13.1-1+jammy1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/python3.13', which is also in package python3.13-minimal 3.13.0-1+jammy1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../libpython3.13-stdlib_3.13.1-1+jammy1_amd64.deb ...
Unpacking libpython3.13-stdlib:amd64 (3.13.1-1+jammy1) over (3.13.0-1+jammy1) ...
dpkg: error processing archive /var/cache/apt/archives/libpython3.13-stdlib_3.13.1-1+jammy1_amd64.deb (--unpack):
 trying to overwrite '/etc/python3.13/sitecustomize.py', which is also in package libpython3.13-minimal:amd64 3.13.0-1+jammy1
No apport report written because MaxReports is reached already
                                                              dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/python3.12_3.12.8-1+jammy1_amd64.deb
 /var/cache/apt/archives/libpython3.12-stdlib_3.12.8-1+jammy1_amd64.deb
 /var/cache/apt/archives/python3.13_3.13.1-1+jammy1_amd64.deb
 /var/cache/apt/archives/libpython3.13-stdlib_3.13.1-1+jammy1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

### os information
Ubuntu 22.04.5 LTS

#### lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

#### uname -a

```
Linux m-nxrock-ng 6.8.0-49-generic #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
search the issue tracker and read pinned issues
