### ISSUE TITLE
missing headers in python 3.6installed in ubuntu 16.04 

### ISSUE THREAD

**Issue by bhaskar-manguluri** [deadsnakes/issues#60]
### description

python headers may be missing if installing python3.6 , unable to compile bcolz using this

### os information
ubuntu 16.04

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

```
# paste the output of `uname -a` here
```
Linux tf2 4.13.0-1011-azure #14-Ubuntu SMP Thu Feb 15 16:15:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by asottile** [comment]
Did you install python3.6-dev?

**Comment by bhaskar-manguluri** [comment]
Thank you, I Installed python3.6 earlier now I installed python3.6-dev and issue is resolved.
