### ISSUE TITLE
python3.7: _ssl module is not properly built (trusty)

### ISSUE THREAD

**Issue by asottile** [deadsnakes/issues#63]
### description

```
root@68e07e991d36:/# python3.7 -c 'import ssl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
```

#### lsb_release -a

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

#### uname -a

```
# uname -a
Linux 68e07e991d36 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I suspect when I backported this I forgot to change the libssl dependency

**Comment by asottile** [comment]
This commit requires openssl 1.0.2, whereas trusty ships with 1.0.1: https://github.com/python/cpython/commit/61d478c71c5341cdc54e6bfb4ace4252852fd972

**Comment by fkrull** [comment]
Options I see:

1. Try to find some PPA with OpenSSL 1.0.2 for trusty. But telling people to replace their system OpenSSL with a version from some sketchy PPA is... not great, IMO.
2. Revert the commit. Not great either. In fact, I think I've backported newer versions of difficult modules, but I don't think I've reverted significant functionality before.
3. Stop offering 3.7 (and newer, I suppose) for trusty. It's already "oldoldlts" now.
4. Offer 3.7 without ssl (and hashlib I guess)?

I'm in favour of 3. Taking bits out of _ssl seems messy, difficult, and like an ongoing maintenance burden. I don't think it's worth it.

**Comment by asottile** [comment]
A few dates that might also factor into what I decide to do here:

- June 2018 3.7.0 final
- April 2019 (trusty EOL)
- October 2019 3.8.0 final

Thoughts:
- I definitely agree that `1.` is not something I want to do
- `4.` is what's happening now
- `2.` would only need to be built for ~10 months -- might not be the easiest but probably doable

**Comment by asottile** [comment]
Yeah this is the same issue.  It's not that I don't want to fix this, there just isn't a good way that plays nice with the ecosystem, the two "fix" options are essentially:
- revert this part of 3.7 (now it's not really 3.7 any more)
- backport libssl and sign up for security fixes against that (don't want to deal with debian conflicts / etc. here)

**Comment by pekkaklarck** [comment]
Is it feasible to compile 3.7 separately for trusty? If yes, I'd say using OpenSSL 1.0.1 on trusty would be fine, even if it would mean that version isn't 100% compatible with 3.7 on other platforms. That would be a lot better than the current situation and would avoid spending a lot of time to support an OS that's about to be EOL'd quite soon. Practicality beats purity.

**Comment by asottile** [comment]
All compiles are done separately already, the support for openssl 1.0.1 has been **_removed_** from the cpython sources for python3.7, in order to make cpython compile against 1.0.1 I would have to make a deadsnakes-specific patch to revert that change which I'm not comfortable with.

The patch in question that would have to be reverted is https://github.com/python/cpython/commit/61d478c71c5341cdc54e6bfb4ace4252852fd972 (which also would revert at least one fix / feature from what I can tell from the bpo link)

**Comment by pekkaklarck** [comment]
I see. Missing features that 3.7 has on other platforms would be fine (at the moment the whole ssl module is missed), but loosing functionality that older versions have is a different topic, especially when we are talking about security stuff here.

It's unfortunate Ubuntu devs decided not to officially backport OpenSSL 1.0.2 to Trusty. I'm fine using PPAs for some software, but not really for crypto. I think I'll just forget about 3.7 until I got time to re-install my laptop.

**Comment by asottile** [comment]
closing: trusty is end-of-lifed (wontfix)

**Comment by thuannt-uit** [comment]
I tried to use python 3.6, it's work ok

**Comment by asottile** [comment]
@thuannt-uit well of course, the title says "3.7" not "3.6"
