### ISSUE TITLE
Any chance to get armhf builds for Ubuntu PPAs? 

### ISSUE THREAD

**Issue by alc6379** [deadsnakes/issues#64]
### description

I'm running Armbian on an ODROID Hardkernel XU4 Singleboard computer. Armbian is based off of Xenial and only includes Python 3.5.1. I need >3.6 to run some of the applications I'm looking to run. Is there any chance that this might happen? Or will I just need to build the package myself? I was hoping to take advantage of all the work that has been done already with stuff like python3.6-venv, etc. 

### os information

Armbian on ODROID Hardkernel XU4 (Based on Xenial)

#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

```

#### uname -a

```
Linux odroid 4.9.61-odroidxu4 #2 SMP PREEMPT Wed Nov 22 16:34:23 CET 2017 armv7l armv7l armv7l GNU/Linux

```

**Comment by asottile** [comment]
You should be able to take our existing sources and build them -- unfortunately building anything more than x86_64 and 386 would cause us to go over our ppa quota.

For building, there's instructions [here](https://github.com/deadsnakes/docs/wiki/Building-Deadsnakes-Packages-from-Git)

Or if you have access to `docker`, there's a ~slightly simpler build [here](https://github.com/deadsnakes/runbooks#building-a-package)

**Comment by fkrull** [comment]
Wait, you can just enable more architectures for any PPA? Sweet, I didn't know that! We should try that.

The space quota isn't an issue. You just ask: https://answers.launchpad.net/launchpad/+question/668674 (the old PPA had a 10GB quota).

**Comment by asottile** [comment]
Yep! you can change which architectures are built from the `Change details` page.  Checkboxes!

![](https://i.fluffy.cc/Tsc7szs4wp0cCnZTxFPbmBkQBG9HK9Wq.png)

**Comment by cjwatson** [comment]
Note that you don't in general need to do a new source upload after enabling new architectures in a PPA, but you do need to trigger the builds somehow.  A somewhat undocumented but handy method of doing this is to use the "Copy packages" UI to copy the relevant source package(s) to the same destination PPA and series, selecting the "Include existing binaries" option; this is a no-op for the architectures that have already built, but has the effect of triggering builds for any configured but missing architectures.

**Comment by alc6379** [comment]
> You should be able to take our existing sources and build them -- unfortunately building anything more than x86_64 and 386 would cause us to go over our ppa quota.

Thanks-- that's what I actually wound up doing, but it took about an hour and a half to build, even on the fairly stout XU4 board. I tried cross-compiling on an x64 machine, but that was a major headache. 

I'd like to track this PPA for armhf, if possible, so I thought maybe having them pre-built would be a big time saver. Thanks again for the response!

**Comment by asottile** [comment]
@alc6379 yep, we're going to try and start supporting more architectures here -- I'll try the above procedure once I have some freetime to watch the builds :)

**Comment by fkrull** [comment]
3.6 and 3.7 for xenial now have armhf versions. Any future uploads will also be built for armhf and arm64. @alc6379 Could you try the packages and report if they work

**Comment by alc6379** [comment]
Will do! I'll give it a shot here pretty soon. I'll need to uninstall the version I built myself. Once I get that done, I'll give it a shot.

Thanks for being on top of this!

**Comment by asottile** [comment]
I've clicked the button for all of our existing packages, closing this out now!

**Comment by fkrull** [comment]
As a record of things that don't work:
* 3.1 on armhf on xenial fails to build for... reasons I can't figure out.
* 3.2 is incompatible with arm64, apparently it doesn't use the *64 version of a syscall. Could be patched, I suppose.

These are all old, so I'm not too bothered personally.
