### ISSUE TITLE
Python 2.3, 2.4, 2.5, 2.6, 3.1, 3.2 and 3.3 

### ISSUE THREAD

**Issue by vijayreddy1991** [deadsnakes/issues#65]
### description

Python environment varibles is not working for this 2.3, 2.4, 2.5, 2.6, 3.1, 3.2 and 3.3 versions

### os information

Ubuntu 14.04
#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```
# paste the output of `uname -a` here
```

**Comment by fkrull** [comment]
Could you provide some more information? What exactly is not working? Which environment variables are you referring to?

**Comment by asottile** [comment]
@vijayreddy1991 they appear to be working for me, could you provide more information?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
$ python2.6
Python 2.6.9 (default, Jul 29 2017, 12:51:50) 
[GCC 4.8.4] on linux4
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import subprocess
>>> os.environ['HELLO'] = 'WORLD'
>>> retv = subprocess.check_call(('bash', '-c', 'echo $HELLO'))
WORLD
```

**Comment by asottile** [comment]
tentatively closing this, if you get more information @vijayreddy1991 please add it here and I can reopen!
