### ISSUE TITLE
python3.7, xenial: ModuleNotFoundError: cmath

### ISSUE THREAD

**Issue by MilosLukic** [deadsnakes/issues#68]
When installing python3.7 using deadsnakes repo the cmath module was missing.

https://stackoverflow.com/questions/51707435/python-3-7-cmath-module-import-error/51707874#51707874

**Comment by asottile** [comment]
Thanks for the report!  It appears to be there for me on `bionic`:

```
$ python3.7 -c 'import cmath'
$ dpkg -S /usr/lib/python3.7/lib-dynload/cmath.cpython-37m-x86_64-linux-gnu.so
libpython3.7-stdlib:amd64: /usr/lib/python3.7/lib-dynload/cmath.cpython-37m-x86_64-linux-gnu.so
```

What distribution are you using? (please fill out the [issue template](https://github.com/deadsnakes/issues/blob/master/.github/ISSUE_TEMPLATE.md) next time! it really helps in triaging!)

**Comment by asottile** [comment]
There were no changes to the `cmath` module between 3.6 and 3.7 -- perplexing.  Also the build succeeded on i386 -- maybe it was a flake? I'm going to try re-uploading

**Comment by asottile** [comment]
`_cmath.c` / `_cmath.h` changed a bit between 3.6.6 and 3.7.0 however.  And the compile line changed:

```
x86_64-linux-gnu-gcc -pthread -c -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers  -IObjects -IInclude -IPython -I. -I../Include -D_FORTIFY_SOURCE=2   -DPy_BUILD_CORE -o Modules/_math.o ../Modules/_math.c
```

```
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fprofile-generate -IObjects -IInclude -IPython -I. -I../Include -Wdate-time -D_FORTIFY_SOURCE=2    -c ../Modules/_math.c -o Modules/_math.o
```

**Comment by asottile** [comment]
Reverting the patches between 3.6.6 and 3.7.0 doesn't fix this either, going to see if upstream handles this in some way

**Comment by asottile** [comment]
I've just uploaded a fix (3.7.0-1+xenial2) -- this should contain [this fix](https://github.com/deadsnakes/python3.7/commit/5f22e97fb7633f3f017429fdef4e6e83578131a9).

It'll take 20-30 minutes for that to be available -- I'll double check once it completes.

**Comment by asottile** [comment]
calling this fixed!

```console
$ python3.7 -c 'import cmath'
$ grep DISTRIB_CODENAME /etc/lsb-release 
DISTRIB_CODENAME=xenial
$ dpkg -l | grep -P '\spython3.7\s'
ii  python3.7                                   3.7.0-1+xenial2                              amd64        Interactive high-level object-oriented language (version 3.7)
```

**Comment by webknjaz** [comment]
@asottile same issue reoccured with `3.7.2-1+xenial1` now
