### ISSUE TITLE
Travis CI installation of Python 3.7 fails because of unauthenticated packages

### ISSUE THREAD

**Issue by YannickJadoul** [deadsnakes/issues#69]
### description

Following [the instructions to install Python 3.7 on Travis CI](https://github.com/deadsnakes/travis-ci-python3.7-example), the apt-get installation fails with the following error message (from today; a few days ago, this was working like a charm):

```
WARNING: The following packages cannot be authenticated!
  libpython3.7-minimal python3.7-minimal libpython3.7-stdlib libpython3.7
  libpython3.7-dev python3.7-lib2to3 python3.7-distutils python3.7
  python3.7-dev python3.7-venv
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

See e.g., https://travis-ci.org/YannickJadoul/Parselmouth/builds/422575571

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

#### uname -a

```
Linux travis-job-cbba60f3-86d4-472a-b9f6-d6124deec642 4.15.0-1014-gcp #14~16.04.1-Ubuntu SMP Thu Jul 19 09:46:30 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
Thanks for the issue! Seems travis-ci must have changed how they install `apt` packages -- I've updated the documentation with a new approach that works!

**Comment by YannickJadoul** [comment]
Thank you for the quick response, even easier to use, now! :-)
