### ISSUE TITLE
Install without system Python

### ISSUE THREAD

**Issue by ipmb** [deadsnakes/issues#71]
### description

Is it possible to install a version from deadsnakes without also pulling in the system Python? Installing 3.7 on bionic requires installing 3.6 as well.

```
# apt-get install -y --no-install-recommends python3.7
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libexpat1 libmpdec2 libpython3-stdlib libpython3.6-minimal
  libpython3.6-stdlib libpython3.7-minimal libpython3.7-stdlib libreadline7
  libsqlite3-0 libssl1.1 mime-support python3 python3-distutils
  python3-lib2to3 python3-minimal python3.6 python3.6-minimal
  python3.7-minimal readline-common
```

#### lsb_release -a

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

#### uname -a

```
Linux 02415f15ab15 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
It's probably from => python3-distutils => python3 if I had to guess. Not at a computer but I'd poke at rdepends and figure out why it gets pulled in. The packaging of distutils / lib2to3 is unfortunate since we depend on upstream's packages (and we shadow upstream's python3.7 package)

**Comment by ipmb** [comment]
Yes,

```
# apt-cache show python3.7 | grep -i depends
Depends: python3.7-minimal (= 3.7.0-1+bionic2), libpython3.7-stdlib (= 3.7.0-1+bionic2), python3-distutils, mime-support
Depends: python3.7-minimal (= 3.7.0~b3-1), libpython3.7-stdlib (= 3.7.0~b3-1), mime-support
# apt-cache show python3-distutils | grep -i depends
Depends: python3 (>= 3.6.4-1~), python3 (<< 3.8), python3-lib2to3 (>= 3.6.4)
```

Is publishing a `python3.7-distutils` a possibility?

I'd like to use your PPA in a Docker image where the expense of installing an extra Python, both in terms of time and size is noticeable.

**Comment by asottile** [comment]
Unfortunately I think (?) our hands are tied here as those files would collide with the upstream packages

**Comment by ipmb** [comment]
Yes, I understand. Strange decision upstream to include both 3.6/3.7 in the same package.

**Comment by asottile** [comment]
You _could_ purge the files after the fact with something like `dpkg -L python3.6 | xargs rm -rf` -- not necessarily recommended though :)
