### ISSUE TITLE
python3.7 sets LC_CTYPE=C.UTF-8 in environment

### ISSUE THREAD

**Issue by agriffis** [deadsnakes/issues#72]
### description

python3.7 sets `LC_CTYPE=C.UTF-8` in environment. Is this leaking from a build process?

```
root@1953601fb6fc:/# env
HOSTNAME=1953601fb6fc
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
_=/usr/bin/env

root@1953601fb6fc:/# python3.7
Python 3.7.0 (default, Aug  6 2018, 20:07:46) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['LC_CTYPE']
'C.UTF-8'
```

### os information

ubuntu xenial (from docker):

```
docker run -it ubuntu:xenial
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

#### uname -a

```
Linux 1953601fb6fc 4.17.18-200.fc28.x86_64 #1 SMP Wed Aug 22 19:08:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
Note that you're not actually using the deadsnakes python3.7 in the linked commit.

This is a new side-effect of [PEP 540](https://www.python.org/dev/peps/pep-0540/), a python3.7 language feature

**Comment by asottile** [comment]
and/or [PEP 538](https://www.python.org/dev/peps/pep-0538/) -- I always mix up the two and forget which one covers the `LC_CTYPE` part

**Comment by agriffis** [comment]
@asottile Thanks, I thought that Travis was using deadsnakes for its python3.7 build, but I'm probably wrong. I partly based that assumption on the common presence of setting `LC_CTYPE` ;-)

Appreciate the PEP pointers!

**Comment by asottile** [comment]
🎉 no problem! Thanks for the issue nonetheless :D
