### ISSUE TITLE
Ubuntu 18.10 support?

### ISSUE THREAD

**Issue by naquiroz** [deadsnakes/issues#73]
Hi, I'm trying to use the ppa with ubuntu 18.10 but it fails to find repository information. Is there a way to make it work?

**Comment by asottile** [comment]
We currently only provide releases for LTS versions. You might be able to add the bionic repo under cosmic, mileage may vary (I can give more concrete directions when I'm at a computer). Another option is to rebuild our source packages

**Comment by naquiroz** [comment]
Oh, sad, didnt knew this, I guess I'll stick with alternative instalation methods then, thanks!

**Comment by GhostofGoes** [comment]
It works on 18.10 with Python 3.4. Just change "cosmic" to "bionic" in `/etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-cosmic.list`, then `sudo apt update`.
