### ISSUE TITLE
3.7.1 for Trusty missing

### ISSUE THREAD

**Issue by LaughDonor** [deadsnakes/issues#74]
Seems like this package was looked over when updated yesterday. Could this get an update too, please?

When I built via source, I ended up having to update gcc from 4.8 to 5.0 to get it to build (with optimizations). Not sure if this helps.

Thanks!

**Comment by asottile** [comment]
I've stopped uploading new trusty builds due to https://github.com/deadsnakes/issues/issues/63 -- I guess I can continue to maintain the branch but the packages it produces will always be broken due to trusty only having ancient libssl

**Comment by LaughDonor** [comment]
Interesting. I'm new at this sort of thing, but since you'd be creating a package, could you set the dependency to use `libssl 1.0.2+`?

**Comment by asottile** [comment]
ubuntu trusty is too old and doesn't have a libssl 1.0.2+ package.  I could set that, but then it would invariably fail to build

**Comment by asottile** [comment]
The current build is a "successful build" but missing the modules that need `libssl` (`ssl`, `hashlib`, a few others)

**Comment by asottile** [comment]
@LaughDonor would you like me to apply the patches to the trusty branch or am I ok to close this?

**Comment by LaughDonor** [comment]
Please apply the patches so they are available. Thanks!

**Comment by asottile** [comment]
I've pushed the patches up for trusty, I didn't release to launchpad since it's _still_ a broken package
