### ISSUE TITLE
Newer patch releases for 3.4 and 3.5 available

### ISSUE THREAD

**Issue by funkyfuture** [deadsnakes/issues#81]
### description

There are the 3.4.10 and the 3.5.10 releases available that have not been published in the repo. Is there a way to help with updates?

on this occassion: as the repository now spans from obsolete to future releases, wouldn't it be consistent to include 2.7 as well?

**Comment by asottile** [comment]
woops, forgot to publish the new python3.4 / python3.5 versions -- I should be able to get to those soon

we don't publish versions for which the distribution also publishes a version.  Presumably 20.04 won't ship with python2.7 and then we'll pick up a package for that? (unclear)

**Comment by funkyfuture** [comment]
i noticed that at least Ubuntu isn't providing packages as quickly as you are. weirdly, Bionic currently installs 2.7.15-rc1.

**Comment by asottile** [comment]
> i noticed that at least Ubuntu isn't providing packages as quickly as you are. weirdly, Bionic currently installs 2.7.15-rc1.

they tend to freeze the version and backport security patches without changing the version.  python frequently ships features / breaks even with "patch" version bumps :sob:

**Comment by funkyfuture** [comment]
aha, thanks for the explanation.

**Comment by asottile** [comment]
I've  uploaded the newer 3.4 / 3.5 patch release -- they should be available within an hour or so -- thanks again for the issue!
