### ISSUE TITLE
Python 3.8 : ModuleNotFoundError: No module named 'distutils.util' using Ubuntu 18 image

### ISSUE THREAD

**Issue by thirtytwobits** [deadsnakes/issues#82]
### description

I'm building a docker container from ubuntu:18.04 with python 3.5, 3.6, 3.7, and 3.8 installed (this is for tox testing). I'm using your ppa to install all of these (thanks for maintaining it!) but when I try to use (or install) pip using the 3.8 version I get `ModuleNotFoundError: No module named 'distutils.util'`. Is the python 3.8 distro broken? 

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

#### uname -a

```
Linux f21c2ed4de51 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
Upstream debian has split several standard library modules from the default installation.  One of those is the `distutils` module (lib2to3, tkinter, gdbm, venv, test are some of the others)

To get `distutils.util`, install `python3.8-distutils` package as well

**Comment by stdedos** [comment]
@asottile would it be okay to add that note somewhere?

> You should run `sudo apt-get install python3.8 python3.8-venv python3.8-distutils` to get a "full" python 3.8 env

or equivalent?

**Comment by asottile** [comment]
you'd also need python3.8-dev, python3.8-gdbm, python3.8-tk, python3.8-lib2to3, and idle-python3.8 but I don't think most people want/need those packages

Maybe something more vague like "these packages are based on the debian upstream so (for instance) distutils and venv (among others) are in separate packages (pythonX.X-distutils / pythonX.X-venv)"?

**Comment by stdedos** [comment]
+1 on the `dev` (I ended up needing it) 

I came here from the error message (not the OP's package that caused the error); so, my issue was resolved purely with my aforementioned packages (+`dev`). 

Your call on the "correct message". Anything that would help us the "semi-ignorant" users that add a ppa to just leverage the benefits.

It's just that starting a venv has multiple levels of trial-and-error, that many of them are not so clear.

**Comment by asottile** [comment]
yeah I wish debian didn't do things the way they do :'(

**Comment by asottile** [comment]
I added this to the PPA page, lmk what you think:

```markdown
Packages
========

The packages provided here are loosely based on the debian upstream packages with some modifications to make them more usable as non-default pythons and on ubuntu. As such, the packages follow debian's patterns and often do not include a full python distribution with just `apt install python#.#`. Here is a list of packages that may be useful along with the default install:

- `python#.#-dev`: includes development headers for building C extensions
- `python#.#-venv`: provides the standard library `venv` module
- `python#.#-distutils`: provides the standard library `distutils` module
- `python#.#-lib2to3`: provides the `2to3-#.#` utility as well as the standard library `lib2to3` module
- `python#.#-gdbm`: provides the standard library `gnu.dbm` module
- `python#.#-tk`: provides the standard library `tkinter` module
```

**Comment by stdedos** [comment]
I'd kindly ask you to add 
```gfm
- `python#.#-venv`: provides the standard library `venv` module (requires `python#.#-distutils`)
```

Or just force it on the packaging (`depends-on`, `requires` or whatever comes from `debian/rules`).

I mean, I am "fairly confident"[1] you *cannot* fully initialize a `venv` on 3.8 (and maybe other versions?).

* What are the Ubuntu's `py3.5-venv` dependencies? I don't see https://packages.ubuntu.com/xenial/python3.5-venv requiring it (or https://packages.ubuntu.com/xenial/python3-venv), but I (probably) have it installed?
* Or `distutils` was split `>3.5`[2]?

[^1]: It seems as `python3-venv` aka `python3.7-venv` on `buster` requires it: https://packages.debian.org/buster/python3-venv
[^2]: Stretch `python3-venv` (aka `python3.5-venv`) didn't require it https://packages.debian.org/stretch/python3-venv

**Comment by asottile** [comment]
oh if the packaging dependencies are broken I'll just fix those 👍

**Comment by stdedos** [comment]
I didn't know it until I digged it 😄 (as I don't do Debian)

**Comment by asottile** [comment]
alrighty!  I've done this for:

- [python3.7](https://github.com/deadsnakes/python3.7)
- [python3.8](https://github.com/deadsnakes/python3.8)
- [python3.7-nightly](https://github.com/deadsnakes/python3.7-nightly) (this will get pushed when the next cron fires)
- [python3.8-nightly](https://github.com/deadsnakes/python3.8-nightly)  (this will get pushed when the next cron fires)
- [python3.10](https://github.com/asottile/python3.10)

**Comment by Mrshahhaxor** [comment]
While i Click on : python3 HiddenEye.py

it gives an Error :

Traceback (most recent call last):
File "HiddenEye.py", line 7, in
from Defs.Actions import *
File "/home/mrshah/HiddenEye/Defs/Actions.py", line 6, in
from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils.dir_util'


Also had tried to install : sudo apt install python3-distutils

While I Enter the : sudo apt install python3-distutils

it says :
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 70393 (apt-get)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

Also installed the new version of HiddenEye from https://github.com/DarkSecDevelopers/HiddenEye link still have the same problem

**Comment by stdedos** [comment]
> While I Enter the : sudo apt install python3-distutils
> 
> it says :
> E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 70393 (apt-get)
> N: Be aware that removing the lock file is not a solution and may break your system.
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

Note that this ^^^ is your problem. If you don't know how to fix it, restart your computer - and then, and only then, to `sudo rm /var/lib/dpkg/lock`

**Comment by taiya** [comment]
FYI, the following `sudo apt-get install python3.8 python3.8-venv python3.8-distutils`
Does not work for `Debian 5.10.26-1rodete1 (2021-04-12) x86_64 GNU/Linux`:

```
~/bin: sudo apt-get install python3.8 python3.8-venv python3.8-distutils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.8-distutils
E: Couldn't find any package by glob 'python3.8-distutils'
E: Couldn't find any package by regex 'python3.8-distutils'
```

**Comment by asottile** [comment]
@taiya ubuntu deadsnakes is an **UBUNTU** ppa and not associated with debian

**Comment by zelifcam** [comment]
```
python3.8-distutils is missing.

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"

sudo apt-get install python3.8 python3.8-venv python3.8-distutils
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.8-distutils
E: Couldn't find any package by glob 'python3.8-distutils'
E: Couldn't find any package by regex 'python3.8-distutils
```

**Comment by asottile** [comment]
on 18.04 the package which contains python3.8 distutils sources is called `python3-distutils`
