### ISSUE TITLE
python3.6 - installing to debian

### ISSUE THREAD

**Issue by fraser-lowndes** [deadsnakes/issues#83]
### description

I'm trying to install the python3.6 package to my debian stretch machine.

I started with `add-apt-repository ppa:deadsnakes/ppa` which tried to install the `disco` version (I don't think this is supported): `Failed to fetch http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/dists/disco/main/binary-amd64/Packages  404`

So I manually added the line `deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu trusty main` to my `/etc/apt/sources.list`:

Now when I do `apt-get update; apt-get install python3.6` I get the error:

```
The following packages have unmet dependencies:
 python3.6 : Depends: python3.6-minimal (= 3.6.8-1+trusty1) but it is not going to be installed
             Depends: libpython3.6-stdlib (= 3.6.8-1+trusty1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
If I try to manually install the dependency `python3.6-minimal=3.6.8-1+trusty1` and its dependency `libpython3.6-minimal=3.6.8-1+trusty1` I get the error

```
The following packages have unmet dependencies:
 libpython3.6-minimal : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
                        Recommends: libpython3.6-stdlib but it is not going to be installed
```
And now I'm stumped, not sure if I need to install `libssl1.0.0` or if I have done something totally wrong from the beginning. I have also tried these steps using `xenial` instead of `trusty`. Any advice appreciated.

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch
```
#### uname -a

```
Linux *** 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```

**Comment by asottile** [comment]
for stretch I'd suggest instead of trusty (14.04) use xenial (16.04) or bionic (18.04) as they're more likely to have compatible packages to stretch (released in 2017)

fwiw, installing against different debians isn't really supported though it _may_ work in some cases.  You may have better luck rebuilding the deadsnakes source packages on debian however (that's how, for instance [ocf/python3.7-deb](https://github.com/ocf/python3.7-deb) works)

**Comment by fraser-lowndes** [comment]
Thanks for the reply @asottile, I tried xenial & bionic but had similar / same issues. Guess I will just build 3.6 myself, spent far too much time on this now.

**Comment by asottile** [comment]
Let me know if you'd like help rebuilding this for debian -- happy to assist there :)

**Comment by ankostis** [comment]
What (effort, people, cost) would it take to add repos also for Debian-releases `focal`, `buster,, `stretch` (maybe `jessie`)?

**Comment by asottile** [comment]
`focal` is an ubuntu release which is already provided.

for debian, it's a matter of rebuilding the sources and maintaining them somewhere -- if you need this for your company you could potentially contract someone to do this (I don't have the time to do that for free and/or host it for free)

**Comment by ankostis** [comment]
This is not for a company. I could offer some time, though i don't have experience on maintaining an apt-repo.  And what about hosting?  What are the costs involved?

**Comment by asottile** [comment]
hard to say, launchpad is free but is ubuntu specific

**Comment by ankostis** [comment]
For anyone arriving at this issue, this is an unofficial repository for back/forward-ported python for (yet?) x2 Debian releases, buster & strech:
https://people.debian.org/~paravoid/python-all/
