### ISSUE TITLE
Ubuntu 19.04

### ISSUE THREAD

**Issue by marcelm** [deadsnakes/issues#84]
Whenever I upgrade, I forget how heavily I rely on the deadsnakes packages, and that they only work on LTS releases. I’m now at Ubuntu 19.04 and the trick of changing `disco` to `bionic` [as described in issue 73](https://github.com/deadsnakes/issues/issues/73#issuecomment-468879002) does not work.

Here is what I’ve tried:
```
$ sudo apt install python3.5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3.5 : Depends: libpython3.5-stdlib (= 3.5.7-1+bionic1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Then:
```
$ sudo apt install libpython3.5-stdlib
...
The following packages have unmet dependencies:
 libpython3.5-stdlib : Depends: libreadline7 (>= 7.0~beta) but it is not installable
```
As I said, I understand that you only support LTS releases, but I thought I would ask anyway in case there is an easy workaround that I’m missing.

**Comment by asottile** [comment]
If using the incompatible versions doesn't end up working I'm afraid you'll need to rebuild from source. If you have docker available there's some helpers in github.com/deadsnakes/runbook (and minimal directions, sorry I could probably document those better)

**Comment by fkrull** [comment]
@marcelm In this particular case, the problem is that libreadline7 was [removed in disco](https://packages.ubuntu.com/search?keywords=libreadline7&searchon=names&suite=all&section=all) (I guess because it wasn't used by anything any more). If you're feeling adventurous, you could try installing the cosmic .deb for that and see if that's enough.

If it's not, though, you're probably better off building from source lest you end up in forward-porting hell; which is a place about as unpleasant as the name suggests.

**Comment by asottile** [comment]
more specifically, it looks like it's now `libreadline8`: https://packages.ubuntu.com/search?keywords=libreadline8&searchon=names&suite=all&section=all

**Comment by marcelm** [comment]
Ok, thanks for the replies! I managed to install the libreadline7 .deb manually and was then able to install (and use) the deadsnakes packages for python3.4 and python3.5. Now I still don’t have Python 3.6 because you don’t package it for bionic, but it’s now good enough for me.

I won’t try to rebuild from source at the moment, but thanks for the pointer to the documentation. Perhaps I’ll try this later.

Thanks again! (Feel free to close.)

**Comment by asottile** [comment]
cheers! 🎉
