### ISSUE TITLE
Missing GPG key

### ISSUE THREAD

**Issue by fungs** [deadsnakes/issues#86]
On Ubuntu 18.04 adding PPA succeeds but no GPG key can be imported.

```
Executing: /tmp/apt-key-gpghome.j9yocqjMEL/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys F23C5A6CF475977595C89F51BA6932366A755776
apt update
gpg: Empfangen vom Schlüsselserver fehlgeschlagen: Server zeigt einen unbestimmten Fehler an
```

None of the keyservers I tried have the key with this ID.

**Comment by asottile** [comment]
seems there to me ?

```console
$ docker run --rm -ti ubuntu:bionic bash
root@4debb298e1c1:/# apt-get update -qqq && apt-get install gnupg2 -qqq

...

root@4debb298e1c1:/# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F23C5A6CF475977595C89F51BA6932366A755776
Executing: /tmp/apt-key-gpghome.2pO2wpdjGU/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F23C5A6CF475977595C89F51BA6932366A755776
gpg: key BA6932366A755776: public key "Launchpad PPA for deadsnakes" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by fungs** [comment]
Sorry for the false alarm! I also checked using web interface to keyserver but missed the hex encoding part.

It works with hkp:// protocol and specific port 80 setup.

I use the Mint Ubuntu derivative and the corresponding code is

    /usr/lib/linuxmint/mintSources/mintSources.py:160: subprocess.call(["apt-key", "adv", "--keyserver", "keyserver.ubuntu.com", "--recv-keys", ppa_info["signing_key_fingerprint"]])

I tested this on plain old Ubuntu 16.04 and it works even without protocol and port settings.

I will test other PPAs, but I believe this is a distribution bug at the moment.

**Comment by asottile** [comment]
sounds good -- thanks for the issue!

**Comment by KarsonTheFoxx** [comment]
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F23C5A6CF475977595C89F51BA6932366A755776
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.tohAdKLYK7/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F23C5A6CF475977595C89F51BA6932366A755776
gpg: key BA6932366A755776: public key "Launchpad PPA for deadsnakes" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no writable keyring found: Not found
gpg: error reading '[stdin]': General error
gpg: import from '[stdin]' failed: General error
gpg: Total number processed: 0

im having trouble with the keyring it seems, using `sudo add-apt-repository ppa:deadsnakes/ppa returns a GPD key error wiuth the following message
no valid OpenPGP data found.

**Comment by asottile** [comment]
"`gpg: no writable keyring found: Not found`" -- that's an issue on your end, the key was downloaded properly before that: ` gpg: key BA6932366A755776: public key "Launchpad PPA for deadsnakes" imported`
