### ISSUE TITLE
PIP missing in Python 3.7 under Ubuntu 16.04

### ISSUE THREAD

**Issue by ullix** [deadsnakes/issues#87]
### description
Python 3.7.3 was installed from the PPA into Ubuntu 16.04 and it went alongside Python2.7 and Python3.5; both originally installed via apt.

Python3.7 can be called with python3.7 and it works, but I there is no command for pip its, though it seems to be installed at ~/.local/lib/python3.7/site-packages

### os information
Ubuntu 16.04

#### lsb_release -a

```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

```

#### uname -a

```
Linux crucialmx200 4.15.0-51-generic #55~16.04.1-Ubuntu SMP Thu May 16 09:24:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by asottile** [comment]
`~/.local` is from ` pip install --local` and not from files we package. You're correct in that the package does not contain pip, this is consistent with how Debian packages it.

If you install `python3-pip` you can usually use `python3.7 -mpip ... `  however I would strongly suggest using a virtualenv
