### ISSUE TITLE
python 3.7.2 package

### ISSUE THREAD

**Issue by mikebrook** [deadsnakes/issues#90]
### description

can we add python 3.7.2 back? Or this is only for latest versions?

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```
# paste the output of `uname -a` here
```

**Comment by asottile** [comment]
Unfortunately we can only include one version per package -- you can rebuild from the tagged sources if you need an older version -- for example, here's the 3.7.2 xenial tag: https://github.com/deadsnakes/python3.7/releases/tag/debian%2F3.7.2-1%2Bxenial2

**Comment by asottile** [comment]
hope that answers your question -- thanks again for the issue!
