### ISSUE TITLE
Provide virtual package python3

### ISSUE THREAD

**Issue by sveniu** [deadsnakes/issues#93]
### description

Feature request: Please make python3.x packages provide the virtual package `python3`. (Similar for python2.x packages, I take it.)

This would make the python3.x package satisfy the `python3:any` dependency of many packages, notably `python3-pip` on Ubuntu.

Current behaviour: Install python3-pip, and it pulls in python3.5.

Wanted behaviour: Install python3-pip, and it uses the already-installed python3.6 from deadsnakes.

#### lsb_release -a

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

#### uname -a

```
Linux 38a36af00dae 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
I cannot add it is provided by the upstream and these are not replacements for the system python

I'd suggest using the qualified name, a prefixed PATH, or a virtualenv
