### ISSUE TITLE
Does this ppa interfere with upstream packages? Ie Python 3.7 on Ubuntu 18.04

### ISSUE THREAD

**Issue by jugmac00** [deadsnakes/issues#94]
### description

I am running Ubuntu 18.04 (Dell XPS flavor)  and currently have Python 2.7, 3.6 and 3.7 installed via apt, without adding a ppa.

I'd like to have Python 3.8 installed, but I am unsure about adding this ppa will interfere with the already installed Python 3.7.

From **https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa**

> Note: Python2.7 (both), Python 3.5 (xenial), Python 3.6 (bionic) are not provided by deadsnakes as upstream ubuntu provides those packages.

Any advice how to proceede?

Thank you!

```
$ apt-cache policy python3.7
python3.7:
  Installed: 3.7.3-2~18.04.1
  Candidate: 3.7.3-2~18.04.1
  Version table:
 *** 3.7.3-2~18.04.1 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     3.7.0~b3-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

### os information
Pre-installed Ubuntu 18.04 (Dell XPS 9370)

#### lsb_release -a

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

```

#### uname -a

```
$ uname -a
Linux jugmac00-XPS-13-9370 4.15.0-1057-oem #66-Ubuntu SMP Wed Sep 18 14:20:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by asottile** [comment]
The only package that we provide that ubuntu also provides (currently) is `python3.7` (which we package "in the same spirit" as upstream).  Usually `apt` will pick our package over the `python3.7` package, but they won't conflict.  This shouldn't break things, if it does please file a bug and we'll fix it 👍
