### ISSUE TITLE
installing pip for 3.8 using get-pip.py on 18.04 leaves a broken state

### ISSUE THREAD

**Issue by hjwp** [deadsnakes/issues#95]
### description

* start from an 18.04 base, add deadsnakes ppa
* install python3.8, python3.8-dev, python3.8-venv 
* install pip using `curl https://bootstrap.pypa.io/get-pip.py | python3.8`
* run `python3.8 -m pip freeze` and you see:

```
pygobject==3.26.1
python-apt==1.6.4
unattended-upgrades==0.1
```

* run, eg,  `python3.8 -m pip show unattended-upgrades`  and you'll see they are in `/usr/lib/python3/dist-packages`  <-- these are the python3.6 system-installed packages.

so the python3.8 pip is confused about what its systemwide modules are, which causes confusion downstream if you want to install more systemwide packages for 3.8

### os information

18.04

#### lsb_release -a

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

#### uname -a

```
Linux 615922f0a102 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment]
this is, in fact, correct -- `/usr/lib/python3/dist-packages` are "shared python3 installed distribution packages" (this is how debian sets up this directory -- this is a debian specific quirk)

using that `pip` will install into a 3.8-specific dist-packages directory:

```console
root@e07c2bf7f805:/# python3.8 -m pip install astpretty
Collecting astpretty
  Downloading https://files.pythonhosted.org/packages/16/6c/3814ad265e04ae9cd3fc2bd3b72e80c122adffc3f2b8147d9d2897246d25/astpretty-1.6.0-py2.py3-none-any.whl
Installing collected packages: astpretty
Successfully installed astpretty-1.6.0
root@e07c2bf7f805:/# python3.8 -m pip show astpretty         
Name: astpretty
Version: 1.6.0
Summary: Pretty print the output of python stdlib `ast.parse`.
Home-page: https://github.com/asottile/astpretty
Author: Anthony Sottile
Author-email: asottile@umich.edu
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: 
```

also you generally [shouldn't do that unless you want breakage](https://stackoverflow.com/a/49836753/812183)

I'd strongly suggest not installing _anything_ to the system anyway and utilizing virtualenvs

**Comment by hjwp** [comment]
wow i had no idea you could have packages shared between different versions of python.  thanks anthony.

re: virtualenvs, that had occurred to me of course, but this is for a container, and virtualenvs always feel like overkill in those cases -- the only reason for that containers existence is to run a single python app, so i feel like, why have two separate sets of pythons?

in any case i worked around it using a dirty `--user` install hack. 

thanks again for everything that you do.

**Comment by asottile** [comment]
Even in containers, it's a good idea to separate the system packages (managed by `apt` and such) from your application dependencies (when they conflict all sorts of nasty things can happen!)

I usually do that via:

```dockerfile
ENV PATH=/venv/bin:$PATH
RUN : \
    && virtualenv /venv -ppython3.8 \
    && pip install -r requirements.txt
```

This ensures that `python` and `python3` inside the container _are the virtualenv python_ but allows you to sidestep stomping on any system packages

Hope this helps!

**Comment by hjwp** [comment]
it _does_ help!  i needed to hack `$PATH` anyway to get the `--user` install working, i hadn't thought of hacking it to prefer the virtualenv python, that's genius.  Thanks *again*!

**Comment by geetha324** [comment]
pip file is not installed in python. pip in text format. here i share the file
