### ISSUE TITLE
not able to add python 3.8 in ubuntu 18.04

### ISSUE THREAD

**Issue by zub786** [deadsnakes/issues#96]
when i run the following command:
**sudo add-apt-repository ppa:zubair/python-3.8**

i see the following error:
Cannot add PPA: 'ppa:~zubair@A002-00046/ubuntu/python-3.8'.
ERROR: '~zubair@A002-00046' user or team does not exist.

**Comment by asottile** [comment]
that's not our ppa, for our ppa you'd use:

```
sudo add-apt-repository ppa:deadsnakes
```

**Comment by frakman1** [comment]
Still doesn't work on Ubuntu 14.04

```
$sudo add-apt-repository ppa:deadsnakes
Cannot add PPA: 'ppa:deadsnakes'.
Please check that the PPA name or format is correct.
```

**Comment by asottile** [comment]
14.04 is no longer supported, plus your issue is unrelated to the original post
