### ISSUE TITLE
Python 3.8 conflicts with 3.6 on ubuntu 18:04

### ISSUE THREAD

**Issue by jjmurre** [deadsnakes/issues#98]
### description

Upgrading python packages conflicts with installed deadsnakes python 3.8

```
Unpacking python3-lib2to3 (3.6.9-1~18.04) over (3.6.8-1~18.04) ...
dpkg: error processing archive /var/cache/apt/archives/python3-lib2to3_3.6.9-1~18.04_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.8/lib2to3/Grammar.txt', which is also in package python3.8-lib2to3 3.8.0-1+bionic2
Preparing to unpack .../python3-distutils_3.6.9-1~18.04_all.deb ...
Unpacking python3-distutils (3.6.9-1~18.04) over (3.6.8-1~18.04) ...
dpkg: error processing archive /var/cache/apt/archives/python3-distutils_3.6.9-1~18.04_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.8/distutils/README', which is also in package python3.8-distutils 3.8.0-1+bionic2
Errors were encountered while processing:
 /var/cache/apt/archives/python3-lib2to3_3.6.9-1~18.04_all.deb
 /var/cache/apt/archives/python3-distutils_3.6.9-1~18.04_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

#### lsb_release -a

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

#### uname -a

```
Linux jan-ThinkPad-T470s 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jjmurre** [comment]
According to:
https://stackoverflow.com/questions/50397705/trying-to-update-libpython3-6-stdlib-results-in-overwrite-error

This can be 'fixed' with:
sudo dpkg --install --force all /var/cache/apt/archives/python3-lib2to3_3.6.9-1~18.04_all.deb
sudo dpkg --install --force all /var/cache/apt/archives/python3-distutils_3.6.9-1~18.04_all.deb

This leads to a lot of 'overwrite' warnings and effectively replaces 3.8 code with 3.6 code (inside /usr/lib/python3.8/). So, to me, this does not seem to be the correct solution. But, at least, the apt packaging system is not in a broken state any more.

**Comment by asottile** [comment]
the python3.8-distutils / python3.8-lib2to3 packages are gone now, I removed them *because* of this conflict :( -- the conflict is unfortunately out of our control, upstream created new python3.8 packages

The fix is to purge the python3.8-distutils / python3.8-lib2to3 packages and then upgrade:

```
sudo apt purge python3.8-distutils python3.8-lib2to3
sudo apt install python3.8
```

**Comment by jjmurre** [comment]
Great! Works! Tx. for the quick reply.

**Comment by dtlam26** [comment]
> According to:
> https://stackoverflow.com/questions/50397705/trying-to-update-libpython3-6-stdlib-results-in-overwrite-error
> 
> This can be 'fixed' with:
> 
> ```
> sudo dpkg --install --force all /var/cache/apt/archives/python3-lib2to3_3.6.9-1~18.04_all.deb
> sudo dpkg --install --force all /var/cache/apt/archives/python3-distutils_3.6.9-1~18.04_all.deb
> ```
> 
> This leads to a lot of 'overwrite' warnings and effectively replaces 3.8 code with 3.6 code (inside /usr/lib/python3.8/). So, to me, this does not seem to be the correct solution. But, at least, the apt packaging system is not in a broken state any more.

THIS SAVE MY DAYYYYYY
